// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { type Activity, ActivityFromJSON, ActivityToJSON } from "../models/Activity";
import { type ApiError, ApiErrorFromJSON, ApiErrorToJSON } from "../models/ApiError";
import {
  type AssignRoleRequest,
  AssignRoleRequestFromJSON,
  AssignRoleRequestToJSON,
} from "../models/AssignRoleRequest";
import {
  type AuthResponse,
  AuthResponseFromJSON,
  AuthResponseToJSON,
} from "../models/AuthResponse";
import { type Club, ClubFromJSON, ClubToJSON } from "../models/Club";
import {
  type CreateClubRequest,
  CreateClubRequestFromJSON,
  CreateClubRequestToJSON,
} from "../models/CreateClubRequest";
import {
  type HealthStatus,
  HealthStatusFromJSON,
  HealthStatusToJSON,
} from "../models/HealthStatus";
import {
  type LoginRequest,
  LoginRequestFromJSON,
  LoginRequestToJSON,
} from "../models/LoginRequest";
import {
  type PermissionCheckResult,
  PermissionCheckResultFromJSON,
  PermissionCheckResultToJSON,
} from "../models/PermissionCheckResult";
import {
  type PermissionDefinition,
  PermissionDefinitionFromJSON,
  PermissionDefinitionToJSON,
} from "../models/PermissionDefinition";
import {
  type RegisterRequest,
  RegisterRequestFromJSON,
  RegisterRequestToJSON,
} from "../models/RegisterRequest";
import {
  type RoleAssignmentResult,
  RoleAssignmentResultFromJSON,
  RoleAssignmentResultToJSON,
} from "../models/RoleAssignmentResult";
import {
  type RoleDefinition,
  RoleDefinitionFromJSON,
  RoleDefinitionToJSON,
} from "../models/RoleDefinition";
import {
  type UpdateClubRequest,
  UpdateClubRequestFromJSON,
  UpdateClubRequestToJSON,
} from "../models/UpdateClubRequest";

export interface AssignUserRoleRequest {
  assignRoleRequest: AssignRoleRequest;
}

export interface CheckPermissionRequest {
  userId: number;
  permission: string;
  clubId?: number;
}

export interface CreateClubOperationRequest {
  createClubRequest: CreateClubRequest;
}

export interface DeleteClubRequest {
  clubId: number;
}

export interface GetActivityByIdRequest {
  activityId: number;
}

export interface GetClubByIdRequest {
  clubId: number;
}

export interface LoginUserRequest {
  loginRequest: LoginRequest;
}

export interface RegisterUserRequest {
  registerRequest: RegisterRequest;
}

export interface UpdateClubOperationRequest {
  clubId: number;
  updateClubRequest: UpdateClubRequest;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Creates request options for assignUserRole without sending the request
   */
  async assignUserRoleRequestOpts(
    requestParameters: AssignUserRoleRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["assignRoleRequest"] == null) {
      throw new runtime.RequiredError(
        "assignRoleRequest",
        'Required parameter "assignRoleRequest" was null or undefined when calling assignUserRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/auth/roles/assign`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: AssignRoleRequestToJSON(requestParameters["assignRoleRequest"]),
    };
  }

  /**
   * 分配用户角色
   */
  async assignUserRoleRaw(
    requestParameters: AssignUserRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RoleAssignmentResult>> {
    const requestOptions = await this.assignUserRoleRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RoleAssignmentResultFromJSON(jsonValue),
    );
  }

  /**
   * 分配用户角色
   */
  async assignUserRole(
    requestParameters: AssignUserRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RoleAssignmentResult> {
    const response = await this.assignUserRoleRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for checkPermission without sending the request
   */
  async checkPermissionRequestOpts(
    requestParameters: CheckPermissionRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling checkPermission().',
      );
    }

    if (requestParameters["permission"] == null) {
      throw new runtime.RequiredError(
        "permission",
        'Required parameter "permission" was null or undefined when calling checkPermission().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["userId"] != null) {
      queryParameters["userId"] = requestParameters["userId"];
    }

    if (requestParameters["permission"] != null) {
      queryParameters["permission"] = requestParameters["permission"];
    }

    if (requestParameters["clubId"] != null) {
      queryParameters["clubId"] = requestParameters["clubId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/auth/permissions/check`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 检查用户是否拥有指定权限
   */
  async checkPermissionRaw(
    requestParameters: CheckPermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PermissionCheckResult>> {
    const requestOptions = await this.checkPermissionRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PermissionCheckResultFromJSON(jsonValue),
    );
  }

  /**
   * 检查用户是否拥有指定权限
   */
  async checkPermission(
    requestParameters: CheckPermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PermissionCheckResult> {
    const response = await this.checkPermissionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createClub without sending the request
   */
  async createClubRequestOpts(
    requestParameters: CreateClubOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["createClubRequest"] == null) {
      throw new runtime.RequiredError(
        "createClubRequest",
        'Required parameter "createClubRequest" was null or undefined when calling createClub().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreateClubRequestToJSON(requestParameters["createClubRequest"]),
    };
  }

  /**
   * 创建社团
   */
  async createClubRaw(
    requestParameters: CreateClubOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Club>> {
    const requestOptions = await this.createClubRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubFromJSON(jsonValue));
  }

  /**
   * 创建社团
   */
  async createClub(
    requestParameters: CreateClubOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Club> {
    const response = await this.createClubRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteClub without sending the request
   */
  async deleteClubRequestOpts(requestParameters: DeleteClubRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling deleteClub().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clubs/{clubId}`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 删除社团
   */
  async deleteClubRaw(
    requestParameters: DeleteClubRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteClubRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 删除社团
   */
  async deleteClub(
    requestParameters: DeleteClubRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteClubRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for getActivities without sending the request
   */
  async getActivitiesRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/activities`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取活动列表
   */
  async getActivitiesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Activity>>> {
    const requestOptions = await this.getActivitiesRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActivityFromJSON));
  }

  /**
   * 获取活动列表
   */
  async getActivities(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Activity>> {
    const response = await this.getActivitiesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getActivityById without sending the request
   */
  async getActivityByIdRequestOpts(
    requestParameters: GetActivityByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["activityId"] == null) {
      throw new runtime.RequiredError(
        "activityId",
        'Required parameter "activityId" was null or undefined when calling getActivityById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/activities/{activityId}`;
    urlPath = urlPath.replace(
      "{activityId}",
      encodeURIComponent(String(requestParameters["activityId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取活动详情
   */
  async getActivityByIdRaw(
    requestParameters: GetActivityByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Activity>> {
    const requestOptions = await this.getActivityByIdRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ActivityFromJSON(jsonValue));
  }

  /**
   * 获取活动详情
   */
  async getActivityById(
    requestParameters: GetActivityByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Activity> {
    const response = await this.getActivityByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getClubById without sending the request
   */
  async getClubByIdRequestOpts(
    requestParameters: GetClubByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling getClubById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clubs/{clubId}`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取社团详情
   */
  async getClubByIdRaw(
    requestParameters: GetClubByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Club>> {
    const requestOptions = await this.getClubByIdRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubFromJSON(jsonValue));
  }

  /**
   * 获取社团详情
   */
  async getClubById(
    requestParameters: GetClubByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Club> {
    const response = await this.getClubByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getClubs without sending the request
   */
  async getClubsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clubs`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取社团列表
   */
  async getClubsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Club>>> {
    const requestOptions = await this.getClubsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClubFromJSON));
  }

  /**
   * 获取社团列表
   */
  async getClubs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Club>> {
    const response = await this.getClubsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getPermissionCatalog without sending the request
   */
  async getPermissionCatalogRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/auth/permissions`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取权限目录
   */
  async getPermissionCatalogRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PermissionDefinition>>> {
    const requestOptions = await this.getPermissionCatalogRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PermissionDefinitionFromJSON),
    );
  }

  /**
   * 获取权限目录
   */
  async getPermissionCatalog(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PermissionDefinition>> {
    const response = await this.getPermissionCatalogRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getRoleDefinitions without sending the request
   */
  async getRoleDefinitionsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/auth/roles`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取基础角色定义
   */
  async getRoleDefinitionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RoleDefinition>>> {
    const requestOptions = await this.getRoleDefinitionsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(RoleDefinitionFromJSON),
    );
  }

  /**
   * 获取基础角色定义
   */
  async getRoleDefinitions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RoleDefinition>> {
    const response = await this.getRoleDefinitionsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for healthCheck without sending the request
   */
  async healthCheckRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/health`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 健康检查
   */
  async healthCheckRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HealthStatus>> {
    const requestOptions = await this.healthCheckRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => HealthStatusFromJSON(jsonValue));
  }

  /**
   * 健康检查
   */
  async healthCheck(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HealthStatus> {
    const response = await this.healthCheckRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for loginUser without sending the request
   */
  async loginUserRequestOpts(requestParameters: LoginUserRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["loginRequest"] == null) {
      throw new runtime.RequiredError(
        "loginRequest",
        'Required parameter "loginRequest" was null or undefined when calling loginUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/auth/login`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: LoginRequestToJSON(requestParameters["loginRequest"]),
    };
  }

  /**
   * 用户登录
   */
  async loginUserRaw(
    requestParameters: LoginUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AuthResponse>> {
    const requestOptions = await this.loginUserRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
  }

  /**
   * 用户登录
   */
  async loginUser(
    requestParameters: LoginUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AuthResponse> {
    const response = await this.loginUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for registerUser without sending the request
   */
  async registerUserRequestOpts(
    requestParameters: RegisterUserRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["registerRequest"] == null) {
      throw new runtime.RequiredError(
        "registerRequest",
        'Required parameter "registerRequest" was null or undefined when calling registerUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/auth/register`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: RegisterRequestToJSON(requestParameters["registerRequest"]),
    };
  }

  /**
   * 用户注册
   */
  async registerUserRaw(
    requestParameters: RegisterUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AuthResponse>> {
    const requestOptions = await this.registerUserRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
  }

  /**
   * 用户注册
   */
  async registerUser(
    requestParameters: RegisterUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AuthResponse> {
    const response = await this.registerUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateClub without sending the request
   */
  async updateClubRequestOpts(
    requestParameters: UpdateClubOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling updateClub().',
      );
    }

    if (requestParameters["updateClubRequest"] == null) {
      throw new runtime.RequiredError(
        "updateClubRequest",
        'Required parameter "updateClubRequest" was null or undefined when calling updateClub().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs/{clubId}`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: UpdateClubRequestToJSON(requestParameters["updateClubRequest"]),
    };
  }

  /**
   * 更新社团
   */
  async updateClubRaw(
    requestParameters: UpdateClubOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Club>> {
    const requestOptions = await this.updateClubRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubFromJSON(jsonValue));
  }

  /**
   * 更新社团
   */
  async updateClub(
    requestParameters: UpdateClubOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Club> {
    const response = await this.updateClubRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
