// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { type Activity, ActivityFromJSON, ActivityToJSON } from "../models/Activity";
import { type ApiError, ApiErrorFromJSON, ApiErrorToJSON } from "../models/ApiError";
import {
  type AssignRoleRequest,
  AssignRoleRequestFromJSON,
  AssignRoleRequestToJSON,
} from "../models/AssignRoleRequest";
import {
  type AuthResponse,
  AuthResponseFromJSON,
  AuthResponseToJSON,
} from "../models/AuthResponse";
import { type Club, ClubFromJSON, ClubToJSON } from "../models/Club";
import {
  type ClubApplication,
  ClubApplicationFromJSON,
  ClubApplicationToJSON,
} from "../models/ClubApplication";
import {
  type ClubMemberRecord,
  ClubMemberRecordFromJSON,
  ClubMemberRecordToJSON,
} from "../models/ClubMemberRecord";
import {
  type CreateClubApplicationRequest,
  CreateClubApplicationRequestFromJSON,
  CreateClubApplicationRequestToJSON,
} from "../models/CreateClubApplicationRequest";
import {
  type CreateClubMemberTermRequest,
  CreateClubMemberTermRequestFromJSON,
  CreateClubMemberTermRequestToJSON,
} from "../models/CreateClubMemberTermRequest";
import {
  type CreateClubRequest,
  CreateClubRequestFromJSON,
  CreateClubRequestToJSON,
} from "../models/CreateClubRequest";
import {
  type HealthStatus,
  HealthStatusFromJSON,
  HealthStatusToJSON,
} from "../models/HealthStatus";
import {
  type LoginRequest,
  LoginRequestFromJSON,
  LoginRequestToJSON,
} from "../models/LoginRequest";
import {
  type PermissionCheckResult,
  PermissionCheckResultFromJSON,
  PermissionCheckResultToJSON,
} from "../models/PermissionCheckResult";
import {
  type PermissionDefinition,
  PermissionDefinitionFromJSON,
  PermissionDefinitionToJSON,
} from "../models/PermissionDefinition";
import {
  type RegisterRequest,
  RegisterRequestFromJSON,
  RegisterRequestToJSON,
} from "../models/RegisterRequest";
import {
  type ReviewClubApplicationRequest,
  ReviewClubApplicationRequestFromJSON,
  ReviewClubApplicationRequestToJSON,
} from "../models/ReviewClubApplicationRequest";
import {
  type RoleAssignmentResult,
  RoleAssignmentResultFromJSON,
  RoleAssignmentResultToJSON,
} from "../models/RoleAssignmentResult";
import {
  type RoleDefinition,
  RoleDefinitionFromJSON,
  RoleDefinitionToJSON,
} from "../models/RoleDefinition";
import {
  type UpdateClubMemberTermRequest,
  UpdateClubMemberTermRequestFromJSON,
  UpdateClubMemberTermRequestToJSON,
} from "../models/UpdateClubMemberTermRequest";
import {
  type UpdateClubProfileRequest,
  UpdateClubProfileRequestFromJSON,
  UpdateClubProfileRequestToJSON,
} from "../models/UpdateClubProfileRequest";
import {
  type UpdateClubRequest,
  UpdateClubRequestFromJSON,
  UpdateClubRequestToJSON,
} from "../models/UpdateClubRequest";
import { type UserSummary, UserSummaryFromJSON, UserSummaryToJSON } from "../models/UserSummary";

export interface AssignUserRoleRequest {
  assignRoleRequest: AssignRoleRequest;
}

export interface CheckPermissionRequest {
  userId: number;
  permission: string;
  clubId?: number;
}

export interface CreateClubOperationRequest {
  createClubRequest: CreateClubRequest;
}

export interface CreateClubApplicationOperationRequest {
  createClubApplicationRequest: CreateClubApplicationRequest;
}

export interface CreateClubMemberTermOperationRequest {
  clubId: number;
  createClubMemberTermRequest: CreateClubMemberTermRequest;
}

export interface DeleteClubRequest {
  clubId: number;
}

export interface GetActivityByIdRequest {
  activityId: number;
}

export interface GetClubApplicationsRequest {
  viewerUserId: number;
  auditStatus?: GetClubApplicationsAuditStatusEnum;
}

export interface GetClubByIdRequest {
  clubId: number;
}

export interface GetClubMembersRequest {
  clubId: number;
  viewerUserId: number;
  includeHistory?: boolean;
}

export interface GetClubsRequest {
  viewerUserId?: number;
}

export interface LoginUserRequest {
  loginRequest: LoginRequest;
}

export interface RegisterUserRequest {
  registerRequest: RegisterRequest;
}

export interface ReviewClubApplicationOperationRequest {
  clubId: number;
  reviewClubApplicationRequest: ReviewClubApplicationRequest;
}

export interface UpdateClubOperationRequest {
  clubId: number;
  updateClubRequest: UpdateClubRequest;
}

export interface UpdateClubMemberTermOperationRequest {
  clubId: number;
  memberId: number;
  updateClubMemberTermRequest: UpdateClubMemberTermRequest;
}

export interface UpdateClubProfileOperationRequest {
  clubId: number;
  updateClubProfileRequest: UpdateClubProfileRequest;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Creates request options for assignUserRole without sending the request
   */
  async assignUserRoleRequestOpts(
    requestParameters: AssignUserRoleRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["assignRoleRequest"] == null) {
      throw new runtime.RequiredError(
        "assignRoleRequest",
        'Required parameter "assignRoleRequest" was null or undefined when calling assignUserRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/auth/roles/assign`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: AssignRoleRequestToJSON(requestParameters["assignRoleRequest"]),
    };
  }

  /**
   * 分配用户角色
   */
  async assignUserRoleRaw(
    requestParameters: AssignUserRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RoleAssignmentResult>> {
    const requestOptions = await this.assignUserRoleRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RoleAssignmentResultFromJSON(jsonValue),
    );
  }

  /**
   * 分配用户角色
   */
  async assignUserRole(
    requestParameters: AssignUserRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RoleAssignmentResult> {
    const response = await this.assignUserRoleRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for checkPermission without sending the request
   */
  async checkPermissionRequestOpts(
    requestParameters: CheckPermissionRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling checkPermission().',
      );
    }

    if (requestParameters["permission"] == null) {
      throw new runtime.RequiredError(
        "permission",
        'Required parameter "permission" was null or undefined when calling checkPermission().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["userId"] != null) {
      queryParameters["userId"] = requestParameters["userId"];
    }

    if (requestParameters["permission"] != null) {
      queryParameters["permission"] = requestParameters["permission"];
    }

    if (requestParameters["clubId"] != null) {
      queryParameters["clubId"] = requestParameters["clubId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/auth/permissions/check`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 检查用户是否拥有指定权限
   */
  async checkPermissionRaw(
    requestParameters: CheckPermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PermissionCheckResult>> {
    const requestOptions = await this.checkPermissionRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PermissionCheckResultFromJSON(jsonValue),
    );
  }

  /**
   * 检查用户是否拥有指定权限
   */
  async checkPermission(
    requestParameters: CheckPermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PermissionCheckResult> {
    const response = await this.checkPermissionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createClub without sending the request
   */
  async createClubRequestOpts(
    requestParameters: CreateClubOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["createClubRequest"] == null) {
      throw new runtime.RequiredError(
        "createClubRequest",
        'Required parameter "createClubRequest" was null or undefined when calling createClub().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreateClubRequestToJSON(requestParameters["createClubRequest"]),
    };
  }

  /**
   * 创建社团
   */
  async createClubRaw(
    requestParameters: CreateClubOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Club>> {
    const requestOptions = await this.createClubRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubFromJSON(jsonValue));
  }

  /**
   * 创建社团
   */
  async createClub(
    requestParameters: CreateClubOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Club> {
    const response = await this.createClubRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createClubApplication without sending the request
   */
  async createClubApplicationRequestOpts(
    requestParameters: CreateClubApplicationOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["createClubApplicationRequest"] == null) {
      throw new runtime.RequiredError(
        "createClubApplicationRequest",
        'Required parameter "createClubApplicationRequest" was null or undefined when calling createClubApplication().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs/applications`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreateClubApplicationRequestToJSON(requestParameters["createClubApplicationRequest"]),
    };
  }

  /**
   * 仅学生角色可以提交社团注册申请；平台管理员、指导老师等非学生角色不能通过该入口发起申请。
   * 提交社团注册申请
   */
  async createClubApplicationRaw(
    requestParameters: CreateClubApplicationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClubApplication>> {
    const requestOptions = await this.createClubApplicationRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubApplicationFromJSON(jsonValue));
  }

  /**
   * 仅学生角色可以提交社团注册申请；平台管理员、指导老师等非学生角色不能通过该入口发起申请。
   * 提交社团注册申请
   */
  async createClubApplication(
    requestParameters: CreateClubApplicationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClubApplication> {
    const response = await this.createClubApplicationRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createClubMemberTerm without sending the request
   */
  async createClubMemberTermRequestOpts(
    requestParameters: CreateClubMemberTermOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling createClubMemberTerm().',
      );
    }

    if (requestParameters["createClubMemberTermRequest"] == null) {
      throw new runtime.RequiredError(
        "createClubMemberTermRequest",
        'Required parameter "createClubMemberTermRequest" was null or undefined when calling createClubMemberTerm().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs/{clubId}/members/terms`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreateClubMemberTermRequestToJSON(requestParameters["createClubMemberTermRequest"]),
    };
  }

  /**
   * 平台管理员或本社团负责人可以为成员新增职位任期；新增任期时可关闭该成员原有效任期以保留历史记录。
   * 新增社团成员或干部任期
   */
  async createClubMemberTermRaw(
    requestParameters: CreateClubMemberTermOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClubMemberRecord>> {
    const requestOptions = await this.createClubMemberTermRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClubMemberRecordFromJSON(jsonValue),
    );
  }

  /**
   * 平台管理员或本社团负责人可以为成员新增职位任期；新增任期时可关闭该成员原有效任期以保留历史记录。
   * 新增社团成员或干部任期
   */
  async createClubMemberTerm(
    requestParameters: CreateClubMemberTermOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClubMemberRecord> {
    const response = await this.createClubMemberTermRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteClub without sending the request
   */
  async deleteClubRequestOpts(requestParameters: DeleteClubRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling deleteClub().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clubs/{clubId}`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 删除社团
   */
  async deleteClubRaw(
    requestParameters: DeleteClubRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteClubRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 删除社团
   */
  async deleteClub(
    requestParameters: DeleteClubRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteClubRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for getActivities without sending the request
   */
  async getActivitiesRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/activities`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取活动列表
   */
  async getActivitiesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Activity>>> {
    const requestOptions = await this.getActivitiesRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActivityFromJSON));
  }

  /**
   * 获取活动列表
   */
  async getActivities(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Activity>> {
    const response = await this.getActivitiesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getActivityById without sending the request
   */
  async getActivityByIdRequestOpts(
    requestParameters: GetActivityByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["activityId"] == null) {
      throw new runtime.RequiredError(
        "activityId",
        'Required parameter "activityId" was null or undefined when calling getActivityById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/activities/{activityId}`;
    urlPath = urlPath.replace(
      "{activityId}",
      encodeURIComponent(String(requestParameters["activityId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取活动详情
   */
  async getActivityByIdRaw(
    requestParameters: GetActivityByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Activity>> {
    const requestOptions = await this.getActivityByIdRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ActivityFromJSON(jsonValue));
  }

  /**
   * 获取活动详情
   */
  async getActivityById(
    requestParameters: GetActivityByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Activity> {
    const response = await this.getActivityByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getClubApplications without sending the request
   */
  async getClubApplicationsRequestOpts(
    requestParameters: GetClubApplicationsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["viewerUserId"] == null) {
      throw new runtime.RequiredError(
        "viewerUserId",
        'Required parameter "viewerUserId" was null or undefined when calling getClubApplications().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["viewerUserId"] != null) {
      queryParameters["viewerUserId"] = requestParameters["viewerUserId"];
    }

    if (requestParameters["auditStatus"] != null) {
      queryParameters["auditStatus"] = requestParameters["auditStatus"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clubs/applications`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 按当前用户权限查询社团注册申请
   */
  async getClubApplicationsRaw(
    requestParameters: GetClubApplicationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClubApplication>>> {
    const requestOptions = await this.getClubApplicationsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClubApplicationFromJSON),
    );
  }

  /**
   * 按当前用户权限查询社团注册申请
   */
  async getClubApplications(
    requestParameters: GetClubApplicationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClubApplication>> {
    const response = await this.getClubApplicationsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getClubById without sending the request
   */
  async getClubByIdRequestOpts(
    requestParameters: GetClubByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling getClubById().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clubs/{clubId}`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取社团详情
   */
  async getClubByIdRaw(
    requestParameters: GetClubByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Club>> {
    const requestOptions = await this.getClubByIdRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubFromJSON(jsonValue));
  }

  /**
   * 获取社团详情
   */
  async getClubById(
    requestParameters: GetClubByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Club> {
    const response = await this.getClubByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getClubMembers without sending the request
   */
  async getClubMembersRequestOpts(
    requestParameters: GetClubMembersRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling getClubMembers().',
      );
    }

    if (requestParameters["viewerUserId"] == null) {
      throw new runtime.RequiredError(
        "viewerUserId",
        'Required parameter "viewerUserId" was null or undefined when calling getClubMembers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["viewerUserId"] != null) {
      queryParameters["viewerUserId"] = requestParameters["viewerUserId"];
    }

    if (requestParameters["includeHistory"] != null) {
      queryParameters["includeHistory"] = requestParameters["includeHistory"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clubs/{clubId}/members`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 平台管理员、本社团负责人和本社团成员可以查看成员及任期；默认仅返回当前有效记录，可选择包含历史记录。
   * 查询社团成员与干部任期记录
   */
  async getClubMembersRaw(
    requestParameters: GetClubMembersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClubMemberRecord>>> {
    const requestOptions = await this.getClubMembersRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClubMemberRecordFromJSON),
    );
  }

  /**
   * 平台管理员、本社团负责人和本社团成员可以查看成员及任期；默认仅返回当前有效记录，可选择包含历史记录。
   * 查询社团成员与干部任期记录
   */
  async getClubMembers(
    requestParameters: GetClubMembersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClubMemberRecord>> {
    const response = await this.getClubMembersRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getClubs without sending the request
   */
  async getClubsRequestOpts(requestParameters: GetClubsRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["viewerUserId"] != null) {
      queryParameters["viewerUserId"] = requestParameters["viewerUserId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clubs`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取社团列表
   */
  async getClubsRaw(
    requestParameters: GetClubsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Club>>> {
    const requestOptions = await this.getClubsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClubFromJSON));
  }

  /**
   * 获取社团列表
   */
  async getClubs(
    requestParameters: GetClubsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Club>> {
    const response = await this.getClubsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getPermissionCatalog without sending the request
   */
  async getPermissionCatalogRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/auth/permissions`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取权限目录
   */
  async getPermissionCatalogRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PermissionDefinition>>> {
    const requestOptions = await this.getPermissionCatalogRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PermissionDefinitionFromJSON),
    );
  }

  /**
   * 获取权限目录
   */
  async getPermissionCatalog(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PermissionDefinition>> {
    const response = await this.getPermissionCatalogRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getRoleDefinitions without sending the request
   */
  async getRoleDefinitionsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/auth/roles`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取基础角色定义
   */
  async getRoleDefinitionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RoleDefinition>>> {
    const requestOptions = await this.getRoleDefinitionsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(RoleDefinitionFromJSON),
    );
  }

  /**
   * 获取基础角色定义
   */
  async getRoleDefinitions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RoleDefinition>> {
    const response = await this.getRoleDefinitionsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getUsers without sending the request
   */
  async getUsersRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/users`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 获取可切换的当前用户列表
   */
  async getUsersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<UserSummary>>> {
    const requestOptions = await this.getUsersRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserSummaryFromJSON));
  }

  /**
   * 获取可切换的当前用户列表
   */
  async getUsers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<UserSummary>> {
    const response = await this.getUsersRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for healthCheck without sending the request
   */
  async healthCheckRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/health`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 健康检查
   */
  async healthCheckRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HealthStatus>> {
    const requestOptions = await this.healthCheckRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => HealthStatusFromJSON(jsonValue));
  }

  /**
   * 健康检查
   */
  async healthCheck(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HealthStatus> {
    const response = await this.healthCheckRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for loginUser without sending the request
   */
  async loginUserRequestOpts(requestParameters: LoginUserRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["loginRequest"] == null) {
      throw new runtime.RequiredError(
        "loginRequest",
        'Required parameter "loginRequest" was null or undefined when calling loginUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/auth/login`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: LoginRequestToJSON(requestParameters["loginRequest"]),
    };
  }

  /**
   * 用户登录
   */
  async loginUserRaw(
    requestParameters: LoginUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AuthResponse>> {
    const requestOptions = await this.loginUserRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
  }

  /**
   * 用户登录
   */
  async loginUser(
    requestParameters: LoginUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AuthResponse> {
    const response = await this.loginUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for registerUser without sending the request
   */
  async registerUserRequestOpts(
    requestParameters: RegisterUserRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["registerRequest"] == null) {
      throw new runtime.RequiredError(
        "registerRequest",
        'Required parameter "registerRequest" was null or undefined when calling registerUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/auth/register`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: RegisterRequestToJSON(requestParameters["registerRequest"]),
    };
  }

  /**
   * 用户注册
   */
  async registerUserRaw(
    requestParameters: RegisterUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AuthResponse>> {
    const requestOptions = await this.registerUserRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
  }

  /**
   * 用户注册
   */
  async registerUser(
    requestParameters: RegisterUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AuthResponse> {
    const response = await this.registerUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for reviewClubApplication without sending the request
   */
  async reviewClubApplicationRequestOpts(
    requestParameters: ReviewClubApplicationOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling reviewClubApplication().',
      );
    }

    if (requestParameters["reviewClubApplicationRequest"] == null) {
      throw new runtime.RequiredError(
        "reviewClubApplicationRequest",
        'Required parameter "reviewClubApplicationRequest" was null or undefined when calling reviewClubApplication().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs/applications/{clubId}/review`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "PATCH",
      headers: headerParameters,
      query: queryParameters,
      body: ReviewClubApplicationRequestToJSON(requestParameters["reviewClubApplicationRequest"]),
    };
  }

  /**
   * 平台管理员审核社团注册申请
   */
  async reviewClubApplicationRaw(
    requestParameters: ReviewClubApplicationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClubApplication>> {
    const requestOptions = await this.reviewClubApplicationRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubApplicationFromJSON(jsonValue));
  }

  /**
   * 平台管理员审核社团注册申请
   */
  async reviewClubApplication(
    requestParameters: ReviewClubApplicationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClubApplication> {
    const response = await this.reviewClubApplicationRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateClub without sending the request
   */
  async updateClubRequestOpts(
    requestParameters: UpdateClubOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling updateClub().',
      );
    }

    if (requestParameters["updateClubRequest"] == null) {
      throw new runtime.RequiredError(
        "updateClubRequest",
        'Required parameter "updateClubRequest" was null or undefined when calling updateClub().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs/{clubId}`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: UpdateClubRequestToJSON(requestParameters["updateClubRequest"]),
    };
  }

  /**
   * 更新社团
   */
  async updateClubRaw(
    requestParameters: UpdateClubOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Club>> {
    const requestOptions = await this.updateClubRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubFromJSON(jsonValue));
  }

  /**
   * 更新社团
   */
  async updateClub(
    requestParameters: UpdateClubOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Club> {
    const response = await this.updateClubRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateClubMemberTerm without sending the request
   */
  async updateClubMemberTermRequestOpts(
    requestParameters: UpdateClubMemberTermOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling updateClubMemberTerm().',
      );
    }

    if (requestParameters["memberId"] == null) {
      throw new runtime.RequiredError(
        "memberId",
        'Required parameter "memberId" was null or undefined when calling updateClubMemberTerm().',
      );
    }

    if (requestParameters["updateClubMemberTermRequest"] == null) {
      throw new runtime.RequiredError(
        "updateClubMemberTermRequest",
        'Required parameter "updateClubMemberTermRequest" was null or undefined when calling updateClubMemberTerm().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs/{clubId}/members/{memberId}`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));
    urlPath = urlPath.replace(
      "{memberId}",
      encodeURIComponent(String(requestParameters["memberId"])),
    );

    return {
      path: urlPath,
      method: "PATCH",
      headers: headerParameters,
      query: queryParameters,
      body: UpdateClubMemberTermRequestToJSON(requestParameters["updateClubMemberTermRequest"]),
    };
  }

  /**
   * 平台管理员或本社团负责人可以修正成员部门、职位、任期和状态，不删除历史记录。
   * 更新社团成员或干部任期
   */
  async updateClubMemberTermRaw(
    requestParameters: UpdateClubMemberTermOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClubMemberRecord>> {
    const requestOptions = await this.updateClubMemberTermRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClubMemberRecordFromJSON(jsonValue),
    );
  }

  /**
   * 平台管理员或本社团负责人可以修正成员部门、职位、任期和状态，不删除历史记录。
   * 更新社团成员或干部任期
   */
  async updateClubMemberTerm(
    requestParameters: UpdateClubMemberTermOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClubMemberRecord> {
    const response = await this.updateClubMemberTermRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateClubProfile without sending the request
   */
  async updateClubProfileRequestOpts(
    requestParameters: UpdateClubProfileOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["clubId"] == null) {
      throw new runtime.RequiredError(
        "clubId",
        'Required parameter "clubId" was null or undefined when calling updateClubProfile().',
      );
    }

    if (requestParameters["updateClubProfileRequest"] == null) {
      throw new runtime.RequiredError(
        "updateClubProfileRequest",
        'Required parameter "updateClubProfileRequest" was null or undefined when calling updateClubProfile().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clubs/{clubId}/profile`;
    urlPath = urlPath.replace("{clubId}", encodeURIComponent(String(requestParameters["clubId"])));

    return {
      path: urlPath,
      method: "PATCH",
      headers: headerParameters,
      query: queryParameters,
      body: UpdateClubProfileRequestToJSON(requestParameters["updateClubProfileRequest"]),
    };
  }

  /**
   * 平台管理员或本社团负责人可以维护社团简介、联系方式、指导老师和负责人信息。
   * 维护社团基础信息
   */
  async updateClubProfileRaw(
    requestParameters: UpdateClubProfileOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Club>> {
    const requestOptions = await this.updateClubProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ClubFromJSON(jsonValue));
  }

  /**
   * 平台管理员或本社团负责人可以维护社团简介、联系方式、指导老师和负责人信息。
   * 维护社团基础信息
   */
  async updateClubProfile(
    requestParameters: UpdateClubProfileOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Club> {
    const response = await this.updateClubProfileRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const GetClubApplicationsAuditStatusEnum = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
} as const;
export type GetClubApplicationsAuditStatusEnum =
  (typeof GetClubApplicationsAuditStatusEnum)[keyof typeof GetClubApplicationsAuditStatusEnum];
