/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  replaceWithSerializableTypeIfNeeded,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { Activity } from "../models";
// @ts-ignore
import type { Club } from "../models";
// @ts-ignore
import type { CreateClubRequest } from "../models";
// @ts-ignore
import type { HealthStatus } from "../models";
// @ts-ignore
import type { UpdateClubRequest } from "../models";
/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary 创建社团
     * @param {CreateClubRequest} createClubRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createClub: async (
      createClubRequest: CreateClubRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createClubRequest' is not null or undefined
      assertParamExists("createClub", "createClubRequest", createClubRequest);
      const localVarPath = `/api/clubs`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createClubRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 删除社团
     * @param {number} clubId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteClub: async (
      clubId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'clubId' is not null or undefined
      assertParamExists("deleteClub", "clubId", clubId);
      const localVarPath = `/api/clubs/{clubId}`.replace(
        "{clubId}",
        encodeURIComponent(String(clubId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "DELETE", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 获取活动列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getActivities: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/activities`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 获取活动详情
     * @param {number} activityId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getActivityById: async (
      activityId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'activityId' is not null or undefined
      assertParamExists("getActivityById", "activityId", activityId);
      const localVarPath = `/api/activities/{activityId}`.replace(
        "{activityId}",
        encodeURIComponent(String(activityId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 获取社团详情
     * @param {number} clubId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getClubById: async (
      clubId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'clubId' is not null or undefined
      assertParamExists("getClubById", "clubId", clubId);
      const localVarPath = `/api/clubs/{clubId}`.replace(
        "{clubId}",
        encodeURIComponent(String(clubId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 获取社团列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getClubs: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/clubs`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 健康检查
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthCheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/health`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 更新社团
     * @param {number} clubId
     * @param {UpdateClubRequest} updateClubRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateClub: async (
      clubId: number,
      updateClubRequest: UpdateClubRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'clubId' is not null or undefined
      assertParamExists("updateClub", "clubId", clubId);
      // verify required parameter 'updateClubRequest' is not null or undefined
      assertParamExists("updateClub", "updateClubRequest", updateClubRequest);
      const localVarPath = `/api/clubs/{clubId}`.replace(
        "{clubId}",
        encodeURIComponent(String(clubId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "PUT", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateClubRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary 创建社团
     * @param {CreateClubRequest} createClubRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createClub(
      createClubRequest: CreateClubRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Club>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createClub(
        createClubRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.createClub"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 删除社团
     * @param {number} clubId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteClub(
      clubId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteClub(clubId, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.deleteClub"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 获取活动列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getActivities(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Activity>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getActivities(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.getActivities"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 获取活动详情
     * @param {number} activityId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getActivityById(
      activityId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Activity>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getActivityById(
        activityId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.getActivityById"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 获取社团详情
     * @param {number} clubId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getClubById(
      clubId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Club>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getClubById(clubId, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.getClubById"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 获取社团列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getClubs(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Club>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getClubs(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.getClubs"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 健康检查
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async healthCheck(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthStatus>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheck(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.healthCheck"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 更新社团
     * @param {number} clubId
     * @param {UpdateClubRequest} updateClubRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateClub(
      clubId: number,
      updateClubRequest: UpdateClubRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Club>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateClub(
        clubId,
        updateClubRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.updateClub"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DefaultApiFp(configuration);
  return {
    /**
     *
     * @summary 创建社团
     * @param {CreateClubRequest} createClubRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createClub(
      createClubRequest: CreateClubRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Club> {
      return localVarFp
        .createClub(createClubRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 删除社团
     * @param {number} clubId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteClub(clubId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp.deleteClub(clubId, options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 获取活动列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getActivities(options?: RawAxiosRequestConfig): AxiosPromise<Array<Activity>> {
      return localVarFp.getActivities(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 获取活动详情
     * @param {number} activityId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getActivityById(activityId: number, options?: RawAxiosRequestConfig): AxiosPromise<Activity> {
      return localVarFp
        .getActivityById(activityId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 获取社团详情
     * @param {number} clubId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getClubById(clubId: number, options?: RawAxiosRequestConfig): AxiosPromise<Club> {
      return localVarFp.getClubById(clubId, options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 获取社团列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getClubs(options?: RawAxiosRequestConfig): AxiosPromise<Array<Club>> {
      return localVarFp.getClubs(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 健康检查
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthCheck(options?: RawAxiosRequestConfig): AxiosPromise<HealthStatus> {
      return localVarFp.healthCheck(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 更新社团
     * @param {number} clubId
     * @param {UpdateClubRequest} updateClubRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateClub(
      clubId: number,
      updateClubRequest: UpdateClubRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Club> {
      return localVarFp
        .updateClub(clubId, updateClubRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
  /**
   *
   * @summary 创建社团
   * @param {CreateClubRequest} createClubRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createClub(createClubRequest: CreateClubRequest, options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .createClub(createClubRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 删除社团
   * @param {number} clubId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteClub(clubId: number, options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .deleteClub(clubId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 获取活动列表
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getActivities(options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .getActivities(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 获取活动详情
   * @param {number} activityId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getActivityById(activityId: number, options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .getActivityById(activityId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 获取社团详情
   * @param {number} clubId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getClubById(clubId: number, options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .getClubById(clubId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 获取社团列表
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getClubs(options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .getClubs(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 健康检查
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public healthCheck(options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .healthCheck(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 更新社团
   * @param {number} clubId
   * @param {UpdateClubRequest} updateClubRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateClub(
    clubId: number,
    updateClubRequest: UpdateClubRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DefaultApiFp(this.configuration)
      .updateClub(clubId, updateClubRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
