// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from "../runtime";
/**
 *
 * @export
 * @interface Activity
 */
export interface Activity {
  /**
   *
   */
  id: number;
  /**
   *
   */
  title: string;
  /**
   *
   */
  activityType?: string | null;
  /**
   *
   */
  description?: string | null;
  /**
   *
   */
  clubName: string;
  /**
   *
   */
  clubId: number;
  /**
   *
   */
  creatorUserId?: number | null;
  /**
   *
   */
  startTime: Date | null;
  /**
   *
   */
  endTime: Date | null;
  /**
   *
   */
  location?: string | null;
  /**
   *
   */
  status: ActivityStatusEnum;
  /**
   *
   */
  maxParticipants?: number | null;
  /**
   *
   */
  registrationDeadline?: Date | null;
  /**
   *
   */
  reviewerUserId?: number | null;
  /**
   *
   */
  reviewComment?: string | null;
  /**
   * 活动经费预算金额，未申请时为空。
   */
  budgetAmount?: number | null;
  /**
   * 活动经费用途，未申请时为空。
   */
  budgetPurpose?: string | null;
  /**
   * 活动经费预算明细，未申请时为空。
   */
  budgetDetail?: string | null;
  /**
   * 经费审批状态，可取 pending、approved、rejected；为空表示尚未提交经费申请。
   */
  budgetStatus?: string | null;
  /**
   * 经费审批人用户 ID。
   */
  budgetReviewerId?: number | null;
  /**
   * 经费审批意见。
   */
  budgetComment?: string | null;
  /**
   *
   */
  publishedAt?: Date | null;
  /**
   *
   */
  checkinStartAt?: Date | null;
  /**
   *
   */
  checkinEndAt?: Date | null;
  /**
   *
   */
  checkoutStartAt?: Date | null;
  /**
   *
   */
  checkoutEndAt?: Date | null;
  /**
   *
   */
  currentParticipants: number;
  /**
   * 当前用户是否已报名；未传 currentUserId 时为 false
   */
  isRegistered: boolean;
}

/**
 * @export
 */
export const ActivityStatusEnum = {
  Draft: "draft",
  PendingReview: "pending_review",
  Published: "published",
  Rejected: "rejected",
  Ongoing: "ongoing",
  Finished: "finished",
  Cancelled: "cancelled",
} as const;
export type ActivityStatusEnum = (typeof ActivityStatusEnum)[keyof typeof ActivityStatusEnum];

/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("clubName" in value) || value["clubName"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("startTime" in value) || value["startTime"] === undefined) return false;
  if (!("endTime" in value) || value["endTime"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("currentParticipants" in value) || value["currentParticipants"] === undefined) return false;
  if (!("isRegistered" in value) || value["isRegistered"] === undefined) return false;
  return true;
}

export function ActivityFromJSON(json: any): Activity {
  return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    activityType:
      json["activityType"] === undefined
        ? undefined
        : json["activityType"] === null
          ? null
          : json["activityType"],
    description:
      json["description"] === undefined
        ? undefined
        : json["description"] === null
          ? null
          : json["description"],
    clubName: json["clubName"],
    clubId: json["clubId"],
    creatorUserId:
      json["creatorUserId"] === undefined
        ? undefined
        : json["creatorUserId"] === null
          ? null
          : json["creatorUserId"],
    startTime: json["startTime"] == null ? null : parseDateTime(json["startTime"]),
    endTime: json["endTime"] == null ? null : parseDateTime(json["endTime"]),
    location:
      json["location"] === undefined
        ? undefined
        : json["location"] === null
          ? null
          : json["location"],
    status: json["status"],
    maxParticipants:
      json["maxParticipants"] === undefined
        ? undefined
        : json["maxParticipants"] === null
          ? null
          : json["maxParticipants"],
    registrationDeadline:
      json["registrationDeadline"] === undefined
        ? undefined
        : json["registrationDeadline"] === null
          ? null
          : parseDateTime(json["registrationDeadline"]),
    reviewerUserId:
      json["reviewerUserId"] === undefined
        ? undefined
        : json["reviewerUserId"] === null
          ? null
          : json["reviewerUserId"],
    reviewComment:
      json["reviewComment"] === undefined
        ? undefined
        : json["reviewComment"] === null
          ? null
          : json["reviewComment"],
    budgetAmount:
      json["budgetAmount"] === undefined
        ? undefined
        : json["budgetAmount"] === null
          ? null
          : json["budgetAmount"],
    budgetPurpose:
      json["budgetPurpose"] === undefined
        ? undefined
        : json["budgetPurpose"] === null
          ? null
          : json["budgetPurpose"],
    budgetDetail:
      json["budgetDetail"] === undefined
        ? undefined
        : json["budgetDetail"] === null
          ? null
          : json["budgetDetail"],
    budgetStatus:
      json["budgetStatus"] === undefined
        ? undefined
        : json["budgetStatus"] === null
          ? null
          : json["budgetStatus"],
    budgetReviewerId:
      json["budgetReviewerId"] === undefined
        ? undefined
        : json["budgetReviewerId"] === null
          ? null
          : json["budgetReviewerId"],
    budgetComment:
      json["budgetComment"] === undefined
        ? undefined
        : json["budgetComment"] === null
          ? null
          : json["budgetComment"],
    publishedAt:
      json["publishedAt"] === undefined
        ? undefined
        : json["publishedAt"] === null
          ? null
          : parseDateTime(json["publishedAt"]),
    checkinStartAt:
      json["checkinStartAt"] === undefined
        ? undefined
        : json["checkinStartAt"] === null
          ? null
          : parseDateTime(json["checkinStartAt"]),
    checkinEndAt:
      json["checkinEndAt"] === undefined
        ? undefined
        : json["checkinEndAt"] === null
          ? null
          : parseDateTime(json["checkinEndAt"]),
    checkoutStartAt:
      json["checkoutStartAt"] === undefined
        ? undefined
        : json["checkoutStartAt"] === null
          ? null
          : parseDateTime(json["checkoutStartAt"]),
    checkoutEndAt:
      json["checkoutEndAt"] === undefined
        ? undefined
        : json["checkoutEndAt"] === null
          ? null
          : parseDateTime(json["checkoutEndAt"]),
    currentParticipants: json["currentParticipants"],
    isRegistered: json["isRegistered"],
  };
}

export function ActivityToJSON(json: any): Activity {
  return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(
  value?: Activity | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    activityType: value["activityType"],
    description: value["description"],
    clubName: value["clubName"],
    clubId: value["clubId"],
    creatorUserId: value["creatorUserId"],
    startTime:
      value["startTime"] == null ? value["startTime"] : serializeDateTime(value["startTime"]),
    endTime: value["endTime"] == null ? value["endTime"] : serializeDateTime(value["endTime"]),
    location: value["location"],
    status: value["status"],
    maxParticipants: value["maxParticipants"],
    registrationDeadline:
      value["registrationDeadline"] == null
        ? value["registrationDeadline"]
        : serializeDateTime(value["registrationDeadline"]),
    reviewerUserId: value["reviewerUserId"],
    reviewComment: value["reviewComment"],
    budgetAmount: value["budgetAmount"],
    budgetPurpose: value["budgetPurpose"],
    budgetDetail: value["budgetDetail"],
    budgetStatus: value["budgetStatus"],
    budgetReviewerId: value["budgetReviewerId"],
    budgetComment: value["budgetComment"],
    publishedAt:
      value["publishedAt"] == null ? value["publishedAt"] : serializeDateTime(value["publishedAt"]),
    checkinStartAt:
      value["checkinStartAt"] == null
        ? value["checkinStartAt"]
        : serializeDateTime(value["checkinStartAt"]),
    checkinEndAt:
      value["checkinEndAt"] == null
        ? value["checkinEndAt"]
        : serializeDateTime(value["checkinEndAt"]),
    checkoutStartAt:
      value["checkoutStartAt"] == null
        ? value["checkoutStartAt"]
        : serializeDateTime(value["checkoutStartAt"]),
    checkoutEndAt:
      value["checkoutEndAt"] == null
        ? value["checkoutEndAt"]
        : serializeDateTime(value["checkoutEndAt"]),
    currentParticipants: value["currentParticipants"],
    isRegistered: value["isRegistered"],
  };
}
