// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ActivityParticipation
 */
export interface ActivityParticipation {
  /**
   *
   * @type {number}
   * @memberof ActivityParticipation
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof ActivityParticipation
   */
  activityId: number;
  /**
   *
   * @type {number}
   * @memberof ActivityParticipation
   */
  userId: number;
  /**
   * 参与者姓名；姓名为空时回退为用户名。
   * @type {string}
   * @memberof ActivityParticipation
   */
  userName: string;
  /**
   * 参与者学号或工号。
   * @type {string}
   * @memberof ActivityParticipation
   */
  studentNo?: string | null;
  /**
   *
   * @type {string}
   * @memberof ActivityParticipation
   */
  registerStatus?: string | null;
  /**
   *
   * @type {Date}
   * @memberof ActivityParticipation
   */
  registeredAt?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof ActivityParticipation
   */
  checkinAt?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof ActivityParticipation
   */
  checkoutAt?: Date | null;
  /**
   *
   * @type {string}
   * @memberof ActivityParticipation
   */
  signStatus?: string | null;
  /**
   *
   * @type {string}
   * @memberof ActivityParticipation
   */
  remark?: string | null;
}

/**
 * Check if a given object implements the ActivityParticipation interface.
 */
export function instanceOfActivityParticipation(value: object): value is ActivityParticipation {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("activityId" in value) || value["activityId"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("userName" in value) || value["userName"] === undefined) return false;
  return true;
}

export function ActivityParticipationFromJSON(json: any): ActivityParticipation {
  return ActivityParticipationFromJSONTyped(json, false);
}

export function ActivityParticipationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActivityParticipation {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    activityId: json["activityId"],
    userId: json["userId"],
    userName: json["userName"],
    studentNo:
      json["studentNo"] === undefined
        ? undefined
        : json["studentNo"] === null
          ? null
          : json["studentNo"],
    registerStatus:
      json["registerStatus"] === undefined
        ? undefined
        : json["registerStatus"] === null
          ? null
          : json["registerStatus"],
    registeredAt:
      json["registeredAt"] === undefined
        ? undefined
        : json["registeredAt"] === null
          ? null
          : new Date(json["registeredAt"]),
    checkinAt:
      json["checkinAt"] === undefined
        ? undefined
        : json["checkinAt"] === null
          ? null
          : new Date(json["checkinAt"]),
    checkoutAt:
      json["checkoutAt"] === undefined
        ? undefined
        : json["checkoutAt"] === null
          ? null
          : new Date(json["checkoutAt"]),
    signStatus:
      json["signStatus"] === undefined
        ? undefined
        : json["signStatus"] === null
          ? null
          : json["signStatus"],
    remark:
      json["remark"] === undefined ? undefined : json["remark"] === null ? null : json["remark"],
  };
}

export function ActivityParticipationToJSON(json: any): ActivityParticipation {
  return ActivityParticipationToJSONTyped(json, false);
}

export function ActivityParticipationToJSONTyped(
  value?: ActivityParticipation | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    activityId: value["activityId"],
    userId: value["userId"],
    userName: value["userName"],
    studentNo: value["studentNo"],
    registerStatus: value["registerStatus"],
    registeredAt:
      value["registeredAt"] == null ? value["registeredAt"] : value["registeredAt"].toISOString(),
    checkinAt: value["checkinAt"] == null ? value["checkinAt"] : value["checkinAt"].toISOString(),
    checkoutAt:
      value["checkoutAt"] == null ? value["checkoutAt"] : value["checkoutAt"].toISOString(),
    signStatus: value["signStatus"],
    remark: value["remark"],
  };
}
