// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 添加或恢复项目成员的请求；负责人角色只能通过项目负责人分配流程维护。
 * @export
 * @interface AddProjectMemberRequest
 */
export interface AddProjectMemberRequest {
  /**
   * 所属社团 active 成员的用户 ID。
   * @type {number}
   * @memberof AddProjectMemberRequest
   */
  userId: number;
  /**
   * 新成员的项目内角色。
   * @type {AddProjectMemberRequestMemberRoleEnum}
   * @memberof AddProjectMemberRequest
   */
  memberRole: AddProjectMemberRequestMemberRoleEnum;
  /**
   * 可选备注。
   * @type {string}
   * @memberof AddProjectMemberRequest
   */
  remark?: string | null;
}

/**
 * @export
 */
export const AddProjectMemberRequestMemberRoleEnum = {
  Member: "member",
  Mentor: "mentor",
} as const;
export type AddProjectMemberRequestMemberRoleEnum =
  (typeof AddProjectMemberRequestMemberRoleEnum)[keyof typeof AddProjectMemberRequestMemberRoleEnum];

/**
 * Check if a given object implements the AddProjectMemberRequest interface.
 */
export function instanceOfAddProjectMemberRequest(value: object): value is AddProjectMemberRequest {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("memberRole" in value) || value["memberRole"] === undefined) return false;
  return true;
}

export function AddProjectMemberRequestFromJSON(json: any): AddProjectMemberRequest {
  return AddProjectMemberRequestFromJSONTyped(json, false);
}

export function AddProjectMemberRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddProjectMemberRequest {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"],
    memberRole: json["memberRole"],
    remark: json["remark"] == null ? undefined : json["remark"],
  };
}

export function AddProjectMemberRequestToJSON(json: any): AddProjectMemberRequest {
  return AddProjectMemberRequestToJSONTyped(json, false);
}

export function AddProjectMemberRequestToJSONTyped(
  value?: AddProjectMemberRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    memberRole: value["memberRole"],
    remark: value["remark"],
  };
}
