// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 涓虹洰鏍囩敤鎴峰垎閰嶇郴缁熺骇鎴栫ぞ鍥㈢骇瑙掕壊銆? * @export
 * @interface AssignRoleRequest
 */
export interface AssignRoleRequest {
  /**
   * 鍙戣捣鍒嗛厤鎿嶄綔鐨勭敤鎴?ID銆?     * @type {number}
   * @memberof AssignRoleRequest
   */
  operatorUserId: number;
  /**
   * 琚垎閰嶈鑹茬殑鐢ㄦ埛 ID銆?     * @type {number}
   * @memberof AssignRoleRequest
   */
  targetUserId: number;
  /**
   * 瑙掕壊缂栫爜锛屼緥濡?STUDENT銆丆LUB_MEMBER銆丼YSTEM_ADMIN銆?     * @type {string}
   * @memberof AssignRoleRequest
   */
  roleCode: string;
  /**
   * 绀惧洟绾ц鑹叉墍灞炵ぞ鍥?ID锛涚郴缁熺骇瑙掕壊鍙负绌恒€?     * @type {number}
   * @memberof AssignRoleRequest
   */
  clubId?: number | null;
}

/**
 * Check if a given object implements the AssignRoleRequest interface.
 */
export function instanceOfAssignRoleRequest(value: object): value is AssignRoleRequest {
  if (!("operatorUserId" in value) || value["operatorUserId"] === undefined) return false;
  if (!("targetUserId" in value) || value["targetUserId"] === undefined) return false;
  if (!("roleCode" in value) || value["roleCode"] === undefined) return false;
  return true;
}

export function AssignRoleRequestFromJSON(json: any): AssignRoleRequest {
  return AssignRoleRequestFromJSONTyped(json, false);
}

export function AssignRoleRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssignRoleRequest {
  if (json == null) {
    return json;
  }
  return {
    operatorUserId: json["operatorUserId"],
    targetUserId: json["targetUserId"],
    roleCode: json["roleCode"],
    clubId: json["clubId"] == null ? undefined : json["clubId"],
  };
}

export function AssignRoleRequestToJSON(json: any): AssignRoleRequest {
  return AssignRoleRequestToJSONTyped(json, false);
}

export function AssignRoleRequestToJSONTyped(
  value?: AssignRoleRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    operatorUserId: value["operatorUserId"],
    targetUserId: value["targetUserId"],
    roleCode: value["roleCode"],
    clubId: value["clubId"],
  };
}
