// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 为目标用户分配系统级或社团级角色。
 * @export
 * @interface AssignRoleRequest
 */
export interface AssignRoleRequest {
    /**
     * 发起分配操作的用户 ID。
     * @type {number}
     * @memberof AssignRoleRequest
     */
    operatorUserId: number;
    /**
     * 被分配角色的用户 ID。
     * @type {number}
     * @memberof AssignRoleRequest
     */
    targetUserId: number;
    /**
     * 角色编码，例如 STUDENT、CLUB_MEMBER、SYSTEM_ADMIN。
     * @type {string}
     * @memberof AssignRoleRequest
     */
    roleCode: string;
    /**
     * 社团级角色所属社团 ID；系统级角色可为空。
     * @type {number}
     * @memberof AssignRoleRequest
     */
    clubId?: number | null;
}

/**
 * Check if a given object implements the AssignRoleRequest interface.
 */
export function instanceOfAssignRoleRequest(value: object): value is AssignRoleRequest {
    if (!('operatorUserId' in value) || value['operatorUserId'] === undefined) return false;
    if (!('targetUserId' in value) || value['targetUserId'] === undefined) return false;
    if (!('roleCode' in value) || value['roleCode'] === undefined) return false;
    return true;
}

export function AssignRoleRequestFromJSON(json: any): AssignRoleRequest {
    return AssignRoleRequestFromJSONTyped(json, false);
}

export function AssignRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'operatorUserId': json['operatorUserId'],
        'targetUserId': json['targetUserId'],
        'roleCode': json['roleCode'],
        'clubId': json['clubId'] == null ? undefined : json['clubId'],
    };
}

export function AssignRoleRequestToJSON(json: any): AssignRoleRequest {
    return AssignRoleRequestToJSONTyped(json, false);
}

export function AssignRoleRequestToJSONTyped(value?: AssignRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operatorUserId': value['operatorUserId'],
        'targetUserId': value['targetUserId'],
        'roleCode': value['roleCode'],
        'clubId': value['clubId'],
    };
}


