// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 璁よ瘉涓婁笅鏂囦腑鐨勭敤鎴峰熀纭€淇℃伅銆? * @export
 * @interface AuthUser
 */
export interface AuthUser {
  /**
   * 鐢ㄦ埛 ID銆?     * @type {number}
   * @memberof AuthUser
   */
  id: number;
  /**
   * 鐧诲綍鐢ㄦ埛鍚嶃€?     * @type {string}
   * @memberof AuthUser
   */
  username: string;
  /**
   * 鐢ㄦ埛鐪熷疄濮撳悕銆?     * @type {string}
   * @memberof AuthUser
   */
  realName: string;
  /**
   * 瀛﹀伐鍙凤紱瀛︾敓 7 浣嶏紝鏁欏笀 5 浣嶃€?     * @type {string}
   * @memberof AuthUser
   */
  studentNo?: string | null;
  /**
   * 鎬у埆銆?     * @type {string}
   * @memberof AuthUser
   */
  gender?: string | null;
  /**
   * 鑱旂郴鐢佃瘽銆?     * @type {string}
   * @memberof AuthUser
   */
  phone?: string | null;
  /**
   * 閭鍦板潃銆?     * @type {string}
   * @memberof AuthUser
   */
  email?: string | null;
  /**
   * 鎵€灞炲闄€?     * @type {string}
   * @memberof AuthUser
   */
  college?: string | null;
  /**
   * 鎵€灞炰笓涓氥€?     * @type {string}
   * @memberof AuthUser
   */
  major?: string | null;
  /**
   * 骞寸骇銆?     * @type {string}
   * @memberof AuthUser
   */
  grade?: string | null;
  /**
   * 璐﹀彿鐘舵€侊紝渚嬪 normal 鎴?disabled銆?     * @type {string}
   * @memberof AuthUser
   */
  accountStatus: string;
}

/**
 * Check if a given object implements the AuthUser interface.
 */
export function instanceOfAuthUser(value: object): value is AuthUser {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("username" in value) || value["username"] === undefined) return false;
  if (!("realName" in value) || value["realName"] === undefined) return false;
  if (!("accountStatus" in value) || value["accountStatus"] === undefined) return false;
  return true;
}

export function AuthUserFromJSON(json: any): AuthUser {
  return AuthUserFromJSONTyped(json, false);
}

export function AuthUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUser {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    username: json["username"],
    realName: json["realName"],
    studentNo: json["studentNo"] == null ? undefined : json["studentNo"],
    gender: json["gender"] == null ? undefined : json["gender"],
    phone: json["phone"] == null ? undefined : json["phone"],
    email: json["email"] == null ? undefined : json["email"],
    college: json["college"] == null ? undefined : json["college"],
    major: json["major"] == null ? undefined : json["major"],
    grade: json["grade"] == null ? undefined : json["grade"],
    accountStatus: json["accountStatus"],
  };
}

export function AuthUserToJSON(json: any): AuthUser {
  return AuthUserToJSONTyped(json, false);
}

export function AuthUserToJSONTyped(
  value?: AuthUser | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    username: value["username"],
    realName: value["realName"],
    studentNo: value["studentNo"],
    gender: value["gender"],
    phone: value["phone"],
    email: value["email"],
    college: value["college"],
    major: value["major"],
    grade: value["grade"],
    accountStatus: value["accountStatus"],
  };
}
