// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 评奖评优申请审批记录。
 * @export
 * @interface AwardReviewRecord
 */
export interface AwardReviewRecord {
  /**
   * 审批记录 ID。
   * @type {number}
   * @memberof AwardReviewRecord
   */
  reviewId: number;
  /**
   * 所属评奖评优申请 ID。
   * @type {number}
   * @memberof AwardReviewRecord
   */
  awardApplicationId: number;
  /**
   * 审批轮次；退回后重新提交会进入新轮次。
   * @type {number}
   * @memberof AwardReviewRecord
   */
  reviewRound: number;
  /**
   * 本次审批所在节点。
   * @type {AwardReviewRecordReviewStepEnum}
   * @memberof AwardReviewRecord
   */
  reviewStep: AwardReviewRecordReviewStepEnum;
  /**
   * 审批动作或系统流转动作。
   * @type {AwardReviewRecordReviewResultEnum}
   * @memberof AwardReviewRecord
   */
  reviewResult: AwardReviewRecordReviewResultEnum;
  /**
   * 审批人用户 ID；系统生成记录可为空。
   * @type {number}
   * @memberof AwardReviewRecord
   */
  reviewerUserId?: number | null;
  /**
   * 审批人展示名。
   * @type {string}
   * @memberof AwardReviewRecord
   */
  reviewerName?: string | null;
  /**
   * 审批意见。
   * @type {string}
   * @memberof AwardReviewRecord
   */
  reviewComment?: string | null;
  /**
   * 审批前申请状态。
   * @type {string}
   * @memberof AwardReviewRecord
   */
  fromStatus?: string | null;
  /**
   * 审批后申请状态。
   * @type {string}
   * @memberof AwardReviewRecord
   */
  toStatus?: string | null;
  /**
   * 审批记录生成时间。
   * @type {Date}
   * @memberof AwardReviewRecord
   */
  reviewedAt: Date;
}

/**
 * @export
 */
export const AwardReviewRecordReviewStepEnum = {
  StudentSubmit: "student_submit",
  ClubReview: "club_review",
  AdvisorReview: "advisor_review",
  SchoolReview: "school_review",
  Publicity: "publicity",
  Archive: "archive",
} as const;
export type AwardReviewRecordReviewStepEnum =
  (typeof AwardReviewRecordReviewStepEnum)[keyof typeof AwardReviewRecordReviewStepEnum];

/**
 * @export
 */
export const AwardReviewRecordReviewResultEnum = {
  Submit: "submit",
  Approve: "approve",
  Reject: "reject",
  Return: "return",
  Publish: "publish",
  Archive: "archive",
  Withdraw: "withdraw",
} as const;
export type AwardReviewRecordReviewResultEnum =
  (typeof AwardReviewRecordReviewResultEnum)[keyof typeof AwardReviewRecordReviewResultEnum];

/**
 * Check if a given object implements the AwardReviewRecord interface.
 */
export function instanceOfAwardReviewRecord(value: object): value is AwardReviewRecord {
  if (!("reviewId" in value) || value["reviewId"] === undefined) return false;
  if (!("awardApplicationId" in value) || value["awardApplicationId"] === undefined) return false;
  if (!("reviewRound" in value) || value["reviewRound"] === undefined) return false;
  if (!("reviewStep" in value) || value["reviewStep"] === undefined) return false;
  if (!("reviewResult" in value) || value["reviewResult"] === undefined) return false;
  if (!("reviewedAt" in value) || value["reviewedAt"] === undefined) return false;
  return true;
}

export function AwardReviewRecordFromJSON(json: any): AwardReviewRecord {
  return AwardReviewRecordFromJSONTyped(json, false);
}

export function AwardReviewRecordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AwardReviewRecord {
  if (json == null) {
    return json;
  }
  return {
    reviewId: json["reviewId"],
    awardApplicationId: json["awardApplicationId"],
    reviewRound: json["reviewRound"],
    reviewStep: json["reviewStep"],
    reviewResult: json["reviewResult"],
    reviewerUserId: json["reviewerUserId"] == null ? undefined : json["reviewerUserId"],
    reviewerName: json["reviewerName"] == null ? undefined : json["reviewerName"],
    reviewComment: json["reviewComment"] == null ? undefined : json["reviewComment"],
    fromStatus: json["fromStatus"] == null ? undefined : json["fromStatus"],
    toStatus: json["toStatus"] == null ? undefined : json["toStatus"],
    reviewedAt: new Date(json["reviewedAt"]),
  };
}

export function AwardReviewRecordToJSON(json: any): AwardReviewRecord {
  return AwardReviewRecordToJSONTyped(json, false);
}

export function AwardReviewRecordToJSONTyped(
  value?: AwardReviewRecord | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    reviewId: value["reviewId"],
    awardApplicationId: value["awardApplicationId"],
    reviewRound: value["reviewRound"],
    reviewStep: value["reviewStep"],
    reviewResult: value["reviewResult"],
    reviewerUserId: value["reviewerUserId"],
    reviewerName: value["reviewerName"],
    reviewComment: value["reviewComment"],
    fromStatus: value["fromStatus"],
    toStatus: value["toStatus"],
    reviewedAt: value["reviewedAt"].toISOString(),
  };
}
