// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 评奖评优申请材料附件。
 * @export
 * @interface AwardAttachmentRecord
 */
export interface AwardAttachmentRecord {
  /**
   * 附件记录 ID。
   * @type {number}
   * @memberof AwardAttachmentRecord
   */
  attachmentId: number;
  /**
   * 所属评奖评优申请 ID。
   * @type {number}
   * @memberof AwardAttachmentRecord
   */
  awardApplicationId: number;
  /**
   * 附件展示名称。
   * @type {string}
   * @memberof AwardAttachmentRecord
   */
  attachmentName: string;
  /**
   * 申请材料的内部文件引用；客户端下载文件应调用申请材料下载接口。
   * @type {string}
   * @memberof AwardAttachmentRecord
   */
  attachmentUrl: string;
  /**
   * 附件类型或材料分类。
   * @type {string}
   * @memberof AwardAttachmentRecord
   */
  attachmentType?: string | null;
  /**
   * 上传人用户 ID。
   * @type {number}
   * @memberof AwardAttachmentRecord
   */
  uploadedByUserId: number;
  /**
   * 上传人展示名。
   * @type {string}
   * @memberof AwardAttachmentRecord
   */
  uploadedByName?: string | null;
  /**
   * 上传时间。
   * @type {Date}
   * @memberof AwardAttachmentRecord
   */
  uploadedAt: Date;
}

/**
 * Check if a given object implements the AwardAttachmentRecord interface.
 */
export function instanceOfAwardAttachmentRecord(value: object): value is AwardAttachmentRecord {
  if (!("attachmentId" in value) || value["attachmentId"] === undefined) return false;
  if (!("awardApplicationId" in value) || value["awardApplicationId"] === undefined) return false;
  if (!("attachmentName" in value) || value["attachmentName"] === undefined) return false;
  if (!("attachmentUrl" in value) || value["attachmentUrl"] === undefined) return false;
  if (!("uploadedByUserId" in value) || value["uploadedByUserId"] === undefined) return false;
  if (!("uploadedAt" in value) || value["uploadedAt"] === undefined) return false;
  return true;
}

export function AwardAttachmentRecordFromJSON(json: any): AwardAttachmentRecord {
  return AwardAttachmentRecordFromJSONTyped(json, false);
}

export function AwardAttachmentRecordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AwardAttachmentRecord {
  if (json == null) {
    return json;
  }
  return {
    attachmentId: json["attachmentId"],
    awardApplicationId: json["awardApplicationId"],
    attachmentName: json["attachmentName"],
    attachmentUrl: json["attachmentUrl"],
    attachmentType:
      json["attachmentType"] === undefined
        ? undefined
        : json["attachmentType"] === null
          ? null
          : json["attachmentType"],
    uploadedByUserId: json["uploadedByUserId"],
    uploadedByName:
      json["uploadedByName"] === undefined
        ? undefined
        : json["uploadedByName"] === null
          ? null
          : json["uploadedByName"],
    uploadedAt: new Date(json["uploadedAt"]),
  };
}

export function AwardAttachmentRecordToJSON(json: any): AwardAttachmentRecord {
  return AwardAttachmentRecordToJSONTyped(json, false);
}

export function AwardAttachmentRecordToJSONTyped(
  value?: AwardAttachmentRecord | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    attachmentId: value["attachmentId"],
    awardApplicationId: value["awardApplicationId"],
    attachmentName: value["attachmentName"],
    attachmentUrl: value["attachmentUrl"],
    attachmentType: value["attachmentType"],
    uploadedByUserId: value["uploadedByUserId"],
    uploadedByName: value["uploadedByName"],
    uploadedAt: value["uploadedAt"].toISOString(),
  };
}
