// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AwardLevelRecord } from "./AwardLevelRecord";
import {
  AwardLevelRecordFromJSON,
  AwardLevelRecordFromJSONTyped,
  AwardLevelRecordToJSON,
  AwardLevelRecordToJSONTyped,
} from "./AwardLevelRecord";

/**
 * 社团评奖评优奖项配置，对应学校奖学金系统里的奖种详情，但按社团维度管理。
 * @export
 * @interface AwardSchemeRecord
 */
export interface AwardSchemeRecord {
  /**
   *
   * @type {number}
   * @memberof AwardSchemeRecord
   */
  awardSchemeId: number;
  /**
   *
   * @type {number}
   * @memberof AwardSchemeRecord
   */
  clubId: number;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  clubName: string;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  awardName: string;
  /**
   *
   * @type {AwardSchemeRecordAwardCategoryEnum}
   * @memberof AwardSchemeRecord
   */
  awardCategory: AwardSchemeRecordAwardCategoryEnum;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  academicYear: string;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  termName?: string | null;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  sponsorUnit?: string | null;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  rewardLevel?: string | null;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  fundingSource?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof AwardSchemeRecord
   */
  isRanked: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AwardSchemeRecord
   */
  isFixedAmount: boolean;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  materialDescription?: string | null;
  /**
   *
   * @type {Date}
   * @memberof AwardSchemeRecord
   */
  applicationStartAt?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof AwardSchemeRecord
   */
  applicationEndAt?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof AwardSchemeRecord
   */
  publicityStartAt?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof AwardSchemeRecord
   */
  publicityEndAt?: Date | null;
  /**
   *
   * @type {AwardSchemeRecordSchemeStatusEnum}
   * @memberof AwardSchemeRecord
   */
  schemeStatus: AwardSchemeRecordSchemeStatusEnum;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  schemeStatusText: string;
  /**
   *
   * @type {number}
   * @memberof AwardSchemeRecord
   */
  createdByUserId?: number | null;
  /**
   *
   * @type {string}
   * @memberof AwardSchemeRecord
   */
  createdByName?: string | null;
  /**
   *
   * @type {Date}
   * @memberof AwardSchemeRecord
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof AwardSchemeRecord
   */
  updatedAt: Date;
  /**
   *
   * @type {Array<AwardLevelRecord>}
   * @memberof AwardSchemeRecord
   */
  levels: Array<AwardLevelRecord>;
}

/**
 * @export
 */
export const AwardSchemeRecordAwardCategoryEnum = {
  Honor: "honor",
  Scholarship: "scholarship",
  Competition: "competition",
  Service: "service",
  Other: "other",
} as const;
export type AwardSchemeRecordAwardCategoryEnum =
  (typeof AwardSchemeRecordAwardCategoryEnum)[keyof typeof AwardSchemeRecordAwardCategoryEnum];

/**
 * @export
 */
export const AwardSchemeRecordSchemeStatusEnum = {
  Draft: "draft",
  Open: "open",
  Reviewing: "reviewing",
  Publicizing: "publicizing",
  Archived: "archived",
  Closed: "closed",
} as const;
export type AwardSchemeRecordSchemeStatusEnum =
  (typeof AwardSchemeRecordSchemeStatusEnum)[keyof typeof AwardSchemeRecordSchemeStatusEnum];

/**
 * Check if a given object implements the AwardSchemeRecord interface.
 */
export function instanceOfAwardSchemeRecord(value: object): value is AwardSchemeRecord {
  if (!("awardSchemeId" in value) || value["awardSchemeId"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("clubName" in value) || value["clubName"] === undefined) return false;
  if (!("awardName" in value) || value["awardName"] === undefined) return false;
  if (!("awardCategory" in value) || value["awardCategory"] === undefined) return false;
  if (!("academicYear" in value) || value["academicYear"] === undefined) return false;
  if (!("isRanked" in value) || value["isRanked"] === undefined) return false;
  if (!("isFixedAmount" in value) || value["isFixedAmount"] === undefined) return false;
  if (!("schemeStatus" in value) || value["schemeStatus"] === undefined) return false;
  if (!("schemeStatusText" in value) || value["schemeStatusText"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("levels" in value) || value["levels"] === undefined) return false;
  return true;
}

export function AwardSchemeRecordFromJSON(json: any): AwardSchemeRecord {
  return AwardSchemeRecordFromJSONTyped(json, false);
}

export function AwardSchemeRecordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AwardSchemeRecord {
  if (json == null) {
    return json;
  }
  return {
    awardSchemeId: json["awardSchemeId"],
    clubId: json["clubId"],
    clubName: json["clubName"],
    awardName: json["awardName"],
    awardCategory: json["awardCategory"],
    academicYear: json["academicYear"],
    termName: json["termName"] == null ? undefined : json["termName"],
    sponsorUnit: json["sponsorUnit"] == null ? undefined : json["sponsorUnit"],
    rewardLevel: json["rewardLevel"] == null ? undefined : json["rewardLevel"],
    fundingSource: json["fundingSource"] == null ? undefined : json["fundingSource"],
    isRanked: json["isRanked"],
    isFixedAmount: json["isFixedAmount"],
    description: json["description"] == null ? undefined : json["description"],
    materialDescription:
      json["materialDescription"] == null ? undefined : json["materialDescription"],
    applicationStartAt:
      json["applicationStartAt"] == null ? undefined : new Date(json["applicationStartAt"]),
    applicationEndAt:
      json["applicationEndAt"] == null ? undefined : new Date(json["applicationEndAt"]),
    publicityStartAt:
      json["publicityStartAt"] == null ? undefined : new Date(json["publicityStartAt"]),
    publicityEndAt: json["publicityEndAt"] == null ? undefined : new Date(json["publicityEndAt"]),
    schemeStatus: json["schemeStatus"],
    schemeStatusText: json["schemeStatusText"],
    createdByUserId: json["createdByUserId"] == null ? undefined : json["createdByUserId"],
    createdByName: json["createdByName"] == null ? undefined : json["createdByName"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
    levels: (json["levels"] as Array<any>).map(AwardLevelRecordFromJSON),
  };
}

export function AwardSchemeRecordToJSON(json: any): AwardSchemeRecord {
  return AwardSchemeRecordToJSONTyped(json, false);
}

export function AwardSchemeRecordToJSONTyped(
  value?: AwardSchemeRecord | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    awardSchemeId: value["awardSchemeId"],
    clubId: value["clubId"],
    clubName: value["clubName"],
    awardName: value["awardName"],
    awardCategory: value["awardCategory"],
    academicYear: value["academicYear"],
    termName: value["termName"],
    sponsorUnit: value["sponsorUnit"],
    rewardLevel: value["rewardLevel"],
    fundingSource: value["fundingSource"],
    isRanked: value["isRanked"],
    isFixedAmount: value["isFixedAmount"],
    description: value["description"],
    materialDescription: value["materialDescription"],
    applicationStartAt:
      value["applicationStartAt"] == null
        ? value["applicationStartAt"]
        : value["applicationStartAt"].toISOString(),
    applicationEndAt:
      value["applicationEndAt"] == null
        ? value["applicationEndAt"]
        : value["applicationEndAt"].toISOString(),
    publicityStartAt:
      value["publicityStartAt"] == null
        ? value["publicityStartAt"]
        : value["publicityStartAt"].toISOString(),
    publicityEndAt:
      value["publicityEndAt"] == null
        ? value["publicityEndAt"]
        : value["publicityEndAt"].toISOString(),
    schemeStatus: value["schemeStatus"],
    schemeStatusText: value["schemeStatusText"],
    createdByUserId: value["createdByUserId"],
    createdByName: value["createdByName"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
    levels: (value["levels"] as Array<any>).map(AwardLevelRecordToJSON),
  };
}
