// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BorrowMaterialRequest
 */
export interface BorrowMaterialRequest {
  /**
   *
   * @type {number}
   * @memberof BorrowMaterialRequest
   */
  materialId: number;
  /**
   *
   * @type {number}
   * @memberof BorrowMaterialRequest
   */
  clubId: number;
  /**
   *
   * @type {number}
   * @memberof BorrowMaterialRequest
   */
  quantity: number;
  /**
   *
   * @type {Date}
   * @memberof BorrowMaterialRequest
   */
  expectedReturnAt: Date;
}

/**
 * Check if a given object implements the BorrowMaterialRequest interface.
 */
export function instanceOfBorrowMaterialRequest(value: object): value is BorrowMaterialRequest {
  if (!("materialId" in value) || value["materialId"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("quantity" in value) || value["quantity"] === undefined) return false;
  if (!("expectedReturnAt" in value) || value["expectedReturnAt"] === undefined) return false;
  return true;
}

export function BorrowMaterialRequestFromJSON(json: any): BorrowMaterialRequest {
  return BorrowMaterialRequestFromJSONTyped(json, false);
}

export function BorrowMaterialRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BorrowMaterialRequest {
  if (json == null) {
    return json;
  }
  return {
    materialId: json["materialId"],
    clubId: json["clubId"],
    quantity: json["quantity"],
    expectedReturnAt: new Date(json["expectedReturnAt"]),
  };
}

export function BorrowMaterialRequestToJSON(json: any): BorrowMaterialRequest {
  return BorrowMaterialRequestToJSONTyped(json, false);
}

export function BorrowMaterialRequestToJSONTyped(
  value?: BorrowMaterialRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    materialId: value["materialId"],
    clubId: value["clubId"],
    quantity: value["quantity"],
    expectedReturnAt: value["expectedReturnAt"].toISOString(),
  };
}
