// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 经费申请类型。
 * @export
 */
export const BudgetApplicationType = {
  ActivityBudget: "activity_budget",
  Purchase: "purchase",
  Reimbursement: "reimbursement",
} as const;
export type BudgetApplicationType =
  (typeof BudgetApplicationType)[keyof typeof BudgetApplicationType];

export function instanceOfBudgetApplicationType(value: any): boolean {
  for (const key in BudgetApplicationType) {
    if (Object.prototype.hasOwnProperty.call(BudgetApplicationType, key)) {
      if (BudgetApplicationType[key as keyof typeof BudgetApplicationType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function BudgetApplicationTypeFromJSON(json: any): BudgetApplicationType {
  return BudgetApplicationTypeFromJSONTyped(json, false);
}

export function BudgetApplicationTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BudgetApplicationType {
  return json as BudgetApplicationType;
}

export function BudgetApplicationTypeToJSON(value?: BudgetApplicationType | null): any {
  return value as any;
}

export function BudgetApplicationTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): BudgetApplicationType {
  return value as BudgetApplicationType;
}
