// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 经费流水记录，余额由经费账户初始额度和流水金额汇总得到。
 * @export
 * @interface BudgetTransaction
 */
export interface BudgetTransaction {
  /**
   * 经费流水 ID。
   * @type {number}
   * @memberof BudgetTransaction
   */
  id: number;
  /**
   * 关联经费账户 ID。
   * @type {number}
   * @memberof BudgetTransaction
   */
  accountId: number;
  /**
   * 关联经费申请 ID；手工调整类流水可为空。
   * @type {number}
   * @memberof BudgetTransaction
   */
  applicationId?: number | null;
  /**
   * 流水所属社团 ID。
   * @type {number}
   * @memberof BudgetTransaction
   */
  clubId: number;
  /**
   * 流水所属社团名称。
   * @type {string}
   * @memberof BudgetTransaction
   */
  clubName: string;
  /**
   * 流水类型；commitment 审批占用，expense 实际支出，refund 退款，adjustment 调整。
   * @type {BudgetTransactionTypeEnum}
   * @memberof BudgetTransaction
   */
  type: BudgetTransactionTypeEnum;
  /**
   * 流水金额，支出或占用为负数，退款或调增为正数。
   * @type {number}
   * @memberof BudgetTransaction
   */
  amount: number;
  /**
   * 流水说明。
   * @type {string}
   * @memberof BudgetTransaction
   */
  description?: string | null;
  /**
   * 流水发生时间。
   * @type {Date}
   * @memberof BudgetTransaction
   */
  occurredAt: Date;
  /**
   * 流水创建时间。
   * @type {Date}
   * @memberof BudgetTransaction
   */
  createdAt: Date;
}

/**
 * @export
 */
export const BudgetTransactionTypeEnum = {
  Commitment: "commitment",
  Expense: "expense",
  Refund: "refund",
  Adjustment: "adjustment",
} as const;
export type BudgetTransactionTypeEnum =
  (typeof BudgetTransactionTypeEnum)[keyof typeof BudgetTransactionTypeEnum];

/**
 * Check if a given object implements the BudgetTransaction interface.
 */
export function instanceOfBudgetTransaction(value: object): value is BudgetTransaction {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("accountId" in value) || value["accountId"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("clubName" in value) || value["clubName"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("amount" in value) || value["amount"] === undefined) return false;
  if (!("occurredAt" in value) || value["occurredAt"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function BudgetTransactionFromJSON(json: any): BudgetTransaction {
  return BudgetTransactionFromJSONTyped(json, false);
}

export function BudgetTransactionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BudgetTransaction {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    accountId: json["accountId"],
    applicationId:
      json["applicationId"] === undefined
        ? undefined
        : json["applicationId"] === null
          ? null
          : json["applicationId"],
    clubId: json["clubId"],
    clubName: json["clubName"],
    type: json["type"],
    amount: json["amount"],
    description:
      json["description"] === undefined
        ? undefined
        : json["description"] === null
          ? null
          : json["description"],
    occurredAt: new Date(json["occurredAt"]),
    createdAt: new Date(json["createdAt"]),
  };
}

export function BudgetTransactionToJSON(json: any): BudgetTransaction {
  return BudgetTransactionToJSONTyped(json, false);
}

export function BudgetTransactionToJSONTyped(
  value?: BudgetTransaction | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    accountId: value["accountId"],
    applicationId: value["applicationId"],
    clubId: value["clubId"],
    clubName: value["clubName"],
    type: value["type"],
    amount: value["amount"],
    description: value["description"],
    occurredAt: value["occurredAt"].toISOString(),
    createdAt: value["createdAt"].toISOString(),
  };
}
