// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Request body for canceling a pending or running project.
 * @export
 * @interface CancelProjectRequest
 */
export interface CancelProjectRequest {
  /**
   * 当前撤销操作用户 ID；系统管理员可撤销待审核/进行中项目，本社团负责人可撤销待审核申请，校级社团管理员可撤销进行中项目。
   * @type {number}
   * @memberof CancelProjectRequest
   */
  currentUserId: number;
  /**
   * Optional applicant cancellation reason.
   * @type {string}
   * @memberof CancelProjectRequest
   */
  cancelReason?: string | null;
}

/**
 * Check if a given object implements the CancelProjectRequest interface.
 */
export function instanceOfCancelProjectRequest(value: object): value is CancelProjectRequest {
  if (!("currentUserId" in value) || value["currentUserId"] === undefined) return false;
  return true;
}

export function CancelProjectRequestFromJSON(json: any): CancelProjectRequest {
  return CancelProjectRequestFromJSONTyped(json, false);
}

export function CancelProjectRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CancelProjectRequest {
  if (json == null) {
    return json;
  }
  return {
    currentUserId: json["currentUserId"],
    cancelReason: json["cancelReason"] == null ? undefined : json["cancelReason"],
  };
}

export function CancelProjectRequestToJSON(json: any): CancelProjectRequest {
  return CancelProjectRequestToJSONTyped(json, false);
}

export function CancelProjectRequestToJSONTyped(
  value?: CancelProjectRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentUserId: value["currentUserId"],
    cancelReason: value["cancelReason"],
  };
}
