// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from "../runtime";
/**
 *
 * @export
 * @interface ClubMemberRecord
 */
export interface ClubMemberRecord {
  /**
   *
   */
  memberId: number;
  /**
   *
   */
  clubId: number;
  /**
   *
   */
  clubName: string;
  /**
   *
   */
  userId: number;
  /**
   *
   */
  userName: string;
  /**
   *
   */
  studentNo?: string | null;
  /**
   * 成员当前归属部门 ID；为空表示未归属部门。
   */
  departmentId?: number | null;
  /**
   *
   */
  departmentName?: string | null;
  /**
   * 成员当前归属小组 ID；为空表示未归属小组。
   */
  groupId?: number | null;
  /**
   *
   */
  groupName?: string | null;
  /**
   *
   */
  positionName?: string | null;
  /**
   *
   */
  termName?: string | null;
  /**
   *
   */
  termStart?: Date | null;
  /**
   *
   */
  termEnd?: Date | null;
  /**
   *
   */
  memberStatus?: string | null;
  /**
   *
   */
  joinAt?: Date | null;
  /**
   *
   */
  contributionScore?: number | null;
  /**
   *
   */
  isCurrent: boolean;
}

/**
 * Check if a given object implements the ClubMemberRecord interface.
 */
export function instanceOfClubMemberRecord(value: object): value is ClubMemberRecord {
  if (!("memberId" in value) || value["memberId"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("clubName" in value) || value["clubName"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("userName" in value) || value["userName"] === undefined) return false;
  if (!("isCurrent" in value) || value["isCurrent"] === undefined) return false;
  return true;
}

export function ClubMemberRecordFromJSON(json: any): ClubMemberRecord {
  return ClubMemberRecordFromJSONTyped(json, false);
}

export function ClubMemberRecordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClubMemberRecord {
  if (json == null) {
    return json;
  }
  return {
    memberId: json["memberId"],
    clubId: json["clubId"],
    clubName: json["clubName"],
    userId: json["userId"],
    userName: json["userName"],
    studentNo:
      json["studentNo"] === undefined
        ? undefined
        : json["studentNo"] === null
          ? null
          : json["studentNo"],
    departmentId:
      json["departmentId"] === undefined
        ? undefined
        : json["departmentId"] === null
          ? null
          : json["departmentId"],
    departmentName:
      json["departmentName"] === undefined
        ? undefined
        : json["departmentName"] === null
          ? null
          : json["departmentName"],
    groupId:
      json["groupId"] === undefined ? undefined : json["groupId"] === null ? null : json["groupId"],
    groupName:
      json["groupName"] === undefined
        ? undefined
        : json["groupName"] === null
          ? null
          : json["groupName"],
    positionName:
      json["positionName"] === undefined
        ? undefined
        : json["positionName"] === null
          ? null
          : json["positionName"],
    termName:
      json["termName"] === undefined
        ? undefined
        : json["termName"] === null
          ? null
          : json["termName"],
    termStart:
      json["termStart"] === undefined
        ? undefined
        : json["termStart"] === null
          ? null
          : parseDateTime(json["termStart"]),
    termEnd:
      json["termEnd"] === undefined
        ? undefined
        : json["termEnd"] === null
          ? null
          : parseDateTime(json["termEnd"]),
    memberStatus:
      json["memberStatus"] === undefined
        ? undefined
        : json["memberStatus"] === null
          ? null
          : json["memberStatus"],
    joinAt:
      json["joinAt"] === undefined
        ? undefined
        : json["joinAt"] === null
          ? null
          : parseDateTime(json["joinAt"]),
    contributionScore:
      json["contributionScore"] === undefined
        ? undefined
        : json["contributionScore"] === null
          ? null
          : json["contributionScore"],
    isCurrent: json["isCurrent"],
  };
}

export function ClubMemberRecordToJSON(json: any): ClubMemberRecord {
  return ClubMemberRecordToJSONTyped(json, false);
}

export function ClubMemberRecordToJSONTyped(
  value?: ClubMemberRecord | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    memberId: value["memberId"],
    clubId: value["clubId"],
    clubName: value["clubName"],
    userId: value["userId"],
    userName: value["userName"],
    studentNo: value["studentNo"],
    departmentId: value["departmentId"],
    departmentName: value["departmentName"],
    groupId: value["groupId"],
    groupName: value["groupName"],
    positionName: value["positionName"],
    termName: value["termName"],
    termStart:
      value["termStart"] == null ? value["termStart"] : serializeDateTime(value["termStart"]),
    termEnd: value["termEnd"] == null ? value["termEnd"] : serializeDateTime(value["termEnd"]),
    memberStatus: value["memberStatus"],
    joinAt: value["joinAt"] == null ? value["joinAt"] : serializeDateTime(value["joinAt"]),
    contributionScore: value["contributionScore"],
    isCurrent: value["isCurrent"],
  };
}
