// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 成员学期考核系统生成分预览；维护人可在系统生成分基础上微调后保存。
 * @export
 * @interface ClubEvaluationScorePreview
 */
export interface ClubEvaluationScorePreview {
  /**
   * 根据活动签到、签退和参与记录生成的活动分。
   * @type {number}
   * @memberof ClubEvaluationScorePreview
   */
  activityScore: number;
  /**
   * 根据项目任务进度、完成状态和成果审核生成的任务分。
   * @type {number}
   * @memberof ClubEvaluationScorePreview
   */
  taskScore: number;
  /**
   * 根据课程学习记录和进度生成的学习分。
   * @type {number}
   * @memberof ClubEvaluationScorePreview
   */
  learningScore: number;
  /**
   * 根据同社团、同成员、同学期评优评奖记录汇总生成的奖项分。
   * @type {number}
   * @memberof ClubEvaluationScorePreview
   */
  awardScore: number;
  /**
   * 四项系统生成分合计。
   * @type {number}
   * @memberof ClubEvaluationScorePreview
   */
  totalScore: number;
  /**
   * 后端根据总分计算的等级。
   * @type {string}
   * @memberof ClubEvaluationScorePreview
   */
  grade: string;
}

/**
 * Check if a given object implements the ClubEvaluationScorePreview interface.
 */
export function instanceOfClubEvaluationScorePreview(
  value: object,
): value is ClubEvaluationScorePreview {
  if (!("activityScore" in value) || value["activityScore"] === undefined) return false;
  if (!("taskScore" in value) || value["taskScore"] === undefined) return false;
  if (!("learningScore" in value) || value["learningScore"] === undefined) return false;
  if (!("awardScore" in value) || value["awardScore"] === undefined) return false;
  if (!("totalScore" in value) || value["totalScore"] === undefined) return false;
  if (!("grade" in value) || value["grade"] === undefined) return false;
  return true;
}

export function ClubEvaluationScorePreviewFromJSON(json: any): ClubEvaluationScorePreview {
  return ClubEvaluationScorePreviewFromJSONTyped(json, false);
}

export function ClubEvaluationScorePreviewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClubEvaluationScorePreview {
  if (json == null) {
    return json;
  }
  return {
    activityScore: json["activityScore"],
    taskScore: json["taskScore"],
    learningScore: json["learningScore"],
    awardScore: json["awardScore"],
    totalScore: json["totalScore"],
    grade: json["grade"],
  };
}

export function ClubEvaluationScorePreviewToJSON(json: any): ClubEvaluationScorePreview {
  return ClubEvaluationScorePreviewToJSONTyped(json, false);
}

export function ClubEvaluationScorePreviewToJSONTyped(
  value?: ClubEvaluationScorePreview | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    activityScore: value["activityScore"],
    taskScore: value["taskScore"],
    learningScore: value["learningScore"],
    awardScore: value["awardScore"],
    totalScore: value["totalScore"],
    grade: value["grade"],
  };
}
