// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Club
 */
export interface Club {
  /**
   *
   * @type {number}
   * @memberof Club
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  category?: string | null;
  /**
   *
   * @type {Date}
   * @memberof Club
   */
  foundedAt?: Date | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  status?: string | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  statusText: string;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  logoUrl?: string | null;
  /**
   *
   * @type {number}
   * @memberof Club
   */
  presidentUserId?: number | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  presidentName?: string | null;
  /**
   * 当前指导老师用户 ID，由 USER_ROLES 中 ADVISOR 社团角色关系推导。
   * @type {number}
   * @memberof Club
   */
  advisorUserId?: number | null;
  /**
   * 当前指导老师展示名称；优先由 ADVISOR 角色对应用户推导，历史数据可回退到社团文本字段。
   * @type {string}
   * @memberof Club
   */
  advisorName?: string | null;
  /**
   * 社团对外联系电话或负责人联系电话。
   * @type {string}
   * @memberof Club
   */
  contactPhone?: string | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  auditStatus?: string | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  auditStatusText: string;
  /**
   *
   * @type {number}
   * @memberof Club
   */
  applicantUserId?: number | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  applicantName?: string | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  applyReason?: string | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  materialUrl?: string | null;
  /**
   *
   * @type {number}
   * @memberof Club
   */
  reviewerUserId?: number | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  reviewerName?: string | null;
  /**
   *
   * @type {string}
   * @memberof Club
   */
  reviewComment?: string | null;
  /**
   *
   * @type {Date}
   * @memberof Club
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Club
   */
  updatedAt?: Date | null;
}

/**
 * Check if a given object implements the Club interface.
 */
export function instanceOfClub(value: object): value is Club {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("statusText" in value) || value["statusText"] === undefined) return false;
  if (!("auditStatusText" in value) || value["auditStatusText"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function ClubFromJSON(json: any): Club {
  return ClubFromJSONTyped(json, false);
}

export function ClubFromJSONTyped(json: any, ignoreDiscriminator: boolean): Club {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    description:
      json["description"] === undefined
        ? undefined
        : json["description"] === null
          ? null
          : json["description"],
    category:
      json["category"] === undefined
        ? undefined
        : json["category"] === null
          ? null
          : json["category"],
    foundedAt:
      json["foundedAt"] === undefined
        ? undefined
        : json["foundedAt"] === null
          ? null
          : new Date(json["foundedAt"]),
    status:
      json["status"] === undefined ? undefined : json["status"] === null ? null : json["status"],
    statusText: json["statusText"],
    logoUrl:
      json["logoUrl"] === undefined ? undefined : json["logoUrl"] === null ? null : json["logoUrl"],
    presidentUserId:
      json["presidentUserId"] === undefined
        ? undefined
        : json["presidentUserId"] === null
          ? null
          : json["presidentUserId"],
    presidentName:
      json["presidentName"] === undefined
        ? undefined
        : json["presidentName"] === null
          ? null
          : json["presidentName"],
    advisorUserId:
      json["advisorUserId"] === undefined
        ? undefined
        : json["advisorUserId"] === null
          ? null
          : json["advisorUserId"],
    advisorName:
      json["advisorName"] === undefined
        ? undefined
        : json["advisorName"] === null
          ? null
          : json["advisorName"],
    contactPhone:
      json["contactPhone"] === undefined
        ? undefined
        : json["contactPhone"] === null
          ? null
          : json["contactPhone"],
    auditStatus:
      json["auditStatus"] === undefined
        ? undefined
        : json["auditStatus"] === null
          ? null
          : json["auditStatus"],
    auditStatusText: json["auditStatusText"],
    applicantUserId:
      json["applicantUserId"] === undefined
        ? undefined
        : json["applicantUserId"] === null
          ? null
          : json["applicantUserId"],
    applicantName:
      json["applicantName"] === undefined
        ? undefined
        : json["applicantName"] === null
          ? null
          : json["applicantName"],
    applyReason:
      json["applyReason"] === undefined
        ? undefined
        : json["applyReason"] === null
          ? null
          : json["applyReason"],
    materialUrl:
      json["materialUrl"] === undefined
        ? undefined
        : json["materialUrl"] === null
          ? null
          : json["materialUrl"],
    reviewerUserId:
      json["reviewerUserId"] === undefined
        ? undefined
        : json["reviewerUserId"] === null
          ? null
          : json["reviewerUserId"],
    reviewerName:
      json["reviewerName"] === undefined
        ? undefined
        : json["reviewerName"] === null
          ? null
          : json["reviewerName"],
    reviewComment:
      json["reviewComment"] === undefined
        ? undefined
        : json["reviewComment"] === null
          ? null
          : json["reviewComment"],
    createdAt: new Date(json["createdAt"]),
    updatedAt:
      json["updatedAt"] === undefined
        ? undefined
        : json["updatedAt"] === null
          ? null
          : new Date(json["updatedAt"]),
  };
}

export function ClubToJSON(json: any): Club {
  return ClubToJSONTyped(json, false);
}

export function ClubToJSONTyped(value?: Club | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    description: value["description"],
    category: value["category"],
    foundedAt: value["foundedAt"] == null ? value["foundedAt"] : value["foundedAt"].toISOString(),
    status: value["status"],
    statusText: value["statusText"],
    logoUrl: value["logoUrl"],
    presidentUserId: value["presidentUserId"],
    presidentName: value["presidentName"],
    advisorUserId: value["advisorUserId"],
    advisorName: value["advisorName"],
    contactPhone: value["contactPhone"],
    auditStatus: value["auditStatus"],
    auditStatusText: value["auditStatusText"],
    applicantUserId: value["applicantUserId"],
    applicantName: value["applicantName"],
    applyReason: value["applyReason"],
    materialUrl: value["materialUrl"],
    reviewerUserId: value["reviewerUserId"],
    reviewerName: value["reviewerName"],
    reviewComment: value["reviewComment"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"] == null ? value["updatedAt"] : value["updatedAt"].toISOString(),
  };
}
