// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ClubMemberRecord
 */
export interface ClubMemberRecord {
  /**
   *
   * @type {number}
   * @memberof ClubMemberRecord
   */
  memberId: number;
  /**
   *
   * @type {number}
   * @memberof ClubMemberRecord
   */
  clubId: number;
  /**
   *
   * @type {string}
   * @memberof ClubMemberRecord
   */
  clubName: string;
  /**
   *
   * @type {number}
   * @memberof ClubMemberRecord
   */
  userId: number;
  /**
   *
   * @type {string}
   * @memberof ClubMemberRecord
   */
  userName: string;
  /**
   *
   * @type {string}
   * @memberof ClubMemberRecord
   */
  studentNo?: string | null;
  /**
   * 成员当前归属部门 ID；为空表示未归属部门。
   * @type {number}
   * @memberof ClubMemberRecord
   */
  departmentId?: number | null;
  /**
   *
   * @type {string}
   * @memberof ClubMemberRecord
   */
  departmentName?: string | null;
  /**
   * 成员当前归属小组 ID；为空表示未归属小组。
   * @type {number}
   * @memberof ClubMemberRecord
   */
  groupId?: number | null;
  /**
   *
   * @type {string}
   * @memberof ClubMemberRecord
   */
  groupName?: string | null;
  /**
   *
   * @type {string}
   * @memberof ClubMemberRecord
   */
  positionName?: string | null;
  /**
   *
   * @type {string}
   * @memberof ClubMemberRecord
   */
  termName?: string | null;
  /**
   *
   * @type {Date}
   * @memberof ClubMemberRecord
   */
  termStart?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof ClubMemberRecord
   */
  termEnd?: Date | null;
  /**
   *
   * @type {string}
   * @memberof ClubMemberRecord
   */
  memberStatus?: string | null;
  /**
   *
   * @type {Date}
   * @memberof ClubMemberRecord
   */
  joinAt?: Date | null;
  /**
   *
   * @type {number}
   * @memberof ClubMemberRecord
   */
  contributionScore?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof ClubMemberRecord
   */
  isCurrent: boolean;
}

/**
 * Check if a given object implements the ClubMemberRecord interface.
 */
export function instanceOfClubMemberRecord(value: object): value is ClubMemberRecord {
  if (!("memberId" in value) || value["memberId"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("clubName" in value) || value["clubName"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("userName" in value) || value["userName"] === undefined) return false;
  if (!("isCurrent" in value) || value["isCurrent"] === undefined) return false;
  return true;
}

export function ClubMemberRecordFromJSON(json: any): ClubMemberRecord {
  return ClubMemberRecordFromJSONTyped(json, false);
}

export function ClubMemberRecordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClubMemberRecord {
  if (json == null) {
    return json;
  }
  return {
    memberId: json["memberId"],
    clubId: json["clubId"],
    clubName: json["clubName"],
    userId: json["userId"],
    userName: json["userName"],
    studentNo: json["studentNo"] == null ? undefined : json["studentNo"],
    departmentId: json["departmentId"] == null ? undefined : json["departmentId"],
    departmentName: json["departmentName"] == null ? undefined : json["departmentName"],
    groupId: json["groupId"] == null ? undefined : json["groupId"],
    groupName: json["groupName"] == null ? undefined : json["groupName"],
    positionName: json["positionName"] == null ? undefined : json["positionName"],
    termName: json["termName"] == null ? undefined : json["termName"],
    termStart: json["termStart"] == null ? undefined : new Date(json["termStart"]),
    termEnd: json["termEnd"] == null ? undefined : new Date(json["termEnd"]),
    memberStatus: json["memberStatus"] == null ? undefined : json["memberStatus"],
    joinAt: json["joinAt"] == null ? undefined : new Date(json["joinAt"]),
    contributionScore: json["contributionScore"] == null ? undefined : json["contributionScore"],
    isCurrent: json["isCurrent"],
  };
}

export function ClubMemberRecordToJSON(json: any): ClubMemberRecord {
  return ClubMemberRecordToJSONTyped(json, false);
}

export function ClubMemberRecordToJSONTyped(
  value?: ClubMemberRecord | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    memberId: value["memberId"],
    clubId: value["clubId"],
    clubName: value["clubName"],
    userId: value["userId"],
    userName: value["userName"],
    studentNo: value["studentNo"],
    departmentId: value["departmentId"],
    departmentName: value["departmentName"],
    groupId: value["groupId"],
    groupName: value["groupName"],
    positionName: value["positionName"],
    termName: value["termName"],
    termStart: value["termStart"] == null ? value["termStart"] : value["termStart"].toISOString(),
    termEnd: value["termEnd"] == null ? value["termEnd"] : value["termEnd"].toISOString(),
    memberStatus: value["memberStatus"],
    joinAt: value["joinAt"] == null ? value["joinAt"] : value["joinAt"].toISOString(),
    contributionScore: value["contributionScore"],
    isCurrent: value["isCurrent"],
  };
}
