// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateClubMemberTermRequest
 */
export interface CreateClubMemberTermRequest {
  /**
   *
   * @type {number}
   * @memberof CreateClubMemberTermRequest
   */
  currentUserId: number;
  /**
   *
   * @type {number}
   * @memberof CreateClubMemberTermRequest
   */
  userId: number;
  /**
   *
   * @type {string}
   * @memberof CreateClubMemberTermRequest
   */
  departmentName?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateClubMemberTermRequest
   */
  groupName?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateClubMemberTermRequest
   */
  positionName: string;
  /**
   *
   * @type {string}
   * @memberof CreateClubMemberTermRequest
   */
  termName: string;
  /**
   *
   * @type {Date}
   * @memberof CreateClubMemberTermRequest
   */
  termStart: Date;
  /**
   *
   * @type {Date}
   * @memberof CreateClubMemberTermRequest
   */
  termEnd?: Date | null;
  /**
   *
   * @type {CreateClubMemberTermRequestMemberStatusEnum}
   * @memberof CreateClubMemberTermRequest
   */
  memberStatus?: CreateClubMemberTermRequestMemberStatusEnum;
  /**
   *
   * @type {number}
   * @memberof CreateClubMemberTermRequest
   */
  contributionScore?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof CreateClubMemberTermRequest
   */
  closeCurrentTerm?: boolean;
}

/**
 * @export
 */
export const CreateClubMemberTermRequestMemberStatusEnum = {
  Active: "active",
  Ended: "ended",
  Suspended: "suspended",
} as const;
export type CreateClubMemberTermRequestMemberStatusEnum =
  (typeof CreateClubMemberTermRequestMemberStatusEnum)[keyof typeof CreateClubMemberTermRequestMemberStatusEnum];

/**
 * Check if a given object implements the CreateClubMemberTermRequest interface.
 */
export function instanceOfCreateClubMemberTermRequest(
  value: object,
): value is CreateClubMemberTermRequest {
  if (!("currentUserId" in value) || value["currentUserId"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("positionName" in value) || value["positionName"] === undefined) return false;
  if (!("termName" in value) || value["termName"] === undefined) return false;
  if (!("termStart" in value) || value["termStart"] === undefined) return false;
  return true;
}

export function CreateClubMemberTermRequestFromJSON(json: any): CreateClubMemberTermRequest {
  return CreateClubMemberTermRequestFromJSONTyped(json, false);
}

export function CreateClubMemberTermRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateClubMemberTermRequest {
  if (json == null) {
    return json;
  }
  return {
    currentUserId: json["currentUserId"],
    userId: json["userId"],
    departmentName: json["departmentName"] == null ? undefined : json["departmentName"],
    groupName: json["groupName"] == null ? undefined : json["groupName"],
    positionName: json["positionName"],
    termName: json["termName"],
    termStart: new Date(json["termStart"]),
    termEnd: json["termEnd"] == null ? undefined : new Date(json["termEnd"]),
    memberStatus: json["memberStatus"] == null ? undefined : json["memberStatus"],
    contributionScore: json["contributionScore"] == null ? undefined : json["contributionScore"],
    closeCurrentTerm: json["closeCurrentTerm"] == null ? undefined : json["closeCurrentTerm"],
  };
}

export function CreateClubMemberTermRequestToJSON(json: any): CreateClubMemberTermRequest {
  return CreateClubMemberTermRequestToJSONTyped(json, false);
}

export function CreateClubMemberTermRequestToJSONTyped(
  value?: CreateClubMemberTermRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentUserId: value["currentUserId"],
    userId: value["userId"],
    departmentName: value["departmentName"],
    groupName: value["groupName"],
    positionName: value["positionName"],
    termName: value["termName"],
    termStart: value["termStart"].toISOString(),
    termEnd: value["termEnd"] == null ? value["termEnd"] : value["termEnd"].toISOString(),
    memberStatus: value["memberStatus"],
    contributionScore: value["contributionScore"],
    closeCurrentTerm: value["closeCurrentTerm"],
  };
}
