// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 创建评奖评优申请或负责人推荐；awardSchemeId 必须属于当前路径社团，且对应奖项处于开放申请或审核中，并仍在申请时间窗内。
 * @export
 * @interface CreateAwardApplicationRequest
 */
export interface CreateAwardApplicationRequest {
  /**
   *
   * @type {number}
   * @memberof CreateAwardApplicationRequest
   */
  awardSchemeId: number;
  /**
   *
   * @type {number}
   * @memberof CreateAwardApplicationRequest
   */
  awardLevelId: number;
  /**
   * 被推荐或申请的社团成员用户 ID。
   * @type {number}
   * @memberof CreateAwardApplicationRequest
   */
  applicantUserId: number;
  /**
   *
   * @type {CreateAwardApplicationRequestApplicationTypeEnum}
   * @memberof CreateAwardApplicationRequest
   */
  applicationType: CreateAwardApplicationRequestApplicationTypeEnum;
  /**
   * 申请理由或推荐理由。
   * @type {string}
   * @memberof CreateAwardApplicationRequest
   */
  applicationReason: string;
  /**
   * 兼容字段，由申请材料上传接口维护内部文件引用；新前端不应让用户手填地址。
   * @type {string}
   * @memberof CreateAwardApplicationRequest
   */
  materialUrl?: string | null;
  /**
   * 是否创建后立即提交到负责人初审。
   * @type {boolean}
   * @memberof CreateAwardApplicationRequest
   */
  submitNow?: boolean;
}

/**
 * @export
 */
export const CreateAwardApplicationRequestApplicationTypeEnum = {
  Self: "self",
  Recommendation: "recommendation",
} as const;
export type CreateAwardApplicationRequestApplicationTypeEnum =
  (typeof CreateAwardApplicationRequestApplicationTypeEnum)[keyof typeof CreateAwardApplicationRequestApplicationTypeEnum];

/**
 * Check if a given object implements the CreateAwardApplicationRequest interface.
 */
export function instanceOfCreateAwardApplicationRequest(
  value: object,
): value is CreateAwardApplicationRequest {
  if (!("awardSchemeId" in value) || value["awardSchemeId"] === undefined) return false;
  if (!("awardLevelId" in value) || value["awardLevelId"] === undefined) return false;
  if (!("applicantUserId" in value) || value["applicantUserId"] === undefined) return false;
  if (!("applicationType" in value) || value["applicationType"] === undefined) return false;
  if (!("applicationReason" in value) || value["applicationReason"] === undefined) return false;
  return true;
}

export function CreateAwardApplicationRequestFromJSON(json: any): CreateAwardApplicationRequest {
  return CreateAwardApplicationRequestFromJSONTyped(json, false);
}

export function CreateAwardApplicationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAwardApplicationRequest {
  if (json == null) {
    return json;
  }
  return {
    awardSchemeId: json["awardSchemeId"],
    awardLevelId: json["awardLevelId"],
    applicantUserId: json["applicantUserId"],
    applicationType: json["applicationType"],
    applicationReason: json["applicationReason"],
    materialUrl:
      json["materialUrl"] === undefined
        ? undefined
        : json["materialUrl"] === null
          ? null
          : json["materialUrl"],
    submitNow: json["submitNow"] == null ? undefined : json["submitNow"],
  };
}

export function CreateAwardApplicationRequestToJSON(json: any): CreateAwardApplicationRequest {
  return CreateAwardApplicationRequestToJSONTyped(json, false);
}

export function CreateAwardApplicationRequestToJSONTyped(
  value?: CreateAwardApplicationRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    awardSchemeId: value["awardSchemeId"],
    awardLevelId: value["awardLevelId"],
    applicantUserId: value["applicantUserId"],
    applicationType: value["applicationType"],
    applicationReason: value["applicationReason"],
    materialUrl: value["materialUrl"],
    submitNow: value["submitNow"],
  };
}
