// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 创建评奖评优公示批次。
 * @export
 * @interface CreateAwardPublicityBatchRequest
 */
export interface CreateAwardPublicityBatchRequest {
  /**
   *
   * @type {string}
   * @memberof CreateAwardPublicityBatchRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreateAwardPublicityBatchRequest
   */
  description?: string | null;
  /**
   *
   * @type {Date}
   * @memberof CreateAwardPublicityBatchRequest
   */
  publicityStartAt?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof CreateAwardPublicityBatchRequest
   */
  publicityEndAt?: Date | null;
  /**
   * 纳入公示的已通过申请 ID。
   * @type {Array<number>}
   * @memberof CreateAwardPublicityBatchRequest
   */
  awardApplicationIds: Array<number>;
}

/**
 * Check if a given object implements the CreateAwardPublicityBatchRequest interface.
 */
export function instanceOfCreateAwardPublicityBatchRequest(
  value: object,
): value is CreateAwardPublicityBatchRequest {
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("awardApplicationIds" in value) || value["awardApplicationIds"] === undefined) return false;
  return true;
}

export function CreateAwardPublicityBatchRequestFromJSON(
  json: any,
): CreateAwardPublicityBatchRequest {
  return CreateAwardPublicityBatchRequestFromJSONTyped(json, false);
}

export function CreateAwardPublicityBatchRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAwardPublicityBatchRequest {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"],
    description: json["description"] == null ? undefined : json["description"],
    publicityStartAt:
      json["publicityStartAt"] == null ? undefined : new Date(json["publicityStartAt"]),
    publicityEndAt: json["publicityEndAt"] == null ? undefined : new Date(json["publicityEndAt"]),
    awardApplicationIds: json["awardApplicationIds"],
  };
}

export function CreateAwardPublicityBatchRequestToJSON(
  json: any,
): CreateAwardPublicityBatchRequest {
  return CreateAwardPublicityBatchRequestToJSONTyped(json, false);
}

export function CreateAwardPublicityBatchRequestToJSONTyped(
  value?: CreateAwardPublicityBatchRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    description: value["description"],
    publicityStartAt:
      value["publicityStartAt"] == null
        ? value["publicityStartAt"]
        : value["publicityStartAt"].toISOString(),
    publicityEndAt:
      value["publicityEndAt"] == null
        ? value["publicityEndAt"]
        : value["publicityEndAt"].toISOString(),
    awardApplicationIds: value["awardApplicationIds"],
  };
}
