// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from "../runtime";
/**
 * 创建活动请求。创建人由服务端从登录态写入，客户端无需也不应提交 creatorUserId。
 * @export
 * @interface CreateActivityRequest
 */
export interface CreateActivityRequest {
  /**
   *
   */
  clubId: number;
  /**
   * 已废弃，服务端从 JWT 读取身份。
   * @deprecated
   */
  creatorUserId?: number | null;
  /**
   *
   */
  title: string;
  /**
   *
   */
  activityType?: string | null;
  /**
   *
   */
  description?: string | null;
  /**
   *
   */
  location?: string | null;
  /**
   *
   */
  startTime: Date;
  /**
   *
   */
  endTime: Date;
  /**
   *
   */
  maxParticipants?: number | null;
  /**
   *
   */
  registrationDeadline?: Date | null;
}

/**
 * Check if a given object implements the CreateActivityRequest interface.
 */
export function instanceOfCreateActivityRequest(value: object): value is CreateActivityRequest {
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("startTime" in value) || value["startTime"] === undefined) return false;
  if (!("endTime" in value) || value["endTime"] === undefined) return false;
  return true;
}

export function CreateActivityRequestFromJSON(json: any): CreateActivityRequest {
  return CreateActivityRequestFromJSONTyped(json, false);
}

export function CreateActivityRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateActivityRequest {
  if (json == null) {
    return json;
  }
  return {
    clubId: json["clubId"],
    creatorUserId:
      json["creatorUserId"] === undefined
        ? undefined
        : json["creatorUserId"] === null
          ? null
          : json["creatorUserId"],
    title: json["title"],
    activityType:
      json["activityType"] === undefined
        ? undefined
        : json["activityType"] === null
          ? null
          : json["activityType"],
    description:
      json["description"] === undefined
        ? undefined
        : json["description"] === null
          ? null
          : json["description"],
    location:
      json["location"] === undefined
        ? undefined
        : json["location"] === null
          ? null
          : json["location"],
    startTime: json["startTime"] == null ? json["startTime"] : parseDateTime(json["startTime"]),
    endTime: json["endTime"] == null ? json["endTime"] : parseDateTime(json["endTime"]),
    maxParticipants:
      json["maxParticipants"] === undefined
        ? undefined
        : json["maxParticipants"] === null
          ? null
          : json["maxParticipants"],
    registrationDeadline:
      json["registrationDeadline"] === undefined
        ? undefined
        : json["registrationDeadline"] === null
          ? null
          : parseDateTime(json["registrationDeadline"]),
  };
}

export function CreateActivityRequestToJSON(json: any): CreateActivityRequest {
  return CreateActivityRequestToJSONTyped(json, false);
}

export function CreateActivityRequestToJSONTyped(
  value?: CreateActivityRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clubId: value["clubId"],
    creatorUserId: value["creatorUserId"],
    title: value["title"],
    activityType: value["activityType"],
    description: value["description"],
    location: value["location"],
    startTime:
      value["startTime"] == null ? value["startTime"] : serializeDateTime(value["startTime"]),
    endTime: value["endTime"] == null ? value["endTime"] : serializeDateTime(value["endTime"]),
    maxParticipants: value["maxParticipants"],
    registrationDeadline:
      value["registrationDeadline"] == null
        ? value["registrationDeadline"]
        : serializeDateTime(value["registrationDeadline"]),
  };
}
