// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateRecruitmentApplicationRequest
 */
export interface CreateRecruitmentApplicationRequest {
  /**
   *
   * @type {number}
   * @memberof CreateRecruitmentApplicationRequest
   */
  currentUserId: number;
  /**
   *
   * @type {string}
   * @memberof CreateRecruitmentApplicationRequest
   */
  applicationReason: string;
}

/**
 * Check if a given object implements the CreateRecruitmentApplicationRequest interface.
 */
export function instanceOfCreateRecruitmentApplicationRequest(
  value: object,
): value is CreateRecruitmentApplicationRequest {
  if (!("currentUserId" in value) || value["currentUserId"] === undefined) return false;
  if (!("applicationReason" in value) || value["applicationReason"] === undefined) return false;
  return true;
}

export function CreateRecruitmentApplicationRequestFromJSON(
  json: any,
): CreateRecruitmentApplicationRequest {
  return CreateRecruitmentApplicationRequestFromJSONTyped(json, false);
}

export function CreateRecruitmentApplicationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateRecruitmentApplicationRequest {
  if (json == null) {
    return json;
  }
  return {
    currentUserId: json["currentUserId"],
    applicationReason: json["applicationReason"],
  };
}

export function CreateRecruitmentApplicationRequestToJSON(
  json: any,
): CreateRecruitmentApplicationRequest {
  return CreateRecruitmentApplicationRequestToJSONTyped(json, false);
}

export function CreateRecruitmentApplicationRequestToJSONTyped(
  value?: CreateRecruitmentApplicationRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentUserId: value["currentUserId"],
    applicationReason: value["applicationReason"],
  };
}
