// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Request body for creating a project initiation application.
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
  /**
   * 褰撳墠鎻愪氦绔嬮」鐢宠鐨勭敤鎴?ID锛涘悗绔嵁姝ゆ牎楠屽叾鏄惁涓虹郴缁熺鐞嗗憳鎴栨湰绀惧洟璐熻矗浜恒€?     * @type {number}
   * @memberof CreateProjectRequest
   */
  currentUserId: number;
  /**
   * Club that submits the project application.
   * @type {number}
   * @memberof CreateProjectRequest
   */
  clubId: number;
  /**
   * Project name.
   * @type {string}
   * @memberof CreateProjectRequest
   */
  projectName: string;
  /**
   * Optional project description.
   * @type {string}
   * @memberof CreateProjectRequest
   */
  description?: string | null;
  /**
   * Optional project leader user id.
   * @type {number}
   * @memberof CreateProjectRequest
   */
  leaderUserId?: number | null;
  /**
   * Planned project start time.
   * @type {Date}
   * @memberof CreateProjectRequest
   */
  startDate: Date;
  /**
   * Optional planned project end time.
   * @type {Date}
   * @memberof CreateProjectRequest
   */
  endDate?: Date | null;
}

/**
 * Check if a given object implements the CreateProjectRequest interface.
 */
export function instanceOfCreateProjectRequest(value: object): value is CreateProjectRequest {
  if (!("currentUserId" in value) || value["currentUserId"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("projectName" in value) || value["projectName"] === undefined) return false;
  if (!("startDate" in value) || value["startDate"] === undefined) return false;
  return true;
}

export function CreateProjectRequestFromJSON(json: any): CreateProjectRequest {
  return CreateProjectRequestFromJSONTyped(json, false);
}

export function CreateProjectRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateProjectRequest {
  if (json == null) {
    return json;
  }
  return {
    currentUserId: json["currentUserId"],
    clubId: json["clubId"],
    projectName: json["projectName"],
    description: json["description"] == null ? undefined : json["description"],
    leaderUserId: json["leaderUserId"] == null ? undefined : json["leaderUserId"],
    startDate: new Date(json["startDate"]),
    endDate: json["endDate"] == null ? undefined : new Date(json["endDate"]),
  };
}

export function CreateProjectRequestToJSON(json: any): CreateProjectRequest {
  return CreateProjectRequestToJSONTyped(json, false);
}

export function CreateProjectRequestToJSONTyped(
  value?: CreateProjectRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentUserId: value["currentUserId"],
    clubId: value["clubId"],
    projectName: value["projectName"],
    description: value["description"],
    leaderUserId: value["leaderUserId"],
    startDate: value["startDate"].toISOString(),
    endDate: value["endDate"] == null ? value["endDate"] : value["endDate"].toISOString(),
  };
}
