// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateVenueReservationRequest
 */
export interface CreateVenueReservationRequest {
  /**
   *
   * @type {number}
   * @memberof CreateVenueReservationRequest
   */
  venueId: number;
  /**
   *
   * @type {number}
   * @memberof CreateVenueReservationRequest
   */
  clubId: number;
  /**
   *
   * @type {number}
   * @memberof CreateVenueReservationRequest
   */
  activityId?: number | null;
  /**
   *
   * @type {number}
   * @memberof CreateVenueReservationRequest
   */
  applicantUserId: number;
  /**
   *
   * @type {Date}
   * @memberof CreateVenueReservationRequest
   */
  startTime: Date;
  /**
   *
   * @type {Date}
   * @memberof CreateVenueReservationRequest
   */
  endTime: Date;
  /**
   *
   * @type {string}
   * @memberof CreateVenueReservationRequest
   */
  purpose: string;
}

/**
 * Check if a given object implements the CreateVenueReservationRequest interface.
 */
export function instanceOfCreateVenueReservationRequest(
  value: object,
): value is CreateVenueReservationRequest {
  if (!("venueId" in value) || value["venueId"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("applicantUserId" in value) || value["applicantUserId"] === undefined) return false;
  if (!("startTime" in value) || value["startTime"] === undefined) return false;
  if (!("endTime" in value) || value["endTime"] === undefined) return false;
  if (!("purpose" in value) || value["purpose"] === undefined) return false;
  return true;
}

export function CreateVenueReservationRequestFromJSON(json: any): CreateVenueReservationRequest {
  return CreateVenueReservationRequestFromJSONTyped(json, false);
}

export function CreateVenueReservationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateVenueReservationRequest {
  if (json == null) {
    return json;
  }
  return {
    venueId: json["venueId"],
    clubId: json["clubId"],
    activityId: json["activityId"] == null ? undefined : json["activityId"],
    applicantUserId: json["applicantUserId"],
    startTime: new Date(json["startTime"]),
    endTime: new Date(json["endTime"]),
    purpose: json["purpose"],
  };
}

export function CreateVenueReservationRequestToJSON(json: any): CreateVenueReservationRequest {
  return CreateVenueReservationRequestToJSONTyped(json, false);
}

export function CreateVenueReservationRequestToJSONTyped(
  value?: CreateVenueReservationRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    venueId: value["venueId"],
    clubId: value["clubId"],
    activityId: value["activityId"],
    applicantUserId: value["applicantUserId"],
    startTime: value["startTime"].toISOString(),
    endTime: value["endTime"].toISOString(),
    purpose: value["purpose"],
  };
}
