// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 鍙戝竷鍏憡閫氱煡璇锋眰銆? * @export
 * @interface CreateNoticeRequest
 */
export interface CreateNoticeRequest {
  /**
   * 褰撳墠鍙戝竷浜虹敤鎴?ID銆?     * @type {number}
   * @memberof CreateNoticeRequest
   */
  currentUserId: number;
  /**
   * 閫氱煡绫诲瀷锛屼緥濡?announcement銆乽rgent銆乪vent銆?     * @type {string}
   * @memberof CreateNoticeRequest
   */
  noticeType: string;
  /**
   * 閫氱煡鏍囬銆?     * @type {string}
   * @memberof CreateNoticeRequest
   */
  title: string;
  /**
   * 閫氱煡姝ｆ枃銆?     * @type {string}
   * @memberof CreateNoticeRequest
   */
  content: string;
  /**
   * 瀹氬悜绫诲瀷銆?     * @type {CreateNoticeRequestTargetTypeEnum}
   * @memberof CreateNoticeRequest
   */
  targetType: CreateNoticeRequestTargetTypeEnum;
  /**
   * 鎴愬憳瀹氬悜鎵€灞炵ぞ鍥?ID锛涗粎 member 瀹氬悜闇€瑕佷綔涓虹ぞ鍥笂涓嬫枃锛屽叏鏍°€佺ぞ鍥€侀儴闂ㄥ畾鍚戝彲涓虹┖銆?     * @type {number}
   * @memberof CreateNoticeRequest
   */
  clubId?: number | null;
  /**
   * 鐩爣 ID锛泂chool 涓虹┖锛宑lub 浼犵洰鏍囩ぞ鍥?ID锛宒epartment 浼犳垚鍛樹换鏈?memberId锛宮ember 浼犵洰鏍?userId銆?     * @type {number}
   * @memberof CreateNoticeRequest
   */
  targetId?: number | null;
  /**
   * 杩囨湡鏃堕棿锛屽繀椤绘櫄浜庡彂甯冩椂闂淬€?     * @type {Date}
   * @memberof CreateNoticeRequest
   */
  expireAt?: Date | null;
  /**
   * 閫氱煡鐘舵€侊紱榛樿 published銆?     * @type {CreateNoticeRequestNoticeStatusEnum}
   * @memberof CreateNoticeRequest
   */
  noticeStatus?: CreateNoticeRequestNoticeStatusEnum;
}

/**
 * @export
 */
export const CreateNoticeRequestTargetTypeEnum = {
  School: "school",
  Club: "club",
  Department: "department",
  Member: "member",
} as const;
export type CreateNoticeRequestTargetTypeEnum =
  (typeof CreateNoticeRequestTargetTypeEnum)[keyof typeof CreateNoticeRequestTargetTypeEnum];

/**
 * @export
 */
export const CreateNoticeRequestNoticeStatusEnum = {
  Draft: "draft",
  Published: "published",
} as const;
export type CreateNoticeRequestNoticeStatusEnum =
  (typeof CreateNoticeRequestNoticeStatusEnum)[keyof typeof CreateNoticeRequestNoticeStatusEnum];

/**
 * Check if a given object implements the CreateNoticeRequest interface.
 */
export function instanceOfCreateNoticeRequest(value: object): value is CreateNoticeRequest {
  if (!("currentUserId" in value) || value["currentUserId"] === undefined) return false;
  if (!("noticeType" in value) || value["noticeType"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("content" in value) || value["content"] === undefined) return false;
  if (!("targetType" in value) || value["targetType"] === undefined) return false;
  return true;
}

export function CreateNoticeRequestFromJSON(json: any): CreateNoticeRequest {
  return CreateNoticeRequestFromJSONTyped(json, false);
}

export function CreateNoticeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateNoticeRequest {
  if (json == null) {
    return json;
  }
  return {
    currentUserId: json["currentUserId"],
    noticeType: json["noticeType"],
    title: json["title"],
    content: json["content"],
    targetType: json["targetType"],
    clubId: json["clubId"] == null ? undefined : json["clubId"],
    targetId: json["targetId"] == null ? undefined : json["targetId"],
    expireAt: json["expireAt"] == null ? undefined : new Date(json["expireAt"]),
    noticeStatus: json["noticeStatus"] == null ? undefined : json["noticeStatus"],
  };
}

export function CreateNoticeRequestToJSON(json: any): CreateNoticeRequest {
  return CreateNoticeRequestToJSONTyped(json, false);
}

export function CreateNoticeRequestToJSONTyped(
  value?: CreateNoticeRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentUserId: value["currentUserId"],
    noticeType: value["noticeType"],
    title: value["title"],
    content: value["content"],
    targetType: value["targetType"],
    clubId: value["clubId"],
    targetId: value["targetId"],
    expireAt: value["expireAt"] == null ? value["expireAt"] : value["expireAt"].toISOString(),
    noticeStatus: value["noticeStatus"],
  };
}
