// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DependencyHealthCheck
 */
export interface DependencyHealthCheck {
  /**
   *
   * @type {DependencyHealthCheckStatusEnum}
   * @memberof DependencyHealthCheck
   */
  status: DependencyHealthCheckStatusEnum;
  /**
   *
   * @type {string}
   * @memberof DependencyHealthCheck
   */
  description?: string | null;
}

/**
 * @export
 */
export const DependencyHealthCheckStatusEnum = {
  Healthy: "healthy",
  Degraded: "degraded",
  Unhealthy: "unhealthy",
} as const;
export type DependencyHealthCheckStatusEnum =
  (typeof DependencyHealthCheckStatusEnum)[keyof typeof DependencyHealthCheckStatusEnum];

/**
 * Check if a given object implements the DependencyHealthCheck interface.
 */
export function instanceOfDependencyHealthCheck(value: object): value is DependencyHealthCheck {
  if (!("status" in value) || value["status"] === undefined) return false;
  return true;
}

export function DependencyHealthCheckFromJSON(json: any): DependencyHealthCheck {
  return DependencyHealthCheckFromJSONTyped(json, false);
}

export function DependencyHealthCheckFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DependencyHealthCheck {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    description:
      json["description"] === undefined
        ? undefined
        : json["description"] === null
          ? null
          : json["description"],
  };
}

export function DependencyHealthCheckToJSON(json: any): DependencyHealthCheck {
  return DependencyHealthCheckToJSONTyped(json, false);
}

export function DependencyHealthCheckToJSONTyped(
  value?: DependencyHealthCheck | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    description: value["description"],
  };
}
