// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Request body for joining or exiting a training course.
 * @export
 * @interface EnrollLearningItemRequest
 */
export interface EnrollLearningItemRequest {
  /**
   * Current user id.
   * @type {number}
   * @memberof EnrollLearningItemRequest
   */
  currentUserId: number;
}

/**
 * Check if a given object implements the EnrollLearningItemRequest interface.
 */
export function instanceOfEnrollLearningItemRequest(
  value: object,
): value is EnrollLearningItemRequest {
  if (!("currentUserId" in value) || value["currentUserId"] === undefined) return false;
  return true;
}

export function EnrollLearningItemRequestFromJSON(json: any): EnrollLearningItemRequest {
  return EnrollLearningItemRequestFromJSONTyped(json, false);
}

export function EnrollLearningItemRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EnrollLearningItemRequest {
  if (json == null) {
    return json;
  }
  return {
    currentUserId: json["currentUserId"],
  };
}

export function EnrollLearningItemRequestToJSON(json: any): EnrollLearningItemRequest {
  return EnrollLearningItemRequestToJSONTyped(json, false);
}

export function EnrollLearningItemRequestToJSONTyped(
  value?: EnrollLearningItemRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentUserId: value["currentUserId"],
  };
}
