// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 下载权限校验通过后返回的可访问资源地址与记录时间；OSS 资源返回受鉴权的后端流式下载地址。
 * @export
 * @interface LearningDownloadResult
 */
export interface LearningDownloadResult {
  /**
   *
   * @type {number}
   * @memberof LearningDownloadResult
   */
  itemId: number;
  /**
   *
   * @type {string}
   * @memberof LearningDownloadResult
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof LearningDownloadResult
   */
  fileUrl: string;
  /**
   *
   * @type {Date}
   * @memberof LearningDownloadResult
   */
  downloadedAt: Date;
}

/**
 * Check if a given object implements the LearningDownloadResult interface.
 */
export function instanceOfLearningDownloadResult(value: object): value is LearningDownloadResult {
  if (!("itemId" in value) || value["itemId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("fileUrl" in value) || value["fileUrl"] === undefined) return false;
  if (!("downloadedAt" in value) || value["downloadedAt"] === undefined) return false;
  return true;
}

export function LearningDownloadResultFromJSON(json: any): LearningDownloadResult {
  return LearningDownloadResultFromJSONTyped(json, false);
}

export function LearningDownloadResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LearningDownloadResult {
  if (json == null) {
    return json;
  }
  return {
    itemId: json["itemId"],
    title: json["title"],
    fileUrl: json["fileUrl"],
    downloadedAt: new Date(json["downloadedAt"]),
  };
}

export function LearningDownloadResultToJSON(json: any): LearningDownloadResult {
  return LearningDownloadResultToJSONTyped(json, false);
}

export function LearningDownloadResultToJSONTyped(
  value?: LearningDownloadResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    itemId: value["itemId"],
    title: value["title"],
    fileUrl: value["fileUrl"],
    downloadedAt: value["downloadedAt"].toISOString(),
  };
}
