// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Training course or learning resource published by a club.
 * @export
 * @interface LearningItem
 */
export interface LearningItem {
  /**
   * Learning item id in LEARNING_ITEMS.ITEM_ID.
   * @type {number}
   * @memberof LearningItem
   */
  id: number;
  /**
   * Club that publishes the course.
   * @type {number}
   * @memberof LearningItem
   */
  clubId: number;
  /**
   * User who created or uploaded the learning item.
   * @type {number}
   * @memberof LearningItem
   */
  uploaderUserId?: number | null;
  /**
   * Instructor user id.
   * @type {number}
   * @memberof LearningItem
   */
  teacherUserId?: number | null;
  /**
   * Course title.
   * @type {string}
   * @memberof LearningItem
   */
  title: string;
  /**
   * Course type, video, document, or other learning resource type.
   * @type {string}
   * @memberof LearningItem
   */
  itemType?: string | null;
  /**
   * Course category.
   * @type {string}
   * @memberof LearningItem
   */
  categoryName?: string | null;
  /**
   * Course introduction.
   * @type {string}
   * @memberof LearningItem
   */
  description?: string | null;
  /**
   * Required course start time; learning progress cannot be updated before this time.
   * @type {Date}
   * @memberof LearningItem
   */
  startAt: Date;
  /**
   * Optional course end time; when omitted, users may join at any time.
   * @type {Date}
   * @memberof LearningItem
   */
  endAt?: Date | null;
  /**
   * Maximum number of users who may join the course.
   * @type {number}
   * @memberof LearningItem
   */
  capacity: number;
  /**
   * Course audience; club means active club members, public means all active school accounts.
   * @type {LearningItemVisibilityEnum}
   * @memberof LearningItem
   */
  visibility: LearningItemVisibilityEnum;
  /**
   * Current course publication status.
   * @type {LearningItemItemStatusEnum}
   * @memberof LearningItem
   */
  itemStatus: LearningItemItemStatusEnum;
  /**
   * Number of users currently joined.
   * @type {number}
   * @memberof LearningItem
   */
  currentEnrollments: number;
  /**
   * Current viewer's learning record status; none means not enrolled.
   * @type {LearningItemCurrentUserRecordStatusEnum}
   * @memberof LearningItem
   */
  currentUserRecordStatus: LearningItemCurrentUserRecordStatusEnum;
  /**
   * Whether the current viewer may edit this course and view its roster.
   * @type {boolean}
   * @memberof LearningItem
   */
  canManage: boolean;
  /**
   * Whether the current viewer may join the course now.
   * @type {boolean}
   * @memberof LearningItem
   */
  canEnroll: boolean;
  /**
   * Whether the current viewer may exit the course now.
   * @type {boolean}
   * @memberof LearningItem
   */
  canCancelEnrollment: boolean;
  /**
   * Chinese explanation shown when enrollment is unavailable.
   * @type {string}
   * @memberof LearningItem
   */
  enrollmentUnavailableReason?: string | null;
}

/**
 * @export
 */
export const LearningItemVisibilityEnum = {
  Club: "club",
  Public: "public",
} as const;
export type LearningItemVisibilityEnum =
  (typeof LearningItemVisibilityEnum)[keyof typeof LearningItemVisibilityEnum];

/**
 * @export
 */
export const LearningItemItemStatusEnum = {
  Draft: "draft",
  Published: "published",
  Closed: "closed",
  Finished: "finished",
} as const;
export type LearningItemItemStatusEnum =
  (typeof LearningItemItemStatusEnum)[keyof typeof LearningItemItemStatusEnum];

/**
 * @export
 */
export const LearningItemCurrentUserRecordStatusEnum = {
  None: "none",
  Enrolled: "enrolled",
  Learning: "learning",
  Completed: "completed",
  Cancelled: "cancelled",
} as const;
export type LearningItemCurrentUserRecordStatusEnum =
  (typeof LearningItemCurrentUserRecordStatusEnum)[keyof typeof LearningItemCurrentUserRecordStatusEnum];

/**
 * Check if a given object implements the LearningItem interface.
 */
export function instanceOfLearningItem(value: object): value is LearningItem {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("startAt" in value) || value["startAt"] === undefined) return false;
  if (!("capacity" in value) || value["capacity"] === undefined) return false;
  if (!("visibility" in value) || value["visibility"] === undefined) return false;
  if (!("itemStatus" in value) || value["itemStatus"] === undefined) return false;
  if (!("currentEnrollments" in value) || value["currentEnrollments"] === undefined) return false;
  if (!("currentUserRecordStatus" in value) || value["currentUserRecordStatus"] === undefined)
    return false;
  if (!("canManage" in value) || value["canManage"] === undefined) return false;
  if (!("canEnroll" in value) || value["canEnroll"] === undefined) return false;
  if (!("canCancelEnrollment" in value) || value["canCancelEnrollment"] === undefined) return false;
  return true;
}

export function LearningItemFromJSON(json: any): LearningItem {
  return LearningItemFromJSONTyped(json, false);
}

export function LearningItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningItem {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    clubId: json["clubId"],
    uploaderUserId: json["uploaderUserId"] == null ? undefined : json["uploaderUserId"],
    teacherUserId: json["teacherUserId"] == null ? undefined : json["teacherUserId"],
    title: json["title"],
    itemType: json["itemType"] == null ? undefined : json["itemType"],
    categoryName: json["categoryName"] == null ? undefined : json["categoryName"],
    description: json["description"] == null ? undefined : json["description"],
    startAt: new Date(json["startAt"]),
    endAt: json["endAt"] == null ? undefined : new Date(json["endAt"]),
    capacity: json["capacity"],
    visibility: json["visibility"],
    itemStatus: json["itemStatus"],
    currentEnrollments: json["currentEnrollments"],
    currentUserRecordStatus: json["currentUserRecordStatus"],
    canManage: json["canManage"],
    canEnroll: json["canEnroll"],
    canCancelEnrollment: json["canCancelEnrollment"],
    enrollmentUnavailableReason:
      json["enrollmentUnavailableReason"] == null ? undefined : json["enrollmentUnavailableReason"],
  };
}

export function LearningItemToJSON(json: any): LearningItem {
  return LearningItemToJSONTyped(json, false);
}

export function LearningItemToJSONTyped(
  value?: LearningItem | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    clubId: value["clubId"],
    uploaderUserId: value["uploaderUserId"],
    teacherUserId: value["teacherUserId"],
    title: value["title"],
    itemType: value["itemType"],
    categoryName: value["categoryName"],
    description: value["description"],
    startAt: value["startAt"].toISOString(),
    endAt: value["endAt"] == null ? value["endAt"] : value["endAt"].toISOString(),
    capacity: value["capacity"],
    visibility: value["visibility"],
    itemStatus: value["itemStatus"],
    currentEnrollments: value["currentEnrollments"],
    currentUserRecordStatus: value["currentUserRecordStatus"],
    canManage: value["canManage"],
    canEnroll: value["canEnroll"],
    canCancelEnrollment: value["canCancelEnrollment"],
    enrollmentUnavailableReason: value["enrollmentUnavailableReason"],
  };
}
