// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平�?API�? **API-first 开发流�?*：修改本文件 �?push �?CI 自动生成前后端代�?�?git pull 拉取生成代码 �?�?Controller / Services / Vue 组件中手写业务逻辑�?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 公告通知及当前用户已读状态�? * @export
 * @interface Notice
 */
export interface Notice {
  /**
   * 通知 ID�?     * @type {number}
   * @memberof Notice
   */
  id: number;
  /**
   * 社团 ID；全校通知可为空�?     * @type {number}
   * @memberof Notice
   */
  clubId?: number | null;
  /**
   * 社团名称�?     * @type {string}
   * @memberof Notice
   */
  clubName?: string | null;
  /**
   * 发布人用�?ID�?     * @type {number}
   * @memberof Notice
   */
  publisherUserId: number;
  /**
   * 发布人展示名称�?     * @type {string}
   * @memberof Notice
   */
  publisherName?: string | null;
  /**
   * 通知类型，例�?announcement、urgent、event�?     * @type {string}
   * @memberof Notice
   */
  noticeType: string;
  /**
   * 通知标题�?     * @type {string}
   * @memberof Notice
   */
  title: string;
  /**
   * 通知正文�?     * @type {string}
   * @memberof Notice
   */
  content: string;
  /**
   * 定向类型�?     * @type {NoticeTargetTypeEnum}
   * @memberof Notice
   */
  targetType: NoticeTargetTypeEnum;
  /**
   * 目标 ID；社团通知�?clubId，部门通知为成员任�?memberId，成员通知�?userId，全校通知为空�?     * @type {number}
   * @memberof Notice
   */
  targetId?: number | null;
  /**
   * 前端展示用目标名称�?     * @type {string}
   * @memberof Notice
   */
  targetName?: string | null;
  /**
   * 发布时间�?     * @type {Date}
   * @memberof Notice
   */
  publishAt: Date;
  /**
   * 过期时间�?     * @type {Date}
   * @memberof Notice
   */
  expireAt?: Date | null;
  /**
   * 通知状态�?     * @type {NoticeNoticeStatusEnum}
   * @memberof Notice
   */
  noticeStatus: NoticeNoticeStatusEnum;
  /**
   * 当前查看用户是否已读�?     * @type {boolean}
   * @memberof Notice
   */
  isRead: boolean;
  /**
   * 当前查看用户已读时间�?     * @type {Date}
   * @memberof Notice
   */
  readAt?: Date | null;
  /**
   * 当前规则下可接收该通知的用户数�?     * @type {number}
   * @memberof Notice
   */
  audienceCount?: number | null;
  /**
   * 已读人数�?     * @type {number}
   * @memberof Notice
   */
  readCount: number;
}

/**
 * @export
 */
export const NoticeTargetTypeEnum = {
  School: "school",
  Club: "club",
  Department: "department",
  Member: "member",
} as const;
export type NoticeTargetTypeEnum = (typeof NoticeTargetTypeEnum)[keyof typeof NoticeTargetTypeEnum];

/**
 * @export
 */
export const NoticeNoticeStatusEnum = {
  Draft: "draft",
  Published: "published",
  Expired: "expired",
} as const;
export type NoticeNoticeStatusEnum =
  (typeof NoticeNoticeStatusEnum)[keyof typeof NoticeNoticeStatusEnum];

/**
 * Check if a given object implements the Notice interface.
 */
export function instanceOfNotice(value: object): value is Notice {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("publisherUserId" in value) || value["publisherUserId"] === undefined) return false;
  if (!("noticeType" in value) || value["noticeType"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("content" in value) || value["content"] === undefined) return false;
  if (!("targetType" in value) || value["targetType"] === undefined) return false;
  if (!("publishAt" in value) || value["publishAt"] === undefined) return false;
  if (!("noticeStatus" in value) || value["noticeStatus"] === undefined) return false;
  if (!("isRead" in value) || value["isRead"] === undefined) return false;
  if (!("readCount" in value) || value["readCount"] === undefined) return false;
  return true;
}

export function NoticeFromJSON(json: any): Notice {
  return NoticeFromJSONTyped(json, false);
}

export function NoticeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notice {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    clubId: json["clubId"] == null ? undefined : json["clubId"],
    clubName: json["clubName"] == null ? undefined : json["clubName"],
    publisherUserId: json["publisherUserId"],
    publisherName: json["publisherName"] == null ? undefined : json["publisherName"],
    noticeType: json["noticeType"],
    title: json["title"],
    content: json["content"],
    targetType: json["targetType"],
    targetId: json["targetId"] == null ? undefined : json["targetId"],
    targetName: json["targetName"] == null ? undefined : json["targetName"],
    publishAt: new Date(json["publishAt"]),
    expireAt: json["expireAt"] == null ? undefined : new Date(json["expireAt"]),
    noticeStatus: json["noticeStatus"],
    isRead: json["isRead"],
    readAt: json["readAt"] == null ? undefined : new Date(json["readAt"]),
    audienceCount: json["audienceCount"] == null ? undefined : json["audienceCount"],
    readCount: json["readCount"],
  };
}

export function NoticeToJSON(json: any): Notice {
  return NoticeToJSONTyped(json, false);
}

export function NoticeToJSONTyped(
  value?: Notice | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    clubId: value["clubId"],
    clubName: value["clubName"],
    publisherUserId: value["publisherUserId"],
    publisherName: value["publisherName"],
    noticeType: value["noticeType"],
    title: value["title"],
    content: value["content"],
    targetType: value["targetType"],
    targetId: value["targetId"],
    targetName: value["targetName"],
    publishAt: value["publishAt"].toISOString(),
    expireAt: value["expireAt"] == null ? value["expireAt"] : value["expireAt"].toISOString(),
    noticeStatus: value["noticeStatus"],
    isRead: value["isRead"],
    readAt: value["readAt"] == null ? value["readAt"] : value["readAt"].toISOString(),
    audienceCount: value["audienceCount"],
    readCount: value["readCount"],
  };
}
