// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 权限目录项。
 * @export
 * @interface PermissionDefinition
 */
export interface PermissionDefinition {
    /**
     * 权限编码。
     * @type {string}
     * @memberof PermissionDefinition
     */
    code: string;
    /**
     * 权限展示名称。
     * @type {string}
     * @memberof PermissionDefinition
     */
    name: string;
    /**
     * 权限说明。
     * @type {string}
     * @memberof PermissionDefinition
     */
    description: string;
}

/**
 * Check if a given object implements the PermissionDefinition interface.
 */
export function instanceOfPermissionDefinition(value: object): value is PermissionDefinition {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PermissionDefinitionFromJSON(json: any): PermissionDefinition {
    return PermissionDefinitionFromJSONTyped(json, false);
}

export function PermissionDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function PermissionDefinitionToJSON(json: any): PermissionDefinition {
    return PermissionDefinitionToJSONTyped(json, false);
}

export function PermissionDefinitionToJSONTyped(value?: PermissionDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
    };
}


