// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ProjectTaskAssignee } from "./ProjectTaskAssignee";
import {
  ProjectTaskAssigneeFromJSON,
  ProjectTaskAssigneeFromJSONTyped,
  ProjectTaskAssigneeToJSON,
  ProjectTaskAssigneeToJSONTyped,
} from "./ProjectTaskAssignee";

/**
 * 项目任务及执行进度。
 * @export
 * @interface ProjectTask
 */
export interface ProjectTask {
  /**
   * 项目任务 ID。
   * @type {number}
   * @memberof ProjectTask
   */
  id: number;
  /**
   * 所属项目 ID。
   * @type {number}
   * @memberof ProjectTask
   */
  projectId: number;
  /**
   * 任务执行人列表；每位执行人都必须正在参与该项目。
   * @type {Array<ProjectTaskAssignee>}
   * @memberof ProjectTask
   */
  assignees: Array<ProjectTaskAssignee>;
  /**
   * 任务标题。
   * @type {string}
   * @memberof ProjectTask
   */
  title: string;
  /**
   * 任务详细内容。
   * @type {string}
   * @memberof ProjectTask
   */
  content?: string | null;
  /**
   * 任务优先级。
   * @type {ProjectTaskPriorityEnum}
   * @memberof ProjectTask
   */
  priority: ProjectTaskPriorityEnum;
  /**
   * 任务创建或开始时间。
   * @type {Date}
   * @memberof ProjectTask
   */
  startDate: Date;
  /**
   * 任务截止时间。
   * @type {Date}
   * @memberof ProjectTask
   */
  dueDate: Date;
  /**
   * 任务完成时间；未完成时为空。
   * @type {Date}
   * @memberof ProjectTask
   */
  finishDate?: Date | null;
  /**
   * 完成进度百分比。
   * @type {number}
   * @memberof ProjectTask
   */
  progress: number;
  /**
   * 任务状态。
   * @type {ProjectTaskTaskStatusEnum}
   * @memberof ProjectTask
   */
  taskStatus: ProjectTaskTaskStatusEnum;
  /**
   * 延期原因；延期或逾期未完成时必填。
   * @type {string}
   * @memberof ProjectTask
   */
  delayReason?: string | null;
  /**
   * 已提交成果标题。
   * @type {string}
   * @memberof ProjectTask
   */
  deliverableTitle?: string | null;
  /**
   * 已提交成果说明。
   * @type {string}
   * @memberof ProjectTask
   */
  deliverableDesc?: string | null;
  /**
   * 已提交成果链接，仅允许 HTTP 或 HTTPS 地址。
   * @type {string}
   * @memberof ProjectTask
   */
  deliverableUrl?: string | null;
  /**
   * 成果审核状态。
   * @type {ProjectTaskDeliverableStatusEnum}
   * @memberof ProjectTask
   */
  deliverableStatus: ProjectTaskDeliverableStatusEnum;
  /**
   * 审核人用户 ID。
   * @type {number}
   * @memberof ProjectTask
   */
  reviewerUserId?: number | null;
  /**
   * 审核人姓名和学号/工号展示。
   * @type {string}
   * @memberof ProjectTask
   */
  reviewerDisplayName?: string | null;
  /**
   * 审核意见。
   * @type {string}
   * @memberof ProjectTask
   */
  reviewComment?: string | null;
  /**
   * 成果提交人用户 ID。
   * @type {number}
   * @memberof ProjectTask
   */
  deliverableSubmitterId?: number | null;
  /**
   * 成果提交人姓名和学号/工号展示。
   * @type {string}
   * @memberof ProjectTask
   */
  deliverableSubmitterDisplayName?: string | null;
  /**
   * 成果提交时间。
   * @type {Date}
   * @memberof ProjectTask
   */
  deliverableSubmittedAt?: Date | null;
  /**
   * 成果审核时间。
   * @type {Date}
   * @memberof ProjectTask
   */
  deliverableReviewedAt?: Date | null;
}

/**
 * @export
 */
export const ProjectTaskPriorityEnum = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Urgent: "urgent",
} as const;
export type ProjectTaskPriorityEnum =
  (typeof ProjectTaskPriorityEnum)[keyof typeof ProjectTaskPriorityEnum];

/**
 * @export
 */
export const ProjectTaskTaskStatusEnum = {
  Pending: "pending",
  InProgress: "in_progress",
  Completed: "completed",
  Delayed: "delayed",
} as const;
export type ProjectTaskTaskStatusEnum =
  (typeof ProjectTaskTaskStatusEnum)[keyof typeof ProjectTaskTaskStatusEnum];

/**
 * @export
 */
export const ProjectTaskDeliverableStatusEnum = {
  NotSubmitted: "not_submitted",
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
} as const;
export type ProjectTaskDeliverableStatusEnum =
  (typeof ProjectTaskDeliverableStatusEnum)[keyof typeof ProjectTaskDeliverableStatusEnum];

/**
 * Check if a given object implements the ProjectTask interface.
 */
export function instanceOfProjectTask(value: object): value is ProjectTask {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("projectId" in value) || value["projectId"] === undefined) return false;
  if (!("assignees" in value) || value["assignees"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("priority" in value) || value["priority"] === undefined) return false;
  if (!("startDate" in value) || value["startDate"] === undefined) return false;
  if (!("dueDate" in value) || value["dueDate"] === undefined) return false;
  if (!("progress" in value) || value["progress"] === undefined) return false;
  if (!("taskStatus" in value) || value["taskStatus"] === undefined) return false;
  if (!("deliverableStatus" in value) || value["deliverableStatus"] === undefined) return false;
  return true;
}

export function ProjectTaskFromJSON(json: any): ProjectTask {
  return ProjectTaskFromJSONTyped(json, false);
}

export function ProjectTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectTask {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    projectId: json["projectId"],
    assignees: (json["assignees"] as Array<any>).map(ProjectTaskAssigneeFromJSON),
    title: json["title"],
    content:
      json["content"] === undefined ? undefined : json["content"] === null ? null : json["content"],
    priority: json["priority"],
    startDate: new Date(json["startDate"]),
    dueDate: new Date(json["dueDate"]),
    finishDate:
      json["finishDate"] === undefined
        ? undefined
        : json["finishDate"] === null
          ? null
          : new Date(json["finishDate"]),
    progress: json["progress"],
    taskStatus: json["taskStatus"],
    delayReason:
      json["delayReason"] === undefined
        ? undefined
        : json["delayReason"] === null
          ? null
          : json["delayReason"],
    deliverableTitle:
      json["deliverableTitle"] === undefined
        ? undefined
        : json["deliverableTitle"] === null
          ? null
          : json["deliverableTitle"],
    deliverableDesc:
      json["deliverableDesc"] === undefined
        ? undefined
        : json["deliverableDesc"] === null
          ? null
          : json["deliverableDesc"],
    deliverableUrl:
      json["deliverableUrl"] === undefined
        ? undefined
        : json["deliverableUrl"] === null
          ? null
          : json["deliverableUrl"],
    deliverableStatus: json["deliverableStatus"],
    reviewerUserId:
      json["reviewerUserId"] === undefined
        ? undefined
        : json["reviewerUserId"] === null
          ? null
          : json["reviewerUserId"],
    reviewerDisplayName:
      json["reviewerDisplayName"] === undefined
        ? undefined
        : json["reviewerDisplayName"] === null
          ? null
          : json["reviewerDisplayName"],
    reviewComment:
      json["reviewComment"] === undefined
        ? undefined
        : json["reviewComment"] === null
          ? null
          : json["reviewComment"],
    deliverableSubmitterId:
      json["deliverableSubmitterId"] === undefined
        ? undefined
        : json["deliverableSubmitterId"] === null
          ? null
          : json["deliverableSubmitterId"],
    deliverableSubmitterDisplayName:
      json["deliverableSubmitterDisplayName"] === undefined
        ? undefined
        : json["deliverableSubmitterDisplayName"] === null
          ? null
          : json["deliverableSubmitterDisplayName"],
    deliverableSubmittedAt:
      json["deliverableSubmittedAt"] === undefined
        ? undefined
        : json["deliverableSubmittedAt"] === null
          ? null
          : new Date(json["deliverableSubmittedAt"]),
    deliverableReviewedAt:
      json["deliverableReviewedAt"] === undefined
        ? undefined
        : json["deliverableReviewedAt"] === null
          ? null
          : new Date(json["deliverableReviewedAt"]),
  };
}

export function ProjectTaskToJSON(json: any): ProjectTask {
  return ProjectTaskToJSONTyped(json, false);
}

export function ProjectTaskToJSONTyped(
  value?: ProjectTask | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    projectId: value["projectId"],
    assignees: (value["assignees"] as Array<any>).map(ProjectTaskAssigneeToJSON),
    title: value["title"],
    content: value["content"],
    priority: value["priority"],
    startDate: value["startDate"].toISOString(),
    dueDate: value["dueDate"].toISOString(),
    finishDate:
      value["finishDate"] == null ? value["finishDate"] : value["finishDate"].toISOString(),
    progress: value["progress"],
    taskStatus: value["taskStatus"],
    delayReason: value["delayReason"],
    deliverableTitle: value["deliverableTitle"],
    deliverableDesc: value["deliverableDesc"],
    deliverableUrl: value["deliverableUrl"],
    deliverableStatus: value["deliverableStatus"],
    reviewerUserId: value["reviewerUserId"],
    reviewerDisplayName: value["reviewerDisplayName"],
    reviewComment: value["reviewComment"],
    deliverableSubmitterId: value["deliverableSubmitterId"],
    deliverableSubmitterDisplayName: value["deliverableSubmitterDisplayName"],
    deliverableSubmittedAt:
      value["deliverableSubmittedAt"] == null
        ? value["deliverableSubmittedAt"]
        : value["deliverableSubmittedAt"].toISOString(),
    deliverableReviewedAt:
      value["deliverableReviewedAt"] == null
        ? value["deliverableReviewedAt"]
        : value["deliverableReviewedAt"].toISOString(),
  };
}
