// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RecruitmentApplication
 */
export interface RecruitmentApplication {
  /**
   * 鎷涘嫙鎶ュ悕鐢宠 ID銆?     * @type {number}
   * @memberof RecruitmentApplication
   */
  id: number;
  /**
   * 鎵€灞炴嫑鍕?ID銆?     * @type {number}
   * @memberof RecruitmentApplication
   */
  recruitId: number;
  /**
   * 鎵€灞炴嫑鍕熸爣棰樸€?     * @type {string}
   * @memberof RecruitmentApplication
   */
  recruitTitle: string;
  /**
   * 鎵€灞炵ぞ鍥?ID銆?     * @type {number}
   * @memberof RecruitmentApplication
   */
  clubId: number;
  /**
   * 鎵€灞炵ぞ鍥㈠悕绉般€?     * @type {string}
   * @memberof RecruitmentApplication
   */
  clubName: string;
  /**
   * 鐢宠浜虹敤鎴?ID銆?     * @type {number}
   * @memberof RecruitmentApplication
   */
  userId: number;
  /**
   * 鐢宠浜哄睍绀哄鍚嶃€?     * @type {string}
   * @memberof RecruitmentApplication
   */
  applicantName: string;
  /**
   * 鐢宠浜哄宸ュ彿銆?     * @type {string}
   * @memberof RecruitmentApplication
   */
  studentNo?: string | null;
  /**
   * 鐢宠浜哄～鍐欑殑鍏ョぞ鐞嗙敱銆?     * @type {string}
   * @memberof RecruitmentApplication
   */
  applicationReason: string;
  /**
   * 闈㈣瘯鎴栫瓫閫夎瘎鍒嗭紝0 鍒?100锛涙湭璇勫垎鏃朵负绌恒€?     * @type {number}
   * @memberof RecruitmentApplication
   */
  interviewScore?: number | null;
  /**
   * 鎶ュ悕鐢宠绛涢€夌姸鎬併€?     * @type {RecruitmentApplicationApplicationStatusEnum}
   * @memberof RecruitmentApplication
   */
  applicationStatus: RecruitmentApplicationApplicationStatusEnum;
  /**
   * 鎶ュ悕鐢宠绛涢€夌姸鎬佺殑涓枃鏂囨銆?     * @type {string}
   * @memberof RecruitmentApplication
   */
  applicationStatusText: string;
  /**
   * 瀹℃牳/绛涢€変汉鐢ㄦ埛 ID锛涙湭澶勭悊鏃朵负绌恒€?     * @type {number}
   * @memberof RecruitmentApplication
   */
  reviewerUserId?: number | null;
  /**
   * 瀹℃牳/绛涢€変汉灞曠ず濮撳悕锛涙湭澶勭悊鏃朵负绌恒€?     * @type {string}
   * @memberof RecruitmentApplication
   */
  reviewerName?: string | null;
  /**
   * 鎶ュ悕鎻愪氦鏃堕棿銆?     * @type {Date}
   * @memberof RecruitmentApplication
   */
  submittedAt?: Date | null;
  /**
   * 鎶ュ悕绛涢€夊鐞嗘椂闂达紱鏈鐞嗘椂涓虹┖銆?     * @type {Date}
   * @memberof RecruitmentApplication
   */
  reviewedAt?: Date | null;
}

/**
 * @export
 */
export const RecruitmentApplicationApplicationStatusEnum = {
  Pending: "pending",
  Accepted: "accepted",
  Rejected: "rejected",
} as const;
export type RecruitmentApplicationApplicationStatusEnum =
  (typeof RecruitmentApplicationApplicationStatusEnum)[keyof typeof RecruitmentApplicationApplicationStatusEnum];

/**
 * Check if a given object implements the RecruitmentApplication interface.
 */
export function instanceOfRecruitmentApplication(value: object): value is RecruitmentApplication {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("recruitId" in value) || value["recruitId"] === undefined) return false;
  if (!("recruitTitle" in value) || value["recruitTitle"] === undefined) return false;
  if (!("clubId" in value) || value["clubId"] === undefined) return false;
  if (!("clubName" in value) || value["clubName"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("applicantName" in value) || value["applicantName"] === undefined) return false;
  if (!("applicationReason" in value) || value["applicationReason"] === undefined) return false;
  if (!("applicationStatus" in value) || value["applicationStatus"] === undefined) return false;
  if (!("applicationStatusText" in value) || value["applicationStatusText"] === undefined)
    return false;
  return true;
}

export function RecruitmentApplicationFromJSON(json: any): RecruitmentApplication {
  return RecruitmentApplicationFromJSONTyped(json, false);
}

export function RecruitmentApplicationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecruitmentApplication {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    recruitId: json["recruitId"],
    recruitTitle: json["recruitTitle"],
    clubId: json["clubId"],
    clubName: json["clubName"],
    userId: json["userId"],
    applicantName: json["applicantName"],
    studentNo: json["studentNo"] == null ? undefined : json["studentNo"],
    applicationReason: json["applicationReason"],
    interviewScore: json["interviewScore"] == null ? undefined : json["interviewScore"],
    applicationStatus: json["applicationStatus"],
    applicationStatusText: json["applicationStatusText"],
    reviewerUserId: json["reviewerUserId"] == null ? undefined : json["reviewerUserId"],
    reviewerName: json["reviewerName"] == null ? undefined : json["reviewerName"],
    submittedAt: json["submittedAt"] == null ? undefined : new Date(json["submittedAt"]),
    reviewedAt: json["reviewedAt"] == null ? undefined : new Date(json["reviewedAt"]),
  };
}

export function RecruitmentApplicationToJSON(json: any): RecruitmentApplication {
  return RecruitmentApplicationToJSONTyped(json, false);
}

export function RecruitmentApplicationToJSONTyped(
  value?: RecruitmentApplication | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    recruitId: value["recruitId"],
    recruitTitle: value["recruitTitle"],
    clubId: value["clubId"],
    clubName: value["clubName"],
    userId: value["userId"],
    applicantName: value["applicantName"],
    studentNo: value["studentNo"],
    applicationReason: value["applicationReason"],
    interviewScore: value["interviewScore"],
    applicationStatus: value["applicationStatus"],
    applicationStatusText: value["applicationStatusText"],
    reviewerUserId: value["reviewerUserId"],
    reviewerName: value["reviewerName"],
    submittedAt:
      value["submittedAt"] == null ? value["submittedAt"] : value["submittedAt"].toISOString(),
    reviewedAt:
      value["reviewedAt"] == null ? value["reviewedAt"] : value["reviewedAt"].toISOString(),
  };
}
