// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 绾虫柊鑽夌鍙紪杈戞祦绋嬬姸鎬併€? * @export
 */
export const RecruitmentWorkflowStatus = {
  Draft: "draft",
  PendingReview: "pending_review",
} as const;
export type RecruitmentWorkflowStatus =
  (typeof RecruitmentWorkflowStatus)[keyof typeof RecruitmentWorkflowStatus];

export function instanceOfRecruitmentWorkflowStatus(value: any): boolean {
  for (const key in RecruitmentWorkflowStatus) {
    if (Object.prototype.hasOwnProperty.call(RecruitmentWorkflowStatus, key)) {
      if (RecruitmentWorkflowStatus[key as keyof typeof RecruitmentWorkflowStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function RecruitmentWorkflowStatusFromJSON(json: any): RecruitmentWorkflowStatus {
  return RecruitmentWorkflowStatusFromJSONTyped(json, false);
}

export function RecruitmentWorkflowStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecruitmentWorkflowStatus {
  return json as RecruitmentWorkflowStatus;
}

export function RecruitmentWorkflowStatusToJSON(value?: RecruitmentWorkflowStatus | null): any {
  return value as any;
}

export function RecruitmentWorkflowStatusToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): RecruitmentWorkflowStatus {
  return value as RecruitmentWorkflowStatus;
}
