// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 用户注册请求。学生学工号为 7 位数字，教师工号为 5 位数字。
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
  /**
   * 登录用户名，注册后必须唯一。
   * @type {string}
   * @memberof RegisterRequest
   */
  username: string;
  /**
   * 登录密码，服务端仅保存密码摘要。
   * @type {string}
   * @memberof RegisterRequest
   */
  password: string;
  /**
   * 用户真实姓名。
   * @type {string}
   * @memberof RegisterRequest
   */
  realName: string;
  /**
   * 学工号；学生 7 位，教师 5 位。
   * @type {string}
   * @memberof RegisterRequest
   */
  studentNo: string;
  /**
   * 性别，可为空；当前支持男、女。
   * @type {string}
   * @memberof RegisterRequest
   */
  gender?: string | null;
  /**
   * 联系电话，可为空。
   * @type {string}
   * @memberof RegisterRequest
   */
  phone?: string | null;
  /**
   * 邮箱地址，可为空。
   * @type {string}
   * @memberof RegisterRequest
   */
  email?: string | null;
  /**
   * 所属学院，可为空。
   * @type {string}
   * @memberof RegisterRequest
   */
  college?: string | null;
  /**
   * 所属专业，可为空。
   * @type {string}
   * @memberof RegisterRequest
   */
  major?: string | null;
  /**
   * 年级，可为空。
   * @type {string}
   * @memberof RegisterRequest
   */
  grade?: string | null;
}

/**
 * Check if a given object implements the RegisterRequest interface.
 */
export function instanceOfRegisterRequest(value: object): value is RegisterRequest {
  if (!("username" in value) || value["username"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  if (!("realName" in value) || value["realName"] === undefined) return false;
  if (!("studentNo" in value) || value["studentNo"] === undefined) return false;
  return true;
}

export function RegisterRequestFromJSON(json: any): RegisterRequest {
  return RegisterRequestFromJSONTyped(json, false);
}

export function RegisterRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterRequest {
  if (json == null) {
    return json;
  }
  return {
    username: json["username"],
    password: json["password"],
    realName: json["realName"],
    studentNo: json["studentNo"],
    gender: json["gender"] == null ? undefined : json["gender"],
    phone: json["phone"] == null ? undefined : json["phone"],
    email: json["email"] == null ? undefined : json["email"],
    college: json["college"] == null ? undefined : json["college"],
    major: json["major"] == null ? undefined : json["major"],
    grade: json["grade"] == null ? undefined : json["grade"],
  };
}

export function RegisterRequestToJSON(json: any): RegisterRequest {
  return RegisterRequestToJSONTyped(json, false);
}

export function RegisterRequestToJSONTyped(
  value?: RegisterRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    username: value["username"],
    password: value["password"],
    realName: value["realName"],
    studentNo: value["studentNo"],
    gender: value["gender"],
    phone: value["phone"],
    email: value["email"],
    college: value["college"],
    major: value["major"],
    grade: value["grade"],
  };
}
