// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RegisterActivityRequest
 */
export interface RegisterActivityRequest {
  /**
   * 鎶ュ悕鐢ㄦ埛 ID
   * @type {number}
   * @memberof RegisterActivityRequest
   */
  userId: number;
}

/**
 * Check if a given object implements the RegisterActivityRequest interface.
 */
export function instanceOfRegisterActivityRequest(value: object): value is RegisterActivityRequest {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  return true;
}

export function RegisterActivityRequestFromJSON(json: any): RegisterActivityRequest {
  return RegisterActivityRequestFromJSONTyped(json, false);
}

export function RegisterActivityRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterActivityRequest {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"],
  };
}

export function RegisterActivityRequestToJSON(json: any): RegisterActivityRequest {
  return RegisterActivityRequestToJSONTyped(json, false);
}

export function RegisterActivityRequestToJSONTyped(
  value?: RegisterActivityRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
  };
}
