// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Request to complete an active borrow as damaged and record compensation.
 * @export
 * @interface RegisterMaterialDamageRequest
 */
export interface RegisterMaterialDamageRequest {
  /**
   * Required description of the observed damage.
   * @type {string}
   * @memberof RegisterMaterialDamageRequest
   */
  damageDescription: string;
  /**
   * Non-negative compensation amount in CNY.
   * @type {number}
   * @memberof RegisterMaterialDamageRequest
   */
  compensationAmount: number;
}

/**
 * Check if a given object implements the RegisterMaterialDamageRequest interface.
 */
export function instanceOfRegisterMaterialDamageRequest(
  value: object,
): value is RegisterMaterialDamageRequest {
  if (!("damageDescription" in value) || value["damageDescription"] === undefined) return false;
  if (!("compensationAmount" in value) || value["compensationAmount"] === undefined) return false;
  return true;
}

export function RegisterMaterialDamageRequestFromJSON(json: any): RegisterMaterialDamageRequest {
  return RegisterMaterialDamageRequestFromJSONTyped(json, false);
}

export function RegisterMaterialDamageRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterMaterialDamageRequest {
  if (json == null) {
    return json;
  }
  return {
    damageDescription: json["damageDescription"],
    compensationAmount: json["compensationAmount"],
  };
}

export function RegisterMaterialDamageRequestToJSON(json: any): RegisterMaterialDamageRequest {
  return RegisterMaterialDamageRequestToJSONTyped(json, false);
}

export function RegisterMaterialDamageRequestToJSONTyped(
  value?: RegisterMaterialDamageRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    damageDescription: value["damageDescription"],
    compensationAmount: value["compensationAmount"],
  };
}
