// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 重新提交被驳回经费申请的请求，所有字段均为可选，仅更新传入的字段。
 * @export
 * @interface ResubmitBudgetApplicationRequest
 */
export interface ResubmitBudgetApplicationRequest {
  /**
   * 关联活动，可不填。
   * @type {number}
   * @memberof ResubmitBudgetApplicationRequest
   */
  activityId?: number | null;
  /**
   * 申请类型。
   * @type {string}
   * @memberof ResubmitBudgetApplicationRequest
   */
  type?: string;
  /**
   * 经费申请标题。
   * @type {string}
   * @memberof ResubmitBudgetApplicationRequest
   */
  title?: string;
  /**
   * 申请金额，必须大于 0。
   * @type {number}
   * @memberof ResubmitBudgetApplicationRequest
   */
  amount?: number;
  /**
   * 经费用途。
   * @type {string}
   * @memberof ResubmitBudgetApplicationRequest
   */
  purpose?: string;
  /**
   * 经费明细说明。
   * @type {string}
   * @memberof ResubmitBudgetApplicationRequest
   */
  detail?: string | null;
}

/**
 * Check if a given object implements the ResubmitBudgetApplicationRequest interface.
 */
export function instanceOfResubmitBudgetApplicationRequest(
  value: object,
): value is ResubmitBudgetApplicationRequest {
  return true;
}

export function ResubmitBudgetApplicationRequestFromJSON(json: any): ResubmitBudgetApplicationRequest {
  return ResubmitBudgetApplicationRequestFromJSONTyped(json, false);
}

export function ResubmitBudgetApplicationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResubmitBudgetApplicationRequest {
  if (json == null) {
    return json;
  }
  return {
    activityId:
      json["activityId"] === undefined ? undefined : json["activityId"] === null ? null : json["activityId"],
    type: json["type"] === undefined ? undefined : json["type"],
    title: json["title"] === undefined ? undefined : json["title"],
    amount: json["amount"] === undefined ? undefined : json["amount"],
    purpose: json["purpose"] === undefined ? undefined : json["purpose"],
    detail:
      json["detail"] === undefined ? undefined : json["detail"] === null ? null : json["detail"],
  };
}

export function ResubmitBudgetApplicationRequestToJSON(json: any): ResubmitBudgetApplicationRequest {
  return ResubmitBudgetApplicationRequestToJSONTyped(json, false);
}

export function ResubmitBudgetApplicationRequestToJSONTyped(
  value?: ResubmitBudgetApplicationRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    activityId: value["activityId"],
    type: value["type"],
    title: value["title"],
    amount: value["amount"],
    purpose: value["purpose"],
    detail: value["detail"],
  };
}
