// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 提交项目任务成果的请求；提交人由服务端从 Bearer 令牌解析。
 * @export
 * @interface SubmitProjectTaskDeliverableRequest
 */
export interface SubmitProjectTaskDeliverableRequest {
  /**
   * 成果标题。
   * @type {string}
   * @memberof SubmitProjectTaskDeliverableRequest
   */
  deliverableTitle: string;
  /**
   * 成果说明。
   * @type {string}
   * @memberof SubmitProjectTaskDeliverableRequest
   */
  deliverableDesc?: string | null;
  /**
   * 成果链接，仅允许 HTTP 或 HTTPS 地址。
   * @type {string}
   * @memberof SubmitProjectTaskDeliverableRequest
   */
  deliverableUrl?: string | null;
}

/**
 * Check if a given object implements the SubmitProjectTaskDeliverableRequest interface.
 */
export function instanceOfSubmitProjectTaskDeliverableRequest(
  value: object,
): value is SubmitProjectTaskDeliverableRequest {
  if (!("deliverableTitle" in value) || value["deliverableTitle"] === undefined) return false;
  return true;
}

export function SubmitProjectTaskDeliverableRequestFromJSON(
  json: any,
): SubmitProjectTaskDeliverableRequest {
  return SubmitProjectTaskDeliverableRequestFromJSONTyped(json, false);
}

export function SubmitProjectTaskDeliverableRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubmitProjectTaskDeliverableRequest {
  if (json == null) {
    return json;
  }
  return {
    deliverableTitle: json["deliverableTitle"],
    deliverableDesc:
      json["deliverableDesc"] === undefined
        ? undefined
        : json["deliverableDesc"] === null
          ? null
          : json["deliverableDesc"],
    deliverableUrl:
      json["deliverableUrl"] === undefined
        ? undefined
        : json["deliverableUrl"] === null
          ? null
          : json["deliverableUrl"],
  };
}

export function SubmitProjectTaskDeliverableRequestToJSON(
  json: any,
): SubmitProjectTaskDeliverableRequest {
  return SubmitProjectTaskDeliverableRequestToJSONTyped(json, false);
}

export function SubmitProjectTaskDeliverableRequestToJSONTyped(
  value?: SubmitProjectTaskDeliverableRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    deliverableTitle: value["deliverableTitle"],
    deliverableDesc: value["deliverableDesc"],
    deliverableUrl: value["deliverableUrl"],
  };
}
