// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateClubRequest
 */
export interface UpdateClubRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateClubRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClubRequest
   */
  category?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClubRequest
   */
  description?: string | null;
}

/**
 * Check if a given object implements the UpdateClubRequest interface.
 */
export function instanceOfUpdateClubRequest(value: object): value is UpdateClubRequest {
  return true;
}

export function UpdateClubRequestFromJSON(json: any): UpdateClubRequest {
  return UpdateClubRequestFromJSONTyped(json, false);
}

export function UpdateClubRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateClubRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    category: json["category"] == null ? undefined : json["category"],
    description: json["description"] == null ? undefined : json["description"],
  };
}

export function UpdateClubRequestToJSON(json: any): UpdateClubRequest {
  return UpdateClubRequestToJSONTyped(json, false);
}

export function UpdateClubRequestToJSONTyped(
  value?: UpdateClubRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    category: value["category"],
    description: value["description"],
  };
}
