// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 更新课程或学习资源的请求。
 * @export
 * @interface UpdateLearningItemRequest
 */
export interface UpdateLearningItemRequest {
  /**
   * 课程或资源标题。
   * @type {string}
   * @memberof UpdateLearningItemRequest
   */
  title: string;
  /**
   * 课程或资源说明。
   * @type {string}
   * @memberof UpdateLearningItemRequest
   */
  description?: string | null;
  /**
   * 可选的课程授课人，可以是教师或学生；非课程资源可为空。
   * @type {number}
   * @memberof UpdateLearningItemRequest
   */
  instructorUserId?: number | null;
  /**
   * 支持 course、lecture、training、video、document、material。
   * @type {string}
   * @memberof UpdateLearningItemRequest
   */
  itemType: string;
  /**
   * 资源分类。
   * @type {string}
   * @memberof UpdateLearningItemRequest
   */
  categoryName?: string | null;
  /**
   * 视频、文档或资料的 HTTP/HTTPS 文件地址。
   * @type {string}
   * @memberof UpdateLearningItemRequest
   */
  fileUrl?: string | null;
  /**
   * 课程开始时间。
   * @type {Date}
   * @memberof UpdateLearningItemRequest
   */
  startAt?: Date | null;
  /**
   * 课程结束时间。
   * @type {Date}
   * @memberof UpdateLearningItemRequest
   */
  endAt?: Date | null;
  /**
   * 课程容量。
   * @type {number}
   * @memberof UpdateLearningItemRequest
   */
  capacity?: number | null;
  /**
   * 公开、社团内或上传人所在部门内可见。
   * @type {UpdateLearningItemRequestVisibilityEnum}
   * @memberof UpdateLearningItemRequest
   */
  visibility: UpdateLearningItemRequestVisibilityEnum;
  /**
   * 下载设置。
   * @type {UpdateLearningItemRequestDownloadPermissionEnum}
   * @memberof UpdateLearningItemRequest
   */
  downloadPermission: UpdateLearningItemRequestDownloadPermissionEnum;
  /**
   * 更新后的发布状态。
   * @type {UpdateLearningItemRequestItemStatusEnum}
   * @memberof UpdateLearningItemRequest
   */
  itemStatus: UpdateLearningItemRequestItemStatusEnum;
}

/**
 * @export
 */
export const UpdateLearningItemRequestVisibilityEnum = {
  Public: "public",
  Club: "club",
  Department: "department",
} as const;
export type UpdateLearningItemRequestVisibilityEnum =
  (typeof UpdateLearningItemRequestVisibilityEnum)[keyof typeof UpdateLearningItemRequestVisibilityEnum];

/**
 * @export
 */
export const UpdateLearningItemRequestDownloadPermissionEnum = {
  Allow: "allow",
  Deny: "deny",
  Approval: "approval",
} as const;
export type UpdateLearningItemRequestDownloadPermissionEnum =
  (typeof UpdateLearningItemRequestDownloadPermissionEnum)[keyof typeof UpdateLearningItemRequestDownloadPermissionEnum];

/**
 * @export
 */
export const UpdateLearningItemRequestItemStatusEnum = {
  Draft: "draft",
  Published: "published",
  Closed: "closed",
} as const;
export type UpdateLearningItemRequestItemStatusEnum =
  (typeof UpdateLearningItemRequestItemStatusEnum)[keyof typeof UpdateLearningItemRequestItemStatusEnum];

/**
 * Check if a given object implements the UpdateLearningItemRequest interface.
 */
export function instanceOfUpdateLearningItemRequest(
  value: object,
): value is UpdateLearningItemRequest {
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("itemType" in value) || value["itemType"] === undefined) return false;
  if (!("visibility" in value) || value["visibility"] === undefined) return false;
  if (!("downloadPermission" in value) || value["downloadPermission"] === undefined) return false;
  if (!("itemStatus" in value) || value["itemStatus"] === undefined) return false;
  return true;
}

export function UpdateLearningItemRequestFromJSON(json: any): UpdateLearningItemRequest {
  return UpdateLearningItemRequestFromJSONTyped(json, false);
}

export function UpdateLearningItemRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateLearningItemRequest {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"],
    description:
      json["description"] === undefined
        ? undefined
        : json["description"] === null
          ? null
          : json["description"],
    instructorUserId:
      json["instructorUserId"] === undefined
        ? undefined
        : json["instructorUserId"] === null
          ? null
          : json["instructorUserId"],
    itemType: json["itemType"],
    categoryName:
      json["categoryName"] === undefined
        ? undefined
        : json["categoryName"] === null
          ? null
          : json["categoryName"],
    fileUrl:
      json["fileUrl"] === undefined ? undefined : json["fileUrl"] === null ? null : json["fileUrl"],
    startAt:
      json["startAt"] === undefined
        ? undefined
        : json["startAt"] === null
          ? null
          : new Date(json["startAt"]),
    endAt:
      json["endAt"] === undefined
        ? undefined
        : json["endAt"] === null
          ? null
          : new Date(json["endAt"]),
    capacity:
      json["capacity"] === undefined
        ? undefined
        : json["capacity"] === null
          ? null
          : json["capacity"],
    visibility: json["visibility"],
    downloadPermission: json["downloadPermission"],
    itemStatus: json["itemStatus"],
  };
}

export function UpdateLearningItemRequestToJSON(json: any): UpdateLearningItemRequest {
  return UpdateLearningItemRequestToJSONTyped(json, false);
}

export function UpdateLearningItemRequestToJSONTyped(
  value?: UpdateLearningItemRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    description: value["description"],
    instructorUserId: value["instructorUserId"],
    itemType: value["itemType"],
    categoryName: value["categoryName"],
    fileUrl: value["fileUrl"],
    startAt: value["startAt"] == null ? value["startAt"] : value["startAt"].toISOString(),
    endAt: value["endAt"] == null ? value["endAt"] : value["endAt"].toISOString(),
    capacity: value["capacity"],
    visibility: value["visibility"],
    downloadPermission: value["downloadPermission"],
    itemStatus: value["itemStatus"],
  };
}
