// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from "../runtime";
import type { AwardLevelInput } from "./AwardLevelInput";
import {
  AwardLevelInputFromJSON,
  AwardLevelInputFromJSONTyped,
  AwardLevelInputToJSON,
  AwardLevelInputToJSONTyped,
} from "./AwardLevelInput";

/**
 *
 * @export
 * @interface UpdateAwardSchemeRequest
 */
export interface UpdateAwardSchemeRequest {
  /**
   *
   */
  awardName: string;
  /**
   *
   */
  awardCategory: UpdateAwardSchemeRequestAwardCategoryEnum;
  /**
   *
   */
  academicYear: string;
  /**
   *
   */
  termName?: string | null;
  /**
   *
   */
  sponsorUnit?: string | null;
  /**
   *
   */
  rewardLevel?: string | null;
  /**
   *
   */
  fundingSource?: string | null;
  /**
   *
   */
  isRanked?: boolean;
  /**
   *
   */
  isFixedAmount?: boolean;
  /**
   *
   */
  description?: string | null;
  /**
   *
   */
  materialDescription?: string | null;
  /**
   *
   */
  applicationStartAt?: Date | null;
  /**
   *
   */
  applicationEndAt?: Date | null;
  /**
   *
   */
  publicityStartAt?: Date | null;
  /**
   *
   */
  publicityEndAt?: Date | null;
  /**
   *
   */
  schemeStatus?: UpdateAwardSchemeRequestSchemeStatusEnum;
  /**
   *
   */
  levels: Array<AwardLevelInput>;
}

/**
 * @export
 */
export const UpdateAwardSchemeRequestAwardCategoryEnum = {
  Honor: "honor",
  Scholarship: "scholarship",
  Competition: "competition",
  Service: "service",
  Other: "other",
} as const;
export type UpdateAwardSchemeRequestAwardCategoryEnum =
  (typeof UpdateAwardSchemeRequestAwardCategoryEnum)[keyof typeof UpdateAwardSchemeRequestAwardCategoryEnum];

/**
 * @export
 */
export const UpdateAwardSchemeRequestSchemeStatusEnum = {
  Draft: "draft",
  Open: "open",
  Reviewing: "reviewing",
  Publicizing: "publicizing",
  Archived: "archived",
  Closed: "closed",
} as const;
export type UpdateAwardSchemeRequestSchemeStatusEnum =
  (typeof UpdateAwardSchemeRequestSchemeStatusEnum)[keyof typeof UpdateAwardSchemeRequestSchemeStatusEnum];

/**
 * Check if a given object implements the UpdateAwardSchemeRequest interface.
 */
export function instanceOfUpdateAwardSchemeRequest(
  value: object,
): value is UpdateAwardSchemeRequest {
  if (!("awardName" in value) || value["awardName"] === undefined) return false;
  if (!("awardCategory" in value) || value["awardCategory"] === undefined) return false;
  if (!("academicYear" in value) || value["academicYear"] === undefined) return false;
  if (!("levels" in value) || value["levels"] === undefined) return false;
  return true;
}

export function UpdateAwardSchemeRequestFromJSON(json: any): UpdateAwardSchemeRequest {
  return UpdateAwardSchemeRequestFromJSONTyped(json, false);
}

export function UpdateAwardSchemeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateAwardSchemeRequest {
  if (json == null) {
    return json;
  }
  return {
    awardName: json["awardName"],
    awardCategory: json["awardCategory"],
    academicYear: json["academicYear"],
    termName:
      json["termName"] === undefined
        ? undefined
        : json["termName"] === null
          ? null
          : json["termName"],
    sponsorUnit:
      json["sponsorUnit"] === undefined
        ? undefined
        : json["sponsorUnit"] === null
          ? null
          : json["sponsorUnit"],
    rewardLevel:
      json["rewardLevel"] === undefined
        ? undefined
        : json["rewardLevel"] === null
          ? null
          : json["rewardLevel"],
    fundingSource:
      json["fundingSource"] === undefined
        ? undefined
        : json["fundingSource"] === null
          ? null
          : json["fundingSource"],
    isRanked: json["isRanked"] == null ? undefined : json["isRanked"],
    isFixedAmount: json["isFixedAmount"] == null ? undefined : json["isFixedAmount"],
    description:
      json["description"] === undefined
        ? undefined
        : json["description"] === null
          ? null
          : json["description"],
    materialDescription:
      json["materialDescription"] === undefined
        ? undefined
        : json["materialDescription"] === null
          ? null
          : json["materialDescription"],
    applicationStartAt:
      json["applicationStartAt"] === undefined
        ? undefined
        : json["applicationStartAt"] === null
          ? null
          : parseDateTime(json["applicationStartAt"]),
    applicationEndAt:
      json["applicationEndAt"] === undefined
        ? undefined
        : json["applicationEndAt"] === null
          ? null
          : parseDateTime(json["applicationEndAt"]),
    publicityStartAt:
      json["publicityStartAt"] === undefined
        ? undefined
        : json["publicityStartAt"] === null
          ? null
          : parseDateTime(json["publicityStartAt"]),
    publicityEndAt:
      json["publicityEndAt"] === undefined
        ? undefined
        : json["publicityEndAt"] === null
          ? null
          : parseDateTime(json["publicityEndAt"]),
    schemeStatus: json["schemeStatus"] == null ? undefined : json["schemeStatus"],
    levels: (json["levels"] as Array<any>).map(AwardLevelInputFromJSON),
  };
}

export function UpdateAwardSchemeRequestToJSON(json: any): UpdateAwardSchemeRequest {
  return UpdateAwardSchemeRequestToJSONTyped(json, false);
}

export function UpdateAwardSchemeRequestToJSONTyped(
  value?: UpdateAwardSchemeRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    awardName: value["awardName"],
    awardCategory: value["awardCategory"],
    academicYear: value["academicYear"],
    termName: value["termName"],
    sponsorUnit: value["sponsorUnit"],
    rewardLevel: value["rewardLevel"],
    fundingSource: value["fundingSource"],
    isRanked: value["isRanked"],
    isFixedAmount: value["isFixedAmount"],
    description: value["description"],
    materialDescription: value["materialDescription"],
    applicationStartAt:
      value["applicationStartAt"] == null
        ? value["applicationStartAt"]
        : serializeDateTime(value["applicationStartAt"]),
    applicationEndAt:
      value["applicationEndAt"] == null
        ? value["applicationEndAt"]
        : serializeDateTime(value["applicationEndAt"]),
    publicityStartAt:
      value["publicityStartAt"] == null
        ? value["publicityStartAt"]
        : serializeDateTime(value["publicityStartAt"]),
    publicityEndAt:
      value["publicityEndAt"] == null
        ? value["publicityEndAt"]
        : serializeDateTime(value["publicityEndAt"]),
    schemeStatus: value["schemeStatus"],
    levels: (value["levels"] as Array<any>).map(AwardLevelInputToJSON),
  };
}
