// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateMaterialRequest
 */
export interface UpdateMaterialRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMaterialRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMaterialRequest
   */
  specification?: string | null;
  /**
   *
   * @type {number}
   * @memberof UpdateMaterialRequest
   */
  totalQuantity: number;
  /**
   *
   * @type {number}
   * @memberof UpdateMaterialRequest
   */
  availableQuantity: number;
  /**
   *
   * @type {string}
   * @memberof UpdateMaterialRequest
   */
  storageLocation?: string | null;
  /**
   *
   * @type {UpdateMaterialRequestStatusEnum}
   * @memberof UpdateMaterialRequest
   */
  status: UpdateMaterialRequestStatusEnum;
}

/**
 * @export
 */
export const UpdateMaterialRequestStatusEnum = {
  Active: "active",
  Disabled: "disabled",
} as const;
export type UpdateMaterialRequestStatusEnum =
  (typeof UpdateMaterialRequestStatusEnum)[keyof typeof UpdateMaterialRequestStatusEnum];

/**
 * Check if a given object implements the UpdateMaterialRequest interface.
 */
export function instanceOfUpdateMaterialRequest(value: object): value is UpdateMaterialRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("totalQuantity" in value) || value["totalQuantity"] === undefined) return false;
  if (!("availableQuantity" in value) || value["availableQuantity"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  return true;
}

export function UpdateMaterialRequestFromJSON(json: any): UpdateMaterialRequest {
  return UpdateMaterialRequestFromJSONTyped(json, false);
}

export function UpdateMaterialRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateMaterialRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    specification: json["specification"] == null ? undefined : json["specification"],
    totalQuantity: json["totalQuantity"],
    availableQuantity: json["availableQuantity"],
    storageLocation: json["storageLocation"] == null ? undefined : json["storageLocation"],
    status: json["status"],
  };
}

export function UpdateMaterialRequestToJSON(json: any): UpdateMaterialRequest {
  return UpdateMaterialRequestToJSONTyped(json, false);
}

export function UpdateMaterialRequestToJSONTyped(
  value?: UpdateMaterialRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    specification: value["specification"],
    totalQuantity: value["totalQuantity"],
    availableQuantity: value["availableQuantity"],
    storageLocation: value["storageLocation"],
    status: value["status"],
  };
}
