// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * ClubHub API
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateClubProfileRequest
 */
export interface UpdateClubProfileRequest {
  /**
   *
   * @type {number}
   * @memberof UpdateClubProfileRequest
   */
  currentUserId: number;
  /**
   *
   * @type {string}
   * @memberof UpdateClubProfileRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClubProfileRequest
   */
  category: string;
  /**
   *
   * @type {string}
   * @memberof UpdateClubProfileRequest
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateClubProfileRequest
   */
  logoUrl?: string | null;
  /**
   *
   * @type {number}
   * @memberof UpdateClubProfileRequest
   */
  presidentUserId?: number | null;
  /**
   * 鎸囧鑰佸笀鐢ㄦ埛 ID锛涘悗绔細鏍￠獙璇ョ敤鎴蜂负鏁欏笀璐﹀彿锛屽苟缁存姢鏈ぞ鍥?ADVISOR 瑙掕壊鍏崇郴銆?     * @type {number}
   * @memberof UpdateClubProfileRequest
   */
  advisorUserId?: number | null;
  /**
   * 鍘嗗彶鍏煎瀛楁锛涙柊娴佺▼璇蜂娇鐢?advisorUserId銆?     * @type {string}
   * @memberof UpdateClubProfileRequest
   * @deprecated
   */
  advisorName?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateClubProfileRequest
   */
  contactPhone?: string | null;
}

/**
 * Check if a given object implements the UpdateClubProfileRequest interface.
 */
export function instanceOfUpdateClubProfileRequest(
  value: object,
): value is UpdateClubProfileRequest {
  if (!("currentUserId" in value) || value["currentUserId"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("category" in value) || value["category"] === undefined) return false;
  return true;
}

export function UpdateClubProfileRequestFromJSON(json: any): UpdateClubProfileRequest {
  return UpdateClubProfileRequestFromJSONTyped(json, false);
}

export function UpdateClubProfileRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateClubProfileRequest {
  if (json == null) {
    return json;
  }
  return {
    currentUserId: json["currentUserId"],
    name: json["name"],
    category: json["category"],
    description: json["description"] == null ? undefined : json["description"],
    logoUrl: json["logoUrl"] == null ? undefined : json["logoUrl"],
    presidentUserId: json["presidentUserId"] == null ? undefined : json["presidentUserId"],
    advisorUserId: json["advisorUserId"] == null ? undefined : json["advisorUserId"],
    advisorName: json["advisorName"] == null ? undefined : json["advisorName"],
    contactPhone: json["contactPhone"] == null ? undefined : json["contactPhone"],
  };
}

export function UpdateClubProfileRequestToJSON(json: any): UpdateClubProfileRequest {
  return UpdateClubProfileRequestToJSONTyped(json, false);
}

export function UpdateClubProfileRequestToJSONTyped(
  value?: UpdateClubProfileRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentUserId: value["currentUserId"],
    name: value["name"],
    category: value["category"],
    description: value["description"],
    logoUrl: value["logoUrl"],
    presidentUserId: value["presidentUserId"],
    advisorUserId: value["advisorUserId"],
    advisorName: value["advisorName"],
    contactPhone: value["contactPhone"],
  };
}
