-- 为培训课程增加独立的报名截止时间。
-- 本脚本可重复执行；历史记录优先使用课程开始时间回填。

DECLARE
  column_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO column_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'LEARNING_ITEMS'
     AND COLUMN_NAME = 'ENROLL_DEADLINE';

  IF column_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE LEARNING_ITEMS ADD (ENROLL_DEADLINE DATE)';
  END IF;
END;
/

UPDATE LEARNING_ITEMS
   SET ENROLL_DEADLINE = NVL(START_AT, NVL(CREATED_AT, SYSDATE))
 WHERE ENROLL_DEADLINE IS NULL;

ALTER TABLE LEARNING_ITEMS
  MODIFY (ENROLL_DEADLINE NOT NULL);

DECLARE
  constraint_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO constraint_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'LEARNING_ITEMS'
     AND CONSTRAINT_NAME = 'CK_LEARNING_ITEMS_ENROLL_TIME';

  IF constraint_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE LEARNING_ITEMS ADD CONSTRAINT ' ||
      'CK_LEARNING_ITEMS_ENROLL_TIME CHECK ' ||
      '(START_AT IS NULL OR ENROLL_DEADLINE <= START_AT)';
  END IF;
END;
/

COMMIT;
