-- 为培训课程增加独立的报名截止时间。
-- 本脚本可重复执行；历史记录优先使用课程开始时间回填。
-- 影响范围：会全表回填 LEARNING_ITEMS 并执行 ALTER TABLE，可能产生表锁，
--           实际执行时间取决于现有数据量，建议在低峰期执行。
-- 回滚方案：先删除 CK_LEARNING_ITEMS_ENROLL_TIME 约束，再删除 ENROLL_DEADLINE 列。
--           历史记录的回填值来自 START_AT 或当前时间，删除列后无法恢复该回填结果。

DECLARE
  column_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO column_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'LEARNING_ITEMS'
     AND COLUMN_NAME = 'ENROLL_DEADLINE';

  IF column_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE LEARNING_ITEMS ADD (ENROLL_DEADLINE DATE)';
  END IF;
END;
/

UPDATE LEARNING_ITEMS
   SET ENROLL_DEADLINE = NVL(START_AT, NVL(CREATED_AT, SYSDATE))
 WHERE ENROLL_DEADLINE IS NULL;

ALTER TABLE LEARNING_ITEMS
  MODIFY (ENROLL_DEADLINE NOT NULL);

DECLARE
  constraint_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO constraint_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'LEARNING_ITEMS'
     AND CONSTRAINT_NAME = 'CK_LEARNING_ITEMS_ENROLL_TIME';

  IF constraint_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE LEARNING_ITEMS ADD CONSTRAINT ' ||
      'CK_LEARNING_ITEMS_ENROLL_TIME CHECK ' ||
      '(START_AT IS NULL OR ENROLL_DEADLINE <= START_AT)';
  END IF;
END;
/

COMMIT;
