/*
 * ClubHub API
 *
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Request body for assigning or changing a project leader.
    /// </summary>
    [DataContract]
    public partial class AssignProjectLeaderRequest 
    {
        /// <summary>
        /// 褰撳墠鍒嗛厤璐熻矗浜烘搷浣滅敤鎴?ID锛涗粎绯荤粺绠＄悊鍛樸€佹湰绀惧洟璐熻矗浜烘垨骞查儴鍙搷浣溿€?        /// </summary>
        /// <value>褰撳墠鍒嗛厤璐熻矗浜烘搷浣滅敤鎴?ID锛涗粎绯荤粺绠＄悊鍛樸€佹湰绀惧洟璐熻矗浜烘垨骞查儴鍙搷浣溿€?/value>
        /* <example>7</example> */
        [Required]
        [DataMember(Name="currentUserId", EmitDefaultValue=true)]
        public int CurrentUserId { get; set; }

        /// <summary>
        /// User id of an active club member.
        /// </summary>
        /// <value>User id of an active club member.</value>
        /* <example>12</example> */
        [Required]
        [DataMember(Name="leaderUserId", EmitDefaultValue=true)]
        public int LeaderUserId { get; set; }

    }
}
