/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 为目标用户分配系统级或社团级角色。
    /// </summary>
    [DataContract]
    public partial class AssignRoleRequest 
    {
        /// <summary>
        /// 发起分配操作的用户 ID。
        /// </summary>
        /// <value>发起分配操作的用户 ID。</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="operatorUserId", EmitDefaultValue=true)]
        public int OperatorUserId { get; set; }

        /// <summary>
        /// 被分配角色的用户 ID。
        /// </summary>
        /// <value>被分配角色的用户 ID。</value>
        /* <example>2</example> */
        [Required]
        [DataMember(Name="targetUserId", EmitDefaultValue=true)]
        public int TargetUserId { get; set; }

        /// <summary>
        /// 角色编码，例如 STUDENT、CLUB_MEMBER、SYSTEM_ADMIN。
        /// </summary>
        /// <value>角色编码，例如 STUDENT、CLUB_MEMBER、SYSTEM_ADMIN。</value>
        /* <example>CLUB_MEMBER</example> */
        [Required]
        [MaxLength(50)]
        [DataMember(Name="roleCode", EmitDefaultValue=false)]
        public string RoleCode { get; set; }

        /// <summary>
        /// 社团级角色所属社团 ID；系统级角色可为空。
        /// </summary>
        /// <value>社团级角色所属社团 ID；系统级角色可为空。</value>
        /* <example>1</example> */
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int? ClubId { get; set; }

    }
}
