/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 注册或登录成功后的认证响应。
    /// </summary>
    [DataContract]
    public partial class AuthResponse 
    {
        /// <summary>
        /// 登录令牌；调用需要当前登录态的接口时通过 Authorization Bearer 头传递。
        /// </summary>
        /// <value>登录令牌；调用需要当前登录态的接口时通过 Authorization Bearer 头传递。</value>
        /* <example>eyJ1c2VySWQiOjF9.abc123signature</example> */
        [Required]
        [DataMember(Name="token", EmitDefaultValue=false)]
        public string Token { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [Required]
        [DataMember(Name="user", EmitDefaultValue=false)]
        public AuthUser User { get; set; }

        /// <summary>
        /// 当前用户拥有的角色列表。
        /// </summary>
        /// <value>当前用户拥有的角色列表。</value>
        [Required]
        [DataMember(Name="roles", EmitDefaultValue=false)]
        public List<AuthRole> Roles { get; set; }

        /// <summary>
        /// 当前用户角色权限的并集。
        /// </summary>
        /// <value>当前用户角色权限的并集。</value>
        /* <example>[&quot;profile:view&quot;,&quot;public:view&quot;]</example> */
        [Required]
        [DataMember(Name="permissions", EmitDefaultValue=false)]
        public List<string> Permissions { get; set; }

    }
}
