/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 评优评奖成员申报记录。当前复用 EVALUATIONS 表中的 award_application 类型承载。
    /// </summary>
    [DataContract]
    public partial class AwardApplicationRecord 
    {
        /// <summary>
        /// Gets or Sets ApplicationId
        /// </summary>
        [Required]
        [DataMember(Name="applicationId", EmitDefaultValue=true)]
        public int ApplicationId { get; set; }

        /// <summary>
        /// Gets or Sets CampaignId
        /// </summary>
        [Required]
        [DataMember(Name="campaignId", EmitDefaultValue=true)]
        public int CampaignId { get; set; }

        /// <summary>
        /// Gets or Sets ClubId
        /// </summary>
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// Gets or Sets ClubName
        /// </summary>
        [Required]
        [DataMember(Name="clubName", EmitDefaultValue=false)]
        public string ClubName { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets AwardLevel
        /// </summary>
        [DataMember(Name="awardLevel", EmitDefaultValue=true)]
        public string? AwardLevel { get; set; }

        /// <summary>
        /// Gets or Sets TermName
        /// </summary>
        [Required]
        [DataMember(Name="termName", EmitDefaultValue=false)]
        public string TermName { get; set; }

        /// <summary>
        /// Gets or Sets ApplicantUserId
        /// </summary>
        [Required]
        [DataMember(Name="applicantUserId", EmitDefaultValue=true)]
        public int ApplicantUserId { get; set; }

        /// <summary>
        /// Gets or Sets ApplicantName
        /// </summary>
        [Required]
        [DataMember(Name="applicantName", EmitDefaultValue=false)]
        public string ApplicantName { get; set; }

        /// <summary>
        /// Gets or Sets StudentNo
        /// </summary>
        [DataMember(Name="studentNo", EmitDefaultValue=true)]
        public string? StudentNo { get; set; }

        /// <summary>
        /// Gets or Sets DepartmentName
        /// </summary>
        [DataMember(Name="departmentName", EmitDefaultValue=true)]
        public string? DepartmentName { get; set; }

        /// <summary>
        /// Gets or Sets GroupName
        /// </summary>
        [DataMember(Name="groupName", EmitDefaultValue=true)]
        public string? GroupName { get; set; }

        /// <summary>
        /// Gets or Sets PositionName
        /// </summary>
        [DataMember(Name="positionName", EmitDefaultValue=true)]
        public string? PositionName { get; set; }

        /// <summary>
        /// Gets or Sets ApplyReason
        /// </summary>
        [Required]
        [DataMember(Name="applyReason", EmitDefaultValue=false)]
        public string ApplyReason { get; set; }


        /// <summary>
        /// Gets or Sets ApplicationStatus
        /// </summary>
        
        public enum ApplicationStatusEnum
        {
            
            /// <summary>
            /// Enum SubmittedEnum for submitted
            /// </summary>
            [EnumMember(Value = "submitted")]
            SubmittedEnum = 1,
            
            /// <summary>
            /// Enum LeaderApprovedEnum for leader_approved
            /// </summary>
            [EnumMember(Value = "leader_approved")]
            LeaderApprovedEnum = 2,
            
            /// <summary>
            /// Enum AdvisorApprovedEnum for advisor_approved
            /// </summary>
            [EnumMember(Value = "advisor_approved")]
            AdvisorApprovedEnum = 3,
            
            /// <summary>
            /// Enum RejectedEnum for rejected
            /// </summary>
            [EnumMember(Value = "rejected")]
            RejectedEnum = 4,
            
            /// <summary>
            /// Enum PublishedEnum for published
            /// </summary>
            [EnumMember(Value = "published")]
            PublishedEnum = 5
        }

        /// <summary>
        /// Gets or Sets ApplicationStatus
        /// </summary>
        [Required]
        [DataMember(Name="applicationStatus", EmitDefaultValue=true)]
        public ApplicationStatusEnum ApplicationStatus { get; set; }

        /// <summary>
        /// Gets or Sets ApplicationStatusText
        /// </summary>
        [Required]
        [DataMember(Name="applicationStatusText", EmitDefaultValue=false)]
        public string ApplicationStatusText { get; set; }

        /// <summary>
        /// Gets or Sets ReviewerUserId
        /// </summary>
        [DataMember(Name="reviewerUserId", EmitDefaultValue=true)]
        public int? ReviewerUserId { get; set; }

        /// <summary>
        /// Gets or Sets ReviewerName
        /// </summary>
        [DataMember(Name="reviewerName", EmitDefaultValue=true)]
        public string? ReviewerName { get; set; }

        /// <summary>
        /// Gets or Sets ReviewComment
        /// </summary>
        [DataMember(Name="reviewComment", EmitDefaultValue=true)]
        public string? ReviewComment { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime? CreatedAt { get; set; }

    }
}
