/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{
    /// <summary>
    /// 社团评奖评优奖项等级配置。
    /// </summary>
    [DataContract]
    public partial class AwardLevelRecord
    {
        /// <summary>
        /// Gets or Sets AwardLevelId
        /// </summary>
        /* <example>10001</example> */
        [Required]
        [DataMember(Name = "awardLevelId", EmitDefaultValue = true)]
        public int AwardLevelId { get; set; }

        /// <summary>
        /// Gets or Sets AwardSchemeId
        /// </summary>
        /* <example>9001</example> */
        [Required]
        [DataMember(Name = "awardSchemeId", EmitDefaultValue = true)]
        public int AwardSchemeId { get; set; }

        /// <summary>
        /// Gets or Sets LevelName
        /// </summary>
        /* <example>一等奖</example> */
        [Required]
        [DataMember(Name = "levelName", EmitDefaultValue = false)]
        public string LevelName { get; set; }

        /// <summary>
        /// Gets or Sets AwardScore
        /// </summary>
        /* <example>20</example> */
        [Required]
        [DataMember(Name = "awardScore", EmitDefaultValue = true)]
        public decimal AwardScore { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        /* <example>500</example> */
        [DataMember(Name = "amount", EmitDefaultValue = true)]
        public decimal? Amount { get; set; }

        /// <summary>
        /// Gets or Sets Quota
        /// </summary>
        /* <example>3</example> */
        [DataMember(Name = "quota", EmitDefaultValue = true)]
        public int? Quota { get; set; }

        /// <summary>
        /// Gets or Sets DisplayOrder
        /// </summary>
        /* <example>1</example> */
        [Required]
        [DataMember(Name = "displayOrder", EmitDefaultValue = true)]
        public int DisplayOrder { get; set; }


        /// <summary>
        /// Gets or Sets LevelStatus
        /// </summary>

        public enum LevelStatusEnum
        {

            /// <summary>
            /// Enum ActiveEnum for active
            /// </summary>
            [EnumMember(Value = "active")]
            ActiveEnum = 1,

            /// <summary>
            /// Enum InactiveEnum for inactive
            /// </summary>
            [EnumMember(Value = "inactive")]
            InactiveEnum = 2
        }

        /// <summary>
        /// Gets or Sets LevelStatus
        /// </summary>
        /* <example>active</example> */
        [Required]
        [DataMember(Name = "levelStatus", EmitDefaultValue = true)]
        public LevelStatusEnum LevelStatus { get; set; }

    }
}
