/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 评优评奖活动记录。当前复用 EVALUATIONS 表中的 award_campaign 类型承载。
    /// </summary>
    [DataContract]
    public partial class AwardCampaignRecord 
    {
        /// <summary>
        /// Gets or Sets CampaignId
        /// </summary>
        [Required]
        [DataMember(Name="campaignId", EmitDefaultValue=true)]
        public int CampaignId { get; set; }

        /// <summary>
        /// Gets or Sets ClubId
        /// </summary>
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// Gets or Sets ClubName
        /// </summary>
        [Required]
        [DataMember(Name="clubName", EmitDefaultValue=false)]
        public string ClubName { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets AwardType
        /// </summary>
        [DataMember(Name="awardType", EmitDefaultValue=true)]
        public string? AwardType { get; set; }

        /// <summary>
        /// Gets or Sets TermName
        /// </summary>
        [Required]
        [DataMember(Name="termName", EmitDefaultValue=false)]
        public string TermName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets PublisherUserId
        /// </summary>
        [Required]
        [DataMember(Name="publisherUserId", EmitDefaultValue=true)]
        public int PublisherUserId { get; set; }

        /// <summary>
        /// Gets or Sets PublisherName
        /// </summary>
        [Required]
        [DataMember(Name="publisherName", EmitDefaultValue=false)]
        public string PublisherName { get; set; }


        /// <summary>
        /// Gets or Sets CampaignStatus
        /// </summary>
        
        public enum CampaignStatusEnum
        {
            
            /// <summary>
            /// Enum OpenEnum for open
            /// </summary>
            [EnumMember(Value = "open")]
            OpenEnum = 1,
            
            /// <summary>
            /// Enum ClosedEnum for closed
            /// </summary>
            [EnumMember(Value = "closed")]
            ClosedEnum = 2,
            
            /// <summary>
            /// Enum PublishedEnum for published
            /// </summary>
            [EnumMember(Value = "published")]
            PublishedEnum = 3
        }

        /// <summary>
        /// Gets or Sets CampaignStatus
        /// </summary>
        [Required]
        [DataMember(Name="campaignStatus", EmitDefaultValue=true)]
        public CampaignStatusEnum CampaignStatus { get; set; }

        /// <summary>
        /// Gets or Sets CampaignStatusText
        /// </summary>
        [Required]
        [DataMember(Name="campaignStatusText", EmitDefaultValue=false)]
        public string CampaignStatusText { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ApplicationCount
        /// </summary>
        [Required]
        [DataMember(Name="applicationCount", EmitDefaultValue=true)]
        public int ApplicationCount { get; set; }

        /// <summary>
        /// Gets or Sets SubmittedCount
        /// </summary>
        [Required]
        [DataMember(Name="submittedCount", EmitDefaultValue=true)]
        public int SubmittedCount { get; set; }

        /// <summary>
        /// Gets or Sets ApprovedCount
        /// </summary>
        [Required]
        [DataMember(Name="approvedCount", EmitDefaultValue=true)]
        public int ApprovedCount { get; set; }

        /// <summary>
        /// Gets or Sets PublishedCount
        /// </summary>
        [Required]
        [DataMember(Name="publishedCount", EmitDefaultValue=true)]
        public int PublishedCount { get; set; }

    }
}
