/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 经费流水记录，余额由经费账户初始额度和流水金额汇总得到。
    /// </summary>
    [DataContract]
    public partial class BudgetTransaction 
    {
        /// <summary>
        /// 经费流水 ID。
        /// </summary>
        /// <value>经费流水 ID。</value>
        /* <example>1000000</example> */
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// 关联经费账户 ID。
        /// </summary>
        /// <value>关联经费账户 ID。</value>
        /* <example>1000000</example> */
        [Required]
        [DataMember(Name="accountId", EmitDefaultValue=true)]
        public int AccountId { get; set; }

        /// <summary>
        /// 关联经费申请 ID；手工调整类流水可为空。
        /// </summary>
        /// <value>关联经费申请 ID；手工调整类流水可为空。</value>
        /* <example>1000000</example> */
        [DataMember(Name="applicationId", EmitDefaultValue=true)]
        public int? ApplicationId { get; set; }

        /// <summary>
        /// 流水所属社团 ID。
        /// </summary>
        /// <value>流水所属社团 ID。</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// 流水所属社团名称。
        /// </summary>
        /// <value>流水所属社团名称。</value>
        /* <example>计算机协会</example> */
        [Required]
        [DataMember(Name="clubName", EmitDefaultValue=false)]
        public string ClubName { get; set; }


        /// <summary>
        /// 流水类型；commitment 审批占用，expense 实际支出，refund 退款，adjustment 调整。
        /// </summary>
        /// <value>流水类型；commitment 审批占用，expense 实际支出，refund 退款，adjustment 调整。</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum CommitmentEnum for commitment
            /// </summary>
            [EnumMember(Value = "commitment")]
            CommitmentEnum = 1,
            
            /// <summary>
            /// Enum ExpenseEnum for expense
            /// </summary>
            [EnumMember(Value = "expense")]
            ExpenseEnum = 2,
            
            /// <summary>
            /// Enum RefundEnum for refund
            /// </summary>
            [EnumMember(Value = "refund")]
            RefundEnum = 3,
            
            /// <summary>
            /// Enum AdjustmentEnum for adjustment
            /// </summary>
            [EnumMember(Value = "adjustment")]
            AdjustmentEnum = 4
        }

        /// <summary>
        /// 流水类型；commitment 审批占用，expense 实际支出，refund 退款，adjustment 调整。
        /// </summary>
        /// <value>流水类型；commitment 审批占用，expense 实际支出，refund 退款，adjustment 调整。</value>
        /* <example>commitment</example> */
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// 流水金额，支出或占用为负数，退款或调增为正数。
        /// </summary>
        /// <value>流水金额，支出或占用为负数，退款或调增为正数。</value>
        /* <example>-1200</example> */
        [Required]
        [DataMember(Name="amount", EmitDefaultValue=true)]
        public double Amount { get; set; }

        /// <summary>
        /// 流水说明。
        /// </summary>
        /// <value>流水说明。</value>
        /* <example>经费申请通过：迎新活动物料采购</example> */
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// 流水发生时间。
        /// </summary>
        /// <value>流水发生时间。</value>
        /* <example>2026-07-20T12:00Z</example> */
        [Required]
        [DataMember(Name="occurredAt", EmitDefaultValue=true)]
        public DateTime OccurredAt { get; set; }

        /// <summary>
        /// 流水创建时间。
        /// </summary>
        /// <value>流水创建时间。</value>
        /* <example>2026-07-20T12:00Z</example> */
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

    }
}
