/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 社团小组记录，对应 CLUB_GROUPS 表。
    /// </summary>
    [DataContract]
    public partial class ClubGroupRecord 
    {
        /// <summary>
        /// 小组 ID。
        /// </summary>
        /// <value>小组 ID。</value>
        /* <example>2001</example> */
        [Required]
        [DataMember(Name="groupId", EmitDefaultValue=true)]
        public int GroupId { get; set; }

        /// <summary>
        /// 所属社团 ID。
        /// </summary>
        /// <value>所属社团 ID。</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// 所属部门 ID。
        /// </summary>
        /// <value>所属部门 ID。</value>
        /* <example>1001</example> */
        [Required]
        [DataMember(Name="departmentId", EmitDefaultValue=true)]
        public int DepartmentId { get; set; }

        /// <summary>
        /// 小组名称，同一部门下唯一。
        /// </summary>
        /// <value>小组名称，同一部门下唯一。</value>
        /* <example>开发组</example> */
        [Required]
        [DataMember(Name="groupName", EmitDefaultValue=false)]
        public string GroupName { get; set; }

        /// <summary>
        /// 小组内部编码，可用于后端或导入识别。
        /// </summary>
        /// <value>小组内部编码，可用于后端或导入识别。</value>
        /* <example>DEV</example> */
        [DataMember(Name="groupCode", EmitDefaultValue=true)]
        public string? GroupCode { get; set; }

        /// <summary>
        /// 小组简介。
        /// </summary>
        /// <value>小组简介。</value>
        /* <example>负责协会项目开发与代码维护。</example> */
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// 小组职责范围。
        /// </summary>
        /// <value>小组职责范围。</value>
        /* <example>维护社团官网、组织技术分享和项目协作。</example> */
        [DataMember(Name="responsibilities", EmitDefaultValue=true)]
        public string? Responsibilities { get; set; }

        /// <summary>
        /// 小组联系电话。
        /// </summary>
        /// <value>小组联系电话。</value>
        /* <example>13800000000</example> */
        [DataMember(Name="contactPhone", EmitDefaultValue=true)]
        public string? ContactPhone { get; set; }

        /// <summary>
        /// 小组联系邮箱。
        /// </summary>
        /// <value>小组联系邮箱。</value>
        /* <example>dev@clubhub.example</example> */
        [DataMember(Name="contactEmail", EmitDefaultValue=true)]
        public string? ContactEmail { get; set; }

        /// <summary>
        /// 小组常用活动地点。
        /// </summary>
        /// <value>小组常用活动地点。</value>
        /* <example>嘉定校区创新实验室</example> */
        [DataMember(Name="activityLocation", EmitDefaultValue=true)]
        public string? ActivityLocation { get; set; }

        /// <summary>
        /// 小组展示顺序，数值越小越靠前。
        /// </summary>
        /// <value>小组展示顺序，数值越小越靠前。</value>
        /* <example>10</example> */
        [Required]
        [DataMember(Name="displayOrder", EmitDefaultValue=true)]
        public int DisplayOrder { get; set; }


        /// <summary>
        /// 小组状态，active 表示启用，inactive 表示停用。
        /// </summary>
        /// <value>小组状态，active 表示启用，inactive 表示停用。</value>
        
        public enum GroupStatusEnum
        {
            
            /// <summary>
            /// Enum ActiveEnum for active
            /// </summary>
            [EnumMember(Value = "active")]
            ActiveEnum = 1,
            
            /// <summary>
            /// Enum InactiveEnum for inactive
            /// </summary>
            [EnumMember(Value = "inactive")]
            InactiveEnum = 2
        }

        /// <summary>
        /// 小组状态，active 表示启用，inactive 表示停用。
        /// </summary>
        /// <value>小组状态，active 表示启用，inactive 表示停用。</value>
        /* <example>active</example> */
        [Required]
        [DataMember(Name="groupStatus", EmitDefaultValue=true)]
        public GroupStatusEnum GroupStatus { get; set; }

        /// <summary>
        /// 小组创建时间。
        /// </summary>
        /// <value>小组创建时间。</value>
        /* <example>2026-07-14T08:00Z</example> */
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// 小组最后更新时间。
        /// </summary>
        /// <value>小组最后更新时间。</value>
        /* <example>2026-07-14T08:30Z</example> */
        [Required]
        [DataMember(Name="updatedAt", EmitDefaultValue=true)]
        public DateTime UpdatedAt { get; set; }

    }
}
