/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 社团部门记录，对应 CLUB_DEPARTMENTS 表，并携带下属小组。
    /// </summary>
    [DataContract]
    public partial class ClubDepartmentRecord 
    {
        /// <summary>
        /// Gets or Sets DepartmentId
        /// </summary>
        [Required]
        [DataMember(Name="departmentId", EmitDefaultValue=true)]
        public int DepartmentId { get; set; }

        /// <summary>
        /// Gets or Sets ClubId
        /// </summary>
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// Gets or Sets DepartmentName
        /// </summary>
        [Required]
        [DataMember(Name="departmentName", EmitDefaultValue=false)]
        public string DepartmentName { get; set; }

        /// <summary>
        /// Gets or Sets DepartmentCode
        /// </summary>
        [DataMember(Name="departmentCode", EmitDefaultValue=true)]
        public string? DepartmentCode { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets Responsibilities
        /// </summary>
        [DataMember(Name="responsibilities", EmitDefaultValue=true)]
        public string? Responsibilities { get; set; }

        /// <summary>
        /// Gets or Sets ContactPhone
        /// </summary>
        [DataMember(Name="contactPhone", EmitDefaultValue=true)]
        public string? ContactPhone { get; set; }

        /// <summary>
        /// Gets or Sets ContactEmail
        /// </summary>
        [DataMember(Name="contactEmail", EmitDefaultValue=true)]
        public string? ContactEmail { get; set; }

        /// <summary>
        /// Gets or Sets OfficeLocation
        /// </summary>
        [DataMember(Name="officeLocation", EmitDefaultValue=true)]
        public string? OfficeLocation { get; set; }

        /// <summary>
        /// Gets or Sets DisplayOrder
        /// </summary>
        [Required]
        [DataMember(Name="displayOrder", EmitDefaultValue=true)]
        public int DisplayOrder { get; set; }


        /// <summary>
        /// Gets or Sets DepartmentStatus
        /// </summary>
        
        public enum DepartmentStatusEnum
        {
            
            /// <summary>
            /// Enum ActiveEnum for active
            /// </summary>
            [EnumMember(Value = "active")]
            ActiveEnum = 1,
            
            /// <summary>
            /// Enum InactiveEnum for inactive
            /// </summary>
            [EnumMember(Value = "inactive")]
            InactiveEnum = 2
        }

        /// <summary>
        /// Gets or Sets DepartmentStatus
        /// </summary>
        [Required]
        [DataMember(Name="departmentStatus", EmitDefaultValue=true)]
        public DepartmentStatusEnum DepartmentStatus { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [Required]
        [DataMember(Name="updatedAt", EmitDefaultValue=true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Groups
        /// </summary>
        [Required]
        [DataMember(Name="groups", EmitDefaultValue=false)]
        public List<ClubGroupRecord> Groups { get; set; }

    }
}
