/*
 * ClubHub API
 *
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Club 
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="category", EmitDefaultValue=true)]
        public string? Category { get; set; }

        /// <summary>
        /// Gets or Sets FoundedAt
        /// </summary>
        [DataMember(Name="foundedAt", EmitDefaultValue=true)]
        public DateTime? FoundedAt { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=true)]
        public string? Status { get; set; }

        /// <summary>
        /// Gets or Sets StatusText
        /// </summary>
        [Required]
        [DataMember(Name="statusText", EmitDefaultValue=false)]
        public string StatusText { get; set; }

        /// <summary>
        /// Gets or Sets LogoUrl
        /// </summary>
        [DataMember(Name="logoUrl", EmitDefaultValue=true)]
        public string? LogoUrl { get; set; }

        /// <summary>
        /// Gets or Sets PresidentUserId
        /// </summary>
        [DataMember(Name="presidentUserId", EmitDefaultValue=true)]
        public int? PresidentUserId { get; set; }

        /// <summary>
        /// Gets or Sets PresidentName
        /// </summary>
        [DataMember(Name="presidentName", EmitDefaultValue=true)]
        public string? PresidentName { get; set; }

        /// <summary>
        /// 褰撳墠鎸囧鑰佸笀鐢ㄦ埛 ID锛岀敱 USER_ROLES 涓?ADVISOR 绀惧洟瑙掕壊鍏崇郴鎺ㄥ銆?        /// </summary>
        /// <value>褰撳墠鎸囧鑰佸笀鐢ㄦ埛 ID锛岀敱 USER_ROLES 涓?ADVISOR 绀惧洟瑙掕壊鍏崇郴鎺ㄥ銆?/value>
        [DataMember(Name="advisorUserId", EmitDefaultValue=true)]
        public int? AdvisorUserId { get; set; }

        /// <summary>
        /// 褰撳墠鎸囧鑰佸笀灞曠ず鍚嶇О锛涗紭鍏堢敱 ADVISOR 瑙掕壊瀵瑰簲鐢ㄦ埛鎺ㄥ锛屽巻鍙叉暟鎹彲鍥為€€鍒扮ぞ鍥㈡枃鏈瓧娈点€?        /// </summary>
        /// <value>褰撳墠鎸囧鑰佸笀灞曠ず鍚嶇О锛涗紭鍏堢敱 ADVISOR 瑙掕壊瀵瑰簲鐢ㄦ埛鎺ㄥ锛屽巻鍙叉暟鎹彲鍥為€€鍒扮ぞ鍥㈡枃鏈瓧娈点€?/value>
        [DataMember(Name="advisorName", EmitDefaultValue=true)]
        public string? AdvisorName { get; set; }

        /// <summary>
        /// Gets or Sets ContactPhone
        /// </summary>
        [DataMember(Name="contactPhone", EmitDefaultValue=true)]
        public string? ContactPhone { get; set; }

        /// <summary>
        /// Gets or Sets AuditStatus
        /// </summary>
        [DataMember(Name="auditStatus", EmitDefaultValue=true)]
        public string? AuditStatus { get; set; }

        /// <summary>
        /// Gets or Sets AuditStatusText
        /// </summary>
        [Required]
        [DataMember(Name="auditStatusText", EmitDefaultValue=false)]
        public string AuditStatusText { get; set; }

        /// <summary>
        /// Gets or Sets ApplicantUserId
        /// </summary>
        [DataMember(Name="applicantUserId", EmitDefaultValue=true)]
        public int? ApplicantUserId { get; set; }

        /// <summary>
        /// Gets or Sets ApplicantName
        /// </summary>
        [DataMember(Name="applicantName", EmitDefaultValue=true)]
        public string? ApplicantName { get; set; }

        /// <summary>
        /// Gets or Sets ApplyReason
        /// </summary>
        [DataMember(Name="applyReason", EmitDefaultValue=true)]
        public string? ApplyReason { get; set; }

        /// <summary>
        /// Gets or Sets MaterialUrl
        /// </summary>
        [DataMember(Name="materialUrl", EmitDefaultValue=true)]
        public string? MaterialUrl { get; set; }

        /// <summary>
        /// Gets or Sets ReviewerUserId
        /// </summary>
        [DataMember(Name="reviewerUserId", EmitDefaultValue=true)]
        public int? ReviewerUserId { get; set; }

        /// <summary>
        /// Gets or Sets ReviewerName
        /// </summary>
        [DataMember(Name="reviewerName", EmitDefaultValue=true)]
        public string? ReviewerName { get; set; }

        /// <summary>
        /// Gets or Sets ReviewComment
        /// </summary>
        [DataMember(Name="reviewComment", EmitDefaultValue=true)]
        public string? ReviewComment { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name="updatedAt", EmitDefaultValue=true)]
        public DateTime? UpdatedAt { get; set; }

    }
}

