/*
 * ClubHub API
 *
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateClubApplicationRequest 
    {
        /// <summary>
        /// 褰撳墠瀛︾敓鐢ㄦ埛 ID锛屽悗绔嵁姝ゅ啓鍏ョ敵璇蜂汉骞舵牎楠岃鑹叉潈闄愩€?        /// </summary>
        /// <value>褰撳墠瀛︾敓鐢ㄦ埛 ID锛屽悗绔嵁姝ゅ啓鍏ョ敵璇蜂汉骞舵牎楠岃鑹叉潈闄愩€?/value>
        [Required]
        [DataMember(Name="currentUserId", EmitDefaultValue=true)]
        public int CurrentUserId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="category", EmitDefaultValue=false)]
        public string Category { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets ApplyReason
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="applyReason", EmitDefaultValue=false)]
        public string ApplyReason { get; set; }

        /// <summary>
        /// Gets or Sets MaterialUrl
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="materialUrl", EmitDefaultValue=false)]
        public string MaterialUrl { get; set; }

        /// <summary>
        /// 鎷熼個璇风殑鎸囧鑰佸笀鐢ㄦ埛 ID锛涘悗绔細鏍￠獙鏁欏笀韬唤骞剁淮鎶?ADVISOR 瑙掕壊鍏崇郴銆?        /// </summary>
        /// <value>鎷熼個璇风殑鎸囧鑰佸笀鐢ㄦ埛 ID锛涘悗绔細鏍￠獙鏁欏笀韬唤骞剁淮鎶?ADVISOR 瑙掕壊鍏崇郴銆?/value>
        [DataMember(Name="advisorUserId", EmitDefaultValue=true)]
        public int? AdvisorUserId { get; set; }

        /// <summary>
        /// 鍘嗗彶鍏煎瀛楁锛涙柊娴佺▼璇蜂娇鐢?advisorUserId銆?        /// </summary>
        /// <value>鍘嗗彶鍏煎瀛楁锛涙柊娴佺▼璇蜂娇鐢?advisorUserId銆?/value>
        [DataMember(Name="advisorName", EmitDefaultValue=true)]
        public string? AdvisorName { get; set; }

        /// <summary>
        /// Gets or Sets ContactPhone
        /// </summary>
        [DataMember(Name="contactPhone", EmitDefaultValue=true)]
        public string? ContactPhone { get; set; }

    }
}

