/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平�?API�? **API-first 开发流�?*：修改本文件 �?push �?CI 自动生成前后端代�?�?git pull 拉取生成代码 �?�?Controller / Services / Vue 组件中手写业务逻辑�?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateActivityRequest 
    {
        /// <summary>
        /// Gets or Sets ClubId
        /// </summary>
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// Gets or Sets CreatorUserId
        /// </summary>
        [DataMember(Name="creatorUserId", EmitDefaultValue=true)]
        public int? CreatorUserId { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [Required]
        [StringLength(255, MinimumLength=1)]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets ActivityType
        /// </summary>
        [MaxLength(255)]
        [DataMember(Name="activityType", EmitDefaultValue=true)]
        public string? ActivityType { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [MaxLength(255)]
        [DataMember(Name="location", EmitDefaultValue=true)]
        public string? Location { get; set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        [Required]
        [DataMember(Name="startTime", EmitDefaultValue=true)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Gets or Sets EndTime
        /// </summary>
        [Required]
        [DataMember(Name="endTime", EmitDefaultValue=true)]
        public DateTime EndTime { get; set; }

        /// <summary>
        /// Gets or Sets MaxParticipants
        /// </summary>
        [DataMember(Name="maxParticipants", EmitDefaultValue=true)]
        public int? MaxParticipants { get; set; }

        /// <summary>
        /// Gets or Sets RegistrationDeadline
        /// </summary>
        [DataMember(Name="registrationDeadline", EmitDefaultValue=true)]
        public DateTime? RegistrationDeadline { get; set; }

    }
}
