/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateAwardApplicationRequest 
    {
        /// <summary>
        /// Gets or Sets CurrentUserId
        /// </summary>
        [Required]
        [DataMember(Name="currentUserId", EmitDefaultValue=true)]
        public int CurrentUserId { get; set; }

        /// <summary>
        /// Gets or Sets AwardLevel
        /// </summary>
        [DataMember(Name="awardLevel", EmitDefaultValue=true)]
        public string? AwardLevel { get; set; }

        /// <summary>
        /// Gets or Sets ApplyReason
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="applyReason", EmitDefaultValue=false)]
        public string ApplyReason { get; set; }

    }
}
