/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 创建评奖评优公示批次。
    /// </summary>
    [DataContract]
    public partial class CreateAwardPublicityBatchRequest 
    {
        /// <summary>
        /// 公示标题。
        /// </summary>
        /// <value>公示标题。</value>
        /* <example>2025-2026学年春季优秀社团干部拟获奖名单公示</example> */
        [Required]
        [StringLength(255, MinimumLength=1)]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// 公示说明。
        /// </summary>
        /// <value>公示说明。</value>
        /* <example>公示期内如有异议请联系社团负责人。</example> */
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// 公示开始时间，不能为空。
        /// </summary>
        /// <value>公示开始时间，不能为空。</value>
        /* <example>2026-07-18T09:00Z</example> */
        [Required]
        [DataMember(Name="publicityStartAt", EmitDefaultValue=true)]
        public DateTime? PublicityStartAt { get; set; }

        /// <summary>
        /// 公示结束时间，必须晚于 publicityStartAt。
        /// </summary>
        /// <value>公示结束时间，必须晚于 publicityStartAt。</value>
        /* <example>2026-07-21T18:00Z</example> */
        [Required]
        [DataMember(Name="publicityEndAt", EmitDefaultValue=true)]
        public DateTime? PublicityEndAt { get; set; }

        /// <summary>
        /// 纳入公示的已通过申请 ID。
        /// </summary>
        /// <value>纳入公示的已通过申请 ID。</value>
        /* <example>[70001,70002]</example> */
        [Required]
        [DataMember(Name="awardApplicationIds", EmitDefaultValue=false)]
        public List<int> AwardApplicationIds { get; set; }

    }
}
