/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateAwardCampaignRequest 
    {
        /// <summary>
        /// Gets or Sets CurrentUserId
        /// </summary>
        [Required]
        [DataMember(Name="currentUserId", EmitDefaultValue=true)]
        public int CurrentUserId { get; set; }

        /// <summary>
        /// Gets or Sets ClubId
        /// </summary>
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets AwardType
        /// </summary>
        [DataMember(Name="awardType", EmitDefaultValue=true)]
        public string? AwardType { get; set; }

        /// <summary>
        /// Gets or Sets TermName
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="termName", EmitDefaultValue=false)]
        public string TermName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }


        /// <summary>
        /// Gets or Sets CampaignStatus
        /// </summary>
        
        public enum CampaignStatusEnum
        {
            
            /// <summary>
            /// Enum OpenEnum for open
            /// </summary>
            [EnumMember(Value = "open")]
            OpenEnum = 1,
            
            /// <summary>
            /// Enum ClosedEnum for closed
            /// </summary>
            [EnumMember(Value = "closed")]
            ClosedEnum = 2,
            
            /// <summary>
            /// Enum PublishedEnum for published
            /// </summary>
            [EnumMember(Value = "published")]
            PublishedEnum = 3
        }

        /// <summary>
        /// Gets or Sets CampaignStatus
        /// </summary>
        [DataMember(Name="campaignStatus", EmitDefaultValue=true)]
        public CampaignStatusEnum CampaignStatus { get; set; } = CampaignStatusEnum.OpenEnum;

    }
}
