/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 基于 LEARNING_RECORDS 聚合的资源学习与下载统计。
    /// </summary>
    [DataContract]
    public partial class LearningItemStatistics 
    {
        /// <summary>
        /// 学习资源 ID。
        /// </summary>
        /// <value>学习资源 ID。</value>
        [Required]
        [DataMember(Name="itemId", EmitDefaultValue=true)]
        public int ItemId { get; set; }

        /// <summary>
        /// 资源标题。
        /// </summary>
        /// <value>资源标题。</value>
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// 非取消状态的学习人数。
        /// </summary>
        /// <value>非取消状态的学习人数。</value>
        [Required]
        [DataMember(Name="learnerCount", EmitDefaultValue=true)]
        public int LearnerCount { get; set; }

        /// <summary>
        /// 已完成学习人数。
        /// </summary>
        /// <value>已完成学习人数。</value>
        [Required]
        [DataMember(Name="completedCount", EmitDefaultValue=true)]
        public int CompletedCount { get; set; }

        /// <summary>
        /// 发生过下载行为的人数。
        /// </summary>
        /// <value>发生过下载行为的人数。</value>
        [Required]
        [DataMember(Name="downloadCount", EmitDefaultValue=true)]
        public int DownloadCount { get; set; }

        /// <summary>
        /// 学习记录平均进度。
        /// </summary>
        /// <value>学习记录平均进度。</value>
        [Required]
        [DataMember(Name="averageProgress", EmitDefaultValue=true)]
        public double AverageProgress { get; set; }

        /// <summary>
        /// 平均累计学习时长（秒）。
        /// </summary>
        /// <value>平均累计学习时长（秒）。</value>
        [Required]
        [DataMember(Name="averageDurationSeconds", EmitDefaultValue=true)]
        public double AverageDurationSeconds { get; set; }

        /// <summary>
        /// 累计学习时长（秒）。
        /// </summary>
        /// <value>累计学习时长（秒）。</value>
        [Required]
        [DataMember(Name="totalDurationSeconds", EmitDefaultValue=true)]
        public int TotalDurationSeconds { get; set; }

    }
}
