/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 课程报名、资源学习进度和下载行为记录。
    /// </summary>
    [DataContract]
    public partial class LearningRecord 
    {
        /// <summary>
        /// Learning record id in LEARNING_RECORDS.RECORD_ID.
        /// </summary>
        /// <value>Learning record id in LEARNING_RECORDS.RECORD_ID.</value>
        /* <example>3001</example> */
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Related learning item id.
        /// </summary>
        /// <value>Related learning item id.</value>
        /* <example>2001</example> */
        [Required]
        [DataMember(Name="itemId", EmitDefaultValue=true)]
        public int ItemId { get; set; }

        /// <summary>
        /// Learning user id.
        /// </summary>
        /// <value>Learning user id.</value>
        /* <example>21</example> */
        [Required]
        [DataMember(Name="userId", EmitDefaultValue=true)]
        public int UserId { get; set; }

        /// <summary>
        /// Learning user&#39;s display name.
        /// </summary>
        /// <value>Learning user&#39;s display name.</value>
        [Required]
        [DataMember(Name="userDisplayName", EmitDefaultValue=false)]
        public string UserDisplayName { get; set; }

        /// <summary>
        /// Learning user&#39;s student or staff number.
        /// </summary>
        /// <value>Learning user&#39;s student or staff number.</value>
        [DataMember(Name="userNumber", EmitDefaultValue=true)]
        public string? UserNumber { get; set; }


        /// <summary>
        /// Enrollment and learning status.
        /// </summary>
        /// <value>Enrollment and learning status.</value>
        
        public enum EnrollStatusEnum
        {
            
            /// <summary>
            /// Enum EnrolledEnum for enrolled
            /// </summary>
            [EnumMember(Value = "enrolled")]
            EnrolledEnum = 1,
            
            /// <summary>
            /// Enum LearningEnum for learning
            /// </summary>
            [EnumMember(Value = "learning")]
            LearningEnum = 2,
            
            /// <summary>
            /// Enum CompletedEnum for completed
            /// </summary>
            [EnumMember(Value = "completed")]
            CompletedEnum = 3,
            
            /// <summary>
            /// Enum CancelledEnum for cancelled
            /// </summary>
            [EnumMember(Value = "cancelled")]
            CancelledEnum = 4
        }

        /// <summary>
        /// Enrollment and learning status.
        /// </summary>
        /// <value>Enrollment and learning status.</value>
        /* <example>learning</example> */
        [Required]
        [DataMember(Name="enrollStatus", EmitDefaultValue=true)]
        public EnrollStatusEnum EnrollStatus { get; set; }

        /// <summary>
        /// Enrollment time.
        /// </summary>
        /// <value>Enrollment time.</value>
        [DataMember(Name="enrolledAt", EmitDefaultValue=true)]
        public DateTime? EnrolledAt { get; set; }

        /// <summary>
        /// Learning progress percentage.
        /// </summary>
        /// <value>Learning progress percentage.</value>
        /* <example>60</example> */
        [Range(0, 100)]
        [DataMember(Name="progress", EmitDefaultValue=true)]
        public double? Progress { get; set; }

        /// <summary>
        /// Accumulated learning duration in seconds.
        /// </summary>
        /// <value>Accumulated learning duration in seconds.</value>
        /* <example>1800</example> */
        [DataMember(Name="durationSeconds", EmitDefaultValue=true)]
        public int? DurationSeconds { get; set; }

        /// <summary>
        /// Last learning time.
        /// </summary>
        /// <value>Last learning time.</value>
        [DataMember(Name="lastLearnAt", EmitDefaultValue=true)]
        public DateTime? LastLearnAt { get; set; }

        /// <summary>
        /// 完成时间。
        /// </summary>
        /// <value>完成时间。</value>
        [DataMember(Name="completedAt", EmitDefaultValue=true)]
        public DateTime? CompletedAt { get; set; }

        /// <summary>
        /// 最近一次下载时间。
        /// </summary>
        /// <value>最近一次下载时间。</value>
        [DataMember(Name="downloadedAt", EmitDefaultValue=true)]
        public DateTime? DownloadedAt { get; set; }

        /// <summary>
        /// 最近一次下载 IP。
        /// </summary>
        /// <value>最近一次下载 IP。</value>
        [DataMember(Name="downloadIp", EmitDefaultValue=true)]
        public string? DownloadIp { get; set; }

    }
}
