/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Training course or learning resource published by a club.
    /// </summary>
    [DataContract]
    public partial class LearningItem 
    {
        /// <summary>
        /// Learning item id in LEARNING_ITEMS.ITEM_ID.
        /// </summary>
        /// <value>Learning item id in LEARNING_ITEMS.ITEM_ID.</value>
        /* <example>2001</example> */
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Club that publishes the course.
        /// </summary>
        /// <value>Club that publishes the course.</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// User who created or uploaded the learning item.
        /// </summary>
        /// <value>User who created or uploaded the learning item.</value>
        /* <example>12</example> */
        [DataMember(Name="uploaderUserId", EmitDefaultValue=true)]
        public int? UploaderUserId { get; set; }

        /// <summary>
        /// Instructor user id.
        /// </summary>
        /// <value>Instructor user id.</value>
        /* <example>30</example> */
        [DataMember(Name="teacherUserId", EmitDefaultValue=true)]
        public int? TeacherUserId { get; set; }

        /// <summary>
        /// Course title.
        /// </summary>
        /// <value>Course title.</value>
        /* <example>社团干部培训课</example> */
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Course type, video, document, or other learning resource type.
        /// </summary>
        /// <value>Course type, video, document, or other learning resource type.</value>
        /* <example>course</example> */
        [DataMember(Name="itemType", EmitDefaultValue=true)]
        public string? ItemType { get; set; }

        /// <summary>
        /// Course category.
        /// </summary>
        /// <value>Course category.</value>
        /* <example>干部培训</example> */
        [DataMember(Name="categoryName", EmitDefaultValue=true)]
        public string? CategoryName { get; set; }

        /// <summary>
        /// Course introduction.
        /// </summary>
        /// <value>Course introduction.</value>
        /* <example>面向社团干部的流程与规范培训。</example> */
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Enrollment deadline. Enrollment and cancellation close at this time.
        /// </summary>
        /// <value>Enrollment deadline. Enrollment and cancellation close at this time.</value>
        [Required]
        [DataMember(Name="enrollmentDeadline", EmitDefaultValue=true)]
        public DateTime EnrollmentDeadline { get; set; }

        /// <summary>
        /// Course start time.
        /// </summary>
        /// <value>Course start time.</value>
        [Required]
        [DataMember(Name="startAt", EmitDefaultValue=true)]
        public DateTime? StartAt { get; set; }

        /// <summary>
        /// Course end time.
        /// </summary>
        /// <value>Course end time.</value>
        [Required]
        [DataMember(Name="endAt", EmitDefaultValue=true)]
        public DateTime? EndAt { get; set; }

        /// <summary>
        /// Enrollment capacity.
        /// </summary>
        /// <value>Enrollment capacity.</value>
        /* <example>40</example> */
        [Required]
        [DataMember(Name="capacity", EmitDefaultValue=true)]
        public int Capacity { get; set; }


        /// <summary>
        /// Course audience; club means active club members, public means all active school accounts.
        /// </summary>
        /// <value>Course audience; club means active club members, public means all active school accounts.</value>
        
        public enum VisibilityEnum
        {
            
            /// <summary>
            /// Enum ClubEnum for club
            /// </summary>
            [EnumMember(Value = "club")]
            ClubEnum = 1,
            
            /// <summary>
            /// Enum PublicEnum for public
            /// </summary>
            [EnumMember(Value = "public")]
            PublicEnum = 2
        }

        /// <summary>
        /// Course audience; club means active club members, public means all active school accounts.
        /// </summary>
        /// <value>Course audience; club means active club members, public means all active school accounts.</value>
        /* <example>club</example> */
        [Required]
        [DataMember(Name="visibility", EmitDefaultValue=true)]
        public VisibilityEnum Visibility { get; set; }


        /// <summary>
        /// Current course publication status.
        /// </summary>
        /// <value>Current course publication status.</value>
        
        public enum ItemStatusEnum
        {
            
            /// <summary>
            /// Enum DraftEnum for draft
            /// </summary>
            [EnumMember(Value = "draft")]
            DraftEnum = 1,
            
            /// <summary>
            /// Enum PublishedEnum for published
            /// </summary>
            [EnumMember(Value = "published")]
            PublishedEnum = 2,
            
            /// <summary>
            /// Enum ClosedEnum for closed
            /// </summary>
            [EnumMember(Value = "closed")]
            ClosedEnum = 3,
            
            /// <summary>
            /// Enum FinishedEnum for finished
            /// </summary>
            [EnumMember(Value = "finished")]
            FinishedEnum = 4
        }

        /// <summary>
        /// Current course publication status.
        /// </summary>
        /// <value>Current course publication status.</value>
        /* <example>published</example> */
        [Required]
        [DataMember(Name="itemStatus", EmitDefaultValue=true)]
        public ItemStatusEnum ItemStatus { get; set; }

        /// <summary>
        /// Active enrollment count.
        /// </summary>
        /// <value>Active enrollment count.</value>
        /* <example>8</example> */
        [Required]
        [DataMember(Name="currentEnrollments", EmitDefaultValue=true)]
        public int CurrentEnrollments { get; set; }


        /// <summary>
        /// Current viewer's learning record status; none means not enrolled.
        /// </summary>
        /// <value>Current viewer's learning record status; none means not enrolled.</value>
        
        public enum CurrentUserRecordStatusEnum
        {
            
            /// <summary>
            /// Enum NoneEnum for none
            /// </summary>
            [EnumMember(Value = "none")]
            NoneEnum = 1,
            
            /// <summary>
            /// Enum EnrolledEnum for enrolled
            /// </summary>
            [EnumMember(Value = "enrolled")]
            EnrolledEnum = 2,
            
            /// <summary>
            /// Enum LearningEnum for learning
            /// </summary>
            [EnumMember(Value = "learning")]
            LearningEnum = 3,
            
            /// <summary>
            /// Enum CompletedEnum for completed
            /// </summary>
            [EnumMember(Value = "completed")]
            CompletedEnum = 4,
            
            /// <summary>
            /// Enum CancelledEnum for cancelled
            /// </summary>
            [EnumMember(Value = "cancelled")]
            CancelledEnum = 5
        }

        /// <summary>
        /// Current viewer&#39;s learning record status; none means not enrolled.
        /// </summary>
        /// <value>Current viewer&#39;s learning record status; none means not enrolled.</value>
        [Required]
        [DataMember(Name="currentUserRecordStatus", EmitDefaultValue=true)]
        public CurrentUserRecordStatusEnum CurrentUserRecordStatus { get; set; }

        /// <summary>
        /// Whether the current viewer may edit this course and view its roster.
        /// </summary>
        /// <value>Whether the current viewer may edit this course and view its roster.</value>
        [Required]
        [DataMember(Name="canManage", EmitDefaultValue=true)]
        public bool CanManage { get; set; }

        /// <summary>
        /// Whether the current viewer may enroll now.
        /// </summary>
        /// <value>Whether the current viewer may enroll now.</value>
        [Required]
        [DataMember(Name="canEnroll", EmitDefaultValue=true)]
        public bool CanEnroll { get; set; }

        /// <summary>
        /// Whether the current viewer may cancel the current enrollment now.
        /// </summary>
        /// <value>Whether the current viewer may cancel the current enrollment now.</value>
        [Required]
        [DataMember(Name="canCancelEnrollment", EmitDefaultValue=true)]
        public bool CanCancelEnrollment { get; set; }

        /// <summary>
        /// Chinese explanation shown when enrollment is unavailable.
        /// </summary>
        /// <value>Chinese explanation shown when enrollment is unavailable.</value>
        [DataMember(Name="enrollmentUnavailableReason", EmitDefaultValue=true)]
        public string? EnrollmentUnavailableReason { get; set; }

    }
}
