/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 用户登录请求，username 可填写用户名或学工号。
    /// </summary>
    [DataContract]
    public partial class LoginRequest 
    {
        /// <summary>
        /// 用户名或学工号。
        /// </summary>
        /// <value>用户名或学工号。</value>
        /* <example>stu_public</example> */
        [Required]
        [StringLength(50, MinimumLength=1)]
        [DataMember(Name="username", EmitDefaultValue=false)]
        public string Username { get; set; }

        /// <summary>
        /// 登录密码。
        /// </summary>
        /// <value>登录密码。</value>
        /* <example>ClubHub123</example> */
        [Required]
        [StringLength(128, MinimumLength=1)]
        [DataMember(Name="password", EmitDefaultValue=false)]
        public string Password { get; set; }

        /// <summary>
        /// 由验证码接口签发的短时一次性挑战令牌。
        /// </summary>
        /// <value>由验证码接口签发的短时一次性挑战令牌。</value>
        /* <example>2d8J6wW8V0d7fH1n4Y4p9Q2s3A5b6C7D8E9F0gH1I2J</example> */
        [Required]
        [RegularExpression("^[A-Za-z0-9_-]+$")]
        [StringLength(64, MinimumLength=40)]
        [DataMember(Name="captchaToken", EmitDefaultValue=false)]
        public string CaptchaToken { get; set; }

        /// <summary>
        /// 用户从验证码图片中识别出的 5 位数字，不区分大小写。
        /// </summary>
        /// <value>用户从验证码图片中识别出的 5 位数字，不区分大小写。</value>
        /* <example>52843</example> */
        [Required]
        [RegularExpression("^[0-9]{5}$")]
        [StringLength(5, MinimumLength=5)]
        [DataMember(Name="captchaCode", EmitDefaultValue=false)]
        public string CaptchaCode { get; set; }

    }
}
