/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 权限检查结果。
    /// </summary>
    [DataContract]
    public partial class PermissionCheckResult 
    {
        /// <summary>
        /// 被检查的用户 ID。
        /// </summary>
        /// <value>被检查的用户 ID。</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="userId", EmitDefaultValue=true)]
        public int UserId { get; set; }

        /// <summary>
        /// 被检查的权限编码。
        /// </summary>
        /// <value>被检查的权限编码。</value>
        /* <example>club:internal:view</example> */
        [Required]
        [DataMember(Name="permission", EmitDefaultValue=false)]
        public string Permission { get; set; }

        /// <summary>
        /// 权限检查涉及的社团 ID；全局权限可为空。
        /// </summary>
        /// <value>权限检查涉及的社团 ID；全局权限可为空。</value>
        /* <example>1</example> */
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int? ClubId { get; set; }

        /// <summary>
        /// 是否允许访问。
        /// </summary>
        /// <value>是否允许访问。</value>
        /* <example>true</example> */
        [JsonRequired]
        [Required]
        [DataMember(Name="allowed", EmitDefaultValue=true)]
        public bool Allowed { get; set; }

        /// <summary>
        /// 命中该权限的角色列表。
        /// </summary>
        /// <value>命中该权限的角色列表。</value>
        [Required]
        [DataMember(Name="matchedRoles", EmitDefaultValue=false)]
        public List<AuthRole> MatchedRoles { get; set; }

        /// <summary>
        /// 面向调用方的判定说明。
        /// </summary>
        /// <value>面向调用方的判定说明。</value>
        /* <example>允许访问。</example> */
        [Required]
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

    }
}
