/*
 * ClubHub API
 *
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 鏉冮檺妫€鏌ョ粨鏋溿€?    /// </summary>
    [DataContract]
    public partial class PermissionCheckResult 
    {
        /// <summary>
        /// 琚鏌ョ殑鐢ㄦ埛 ID銆?        /// </summary>
        /// <value>琚鏌ョ殑鐢ㄦ埛 ID銆?/value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="userId", EmitDefaultValue=true)]
        public int UserId { get; set; }

        /// <summary>
        /// 琚鏌ョ殑鏉冮檺缂栫爜銆?        /// </summary>
        /// <value>琚鏌ョ殑鏉冮檺缂栫爜銆?/value>
        /* <example>club:internal:view</example> */
        [Required]
        [DataMember(Name="permission", EmitDefaultValue=false)]
        public string Permission { get; set; }

        /// <summary>
        /// 鏉冮檺妫€鏌ユ秹鍙婄殑绀惧洟 ID锛涘叏灞€鏉冮檺鍙负绌恒€?        /// </summary>
        /// <value>鏉冮檺妫€鏌ユ秹鍙婄殑绀惧洟 ID锛涘叏灞€鏉冮檺鍙负绌恒€?/value>
        /* <example>1</example> */
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int? ClubId { get; set; }

        /// <summary>
        /// 鏄惁鍏佽璁块棶銆?        /// </summary>
        /// <value>鏄惁鍏佽璁块棶銆?/value>
        /* <example>true</example> */
        [Required]
        [DataMember(Name="allowed", EmitDefaultValue=true)]
        public bool Allowed { get; set; }

        /// <summary>
        /// 鍛戒腑璇ユ潈闄愮殑瑙掕壊鍒楄〃銆?        /// </summary>
        /// <value>鍛戒腑璇ユ潈闄愮殑瑙掕壊鍒楄〃銆?/value>
        [Required]
        [DataMember(Name="matchedRoles", EmitDefaultValue=false)]
        public List<AuthRole> MatchedRoles { get; set; }

        /// <summary>
        /// 闈㈠悜璋冪敤鏂圭殑鍒ゅ畾璇存槑銆?        /// </summary>
        /// <value>闈㈠悜璋冪敤鏂圭殑鍒ゅ畾璇存槑銆?/value>
        /* <example>鍏佽璁块棶銆?/example> */
        [Required]
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

    }
}

