/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Project initiation application and review result.
    /// </summary>
    [DataContract]
    public partial class Project 
    {
        /// <summary>
        /// Project id in PROJECTS.PROJECT_ID.
        /// </summary>
        /// <value>Project id in PROJECTS.PROJECT_ID.</value>
        /* <example>1001</example> */
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Club that owns the project application.
        /// </summary>
        /// <value>Club that owns the project application.</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// Project name submitted by the club.
        /// </summary>
        /// <value>Project name submitted by the club.</value>
        /* <example>校园公益服务项目</example> */
        [Required]
        [DataMember(Name="projectName", EmitDefaultValue=false)]
        public string ProjectName { get; set; }

        /// <summary>
        /// Optional project description.
        /// </summary>
        /// <value>Optional project description.</value>
        /* <example>组织社团成员开展校园公益服务。</example> */
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// Optional project leader user id.
        /// </summary>
        /// <value>Optional project leader user id.</value>
        /* <example>12</example> */
        [DataMember(Name="leaderUserId", EmitDefaultValue=true)]
        public int? LeaderUserId { get; set; }

        /// <summary>
        /// Planned project start time.
        /// </summary>
        /// <value>Planned project start time.</value>
        /* <example>2026-07-15T09:00Z</example> */
        [Required]
        [DataMember(Name="startDate", EmitDefaultValue=true)]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Optional planned project end time.
        /// </summary>
        /// <value>Optional planned project end time.</value>
        /* <example>2026-08-15T18:00Z</example> */
        [DataMember(Name="endDate", EmitDefaultValue=true)]
        public DateTime? EndDate { get; set; }


        /// <summary>
        /// Current project status.
        /// </summary>
        /// <value>Current project status.</value>
        
        public enum ProjectStatusEnum
        {
            
            /// <summary>
            /// Enum PendingEnum for pending
            /// </summary>
            [EnumMember(Value = "pending")]
            PendingEnum = 1,
            
            /// <summary>
            /// Enum RunningEnum for running
            /// </summary>
            [EnumMember(Value = "running")]
            RunningEnum = 2,
            
            /// <summary>
            /// Enum FinishedEnum for finished
            /// </summary>
            [EnumMember(Value = "finished")]
            FinishedEnum = 3,
            
            /// <summary>
            /// Enum DelayedEnum for delayed
            /// </summary>
            [EnumMember(Value = "delayed")]
            DelayedEnum = 4,
            
            /// <summary>
            /// Enum ClosedEnum for closed
            /// </summary>
            [EnumMember(Value = "closed")]
            ClosedEnum = 5
        }

        /// <summary>
        /// Current project status.
        /// </summary>
        /// <value>Current project status.</value>
        /* <example>pending</example> */
        [Required]
        [DataMember(Name="projectStatus", EmitDefaultValue=true)]
        public ProjectStatusEnum ProjectStatus { get; set; }

        /// <summary>
        /// User id of the reviewer after approval or rejection.
        /// </summary>
        /// <value>User id of the reviewer after approval or rejection.</value>
        /* <example>3</example> */
        [DataMember(Name="reviewerUserId", EmitDefaultValue=true)]
        public int? ReviewerUserId { get; set; }

        /// <summary>
        /// Optional reviewer comment.
        /// </summary>
        /// <value>Optional reviewer comment.</value>
        /* <example>立项材料完整，同意执行。</example> */
        [DataMember(Name="reviewComment", EmitDefaultValue=true)]
        public string? ReviewComment { get; set; }

        /// <summary>
        /// Project application creation time.
        /// </summary>
        /// <value>Project application creation time.</value>
        /* <example>2026-07-08T12:00Z</example> */
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

    }
}
<<<<<<< HEAD


=======
>>>>>>> 556da23 (chore(api): 从 openapi.yaml 自动生成 API 代码)
