/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Recruitment 
    {
        /// <summary>
        /// 招募记录 ID。
        /// </summary>
        /// <value>招募记录 ID。</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// 发布该纳新的社团 ID。
        /// </summary>
        /// <value>发布该纳新的社团 ID。</value>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// 发布该纳新的社团名称。
        /// </summary>
        /// <value>发布该纳新的社团名称。</value>
        /* <example>计算机协会</example> */
        [Required]
        [DataMember(Name="clubName", EmitDefaultValue=false)]
        public string ClubName { get; set; }

        /// <summary>
        /// 纳新标题。
        /// </summary>
        /// <value>纳新标题。</value>
        /* <example>2026 春季纳新</example> */
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// 纳新的补充说明，可为空。
        /// </summary>
        /// <value>纳新的补充说明，可为空。</value>
        /* <example>面向对编程、竞赛和项目协作感兴趣的同学。</example> */
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string? Description { get; set; }

        /// <summary>
        /// 纳新开始时间；审核通过后用于计算“未开始/申请中/已结束”。
        /// </summary>
        /// <value>纳新开始时间；审核通过后用于计算“未开始/申请中/已结束”。</value>
        /* <example>2026-03-01T09:00Z</example> */
        [DataMember(Name="startAt", EmitDefaultValue=true)]
        public DateTime? StartAt { get; set; }

        /// <summary>
        /// 纳新结束时间；到期后自动展示为已结束。
        /// </summary>
        /// <value>纳新结束时间；到期后自动展示为已结束。</value>
        /* <example>2026-03-20T18:00Z</example> */
        [DataMember(Name="endAt", EmitDefaultValue=true)]
        public DateTime? EndAt { get; set; }

        /// <summary>
        /// 计划录取人数上限。
        /// </summary>
        /// <value>计划录取人数上限。</value>
        /* <example>30</example> */
        [DataMember(Name="quota", EmitDefaultValue=true)]
        public int? Quota { get; set; }

        /// <summary>
        /// 报名要求或筛选标准。
        /// </summary>
        /// <value>报名要求或筛选标准。</value>
        /* <example>对社团活动有稳定参与时间，愿意参与一次面试。</example> */
        [DataMember(Name="requirements", EmitDefaultValue=true)]
        public string? Requirements { get; set; }


        /// <summary>
        /// 当前展示状态；draft 和 pending_review 为流程状态，not_started/accepting/ended 由已通过纳新的时间窗口计算得到。
        /// </summary>
        /// <value>当前展示状态；draft 和 pending_review 为流程状态，not_started/accepting/ended 由已通过纳新的时间窗口计算得到。</value>
        
        public enum RecruitStatusEnum
        {
            
            /// <summary>
            /// Enum DraftEnum for draft
            /// </summary>
            [EnumMember(Value = "draft")]
            DraftEnum = 1,
            
            /// <summary>
            /// Enum PendingReviewEnum for pending_review
            /// </summary>
            [EnumMember(Value = "pending_review")]
            PendingReviewEnum = 2,
            
            /// <summary>
            /// Enum NotStartedEnum for not_started
            /// </summary>
            [EnumMember(Value = "not_started")]
            NotStartedEnum = 3,
            
            /// <summary>
            /// Enum AcceptingEnum for accepting
            /// </summary>
            [EnumMember(Value = "accepting")]
            AcceptingEnum = 4,
            
            /// <summary>
            /// Enum EndedEnum for ended
            /// </summary>
            [EnumMember(Value = "ended")]
            EndedEnum = 5
        }

        /// <summary>
        /// 当前展示状态；draft 和 pending_review 为流程状态，not_started/accepting/ended 由已通过纳新的时间窗口计算得到。
        /// </summary>
        /// <value>当前展示状态；draft 和 pending_review 为流程状态，not_started/accepting/ended 由已通过纳新的时间窗口计算得到。</value>
        /* <example>accepting</example> */
        [Required]
        [DataMember(Name="recruitStatus", EmitDefaultValue=true)]
        public RecruitStatusEnum RecruitStatus { get; set; }

        /// <summary>
        /// 当前展示状态的中文文案。
        /// </summary>
        /// <value>当前展示状态的中文文案。</value>
        /* <example>申请中</example> */
        [Required]
        [DataMember(Name="recruitStatusText", EmitDefaultValue=false)]
        public string RecruitStatusText { get; set; }

        /// <summary>
        /// 招募创建时间。
        /// </summary>
        /// <value>招募创建时间。</value>
        /* <example>2026-02-20T08:30Z</example> */
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// 当前报名申请总数。
        /// </summary>
        /// <value>当前报名申请总数。</value>
        /* <example>18</example> */
        [Required]
        [DataMember(Name="applicationCount", EmitDefaultValue=true)]
        public int ApplicationCount { get; set; }

        /// <summary>
        /// 当前已录取申请数。
        /// </summary>
        /// <value>当前已录取申请数。</value>
        /* <example>8</example> */
        [Required]
        [DataMember(Name="acceptedCount", EmitDefaultValue=true)]
        public int AcceptedCount { get; set; }

        /// <summary>
        /// 当前查看用户在该纳新下的申请 ID；未申请时为空。
        /// </summary>
        /// <value>当前查看用户在该纳新下的申请 ID；未申请时为空。</value>
        /* <example>12</example> */
        [DataMember(Name="currentUserApplicationId", EmitDefaultValue=true)]
        public int? CurrentUserApplicationId { get; set; }

        /// <summary>
        /// 当前查看用户的申请状态；未申请时为空。
        /// </summary>
        /// <value>当前查看用户的申请状态；未申请时为空。</value>
        /* <example>pending</example> */
        [DataMember(Name="currentUserApplicationStatus", EmitDefaultValue=true)]
        public string? CurrentUserApplicationStatus { get; set; }

        /// <summary>
        /// 当前查看用户申请状态的中文文案；未申请时为空。
        /// </summary>
        /// <value>当前查看用户申请状态的中文文案；未申请时为空。</value>
        /* <example>待筛选</example> */
        [DataMember(Name="currentUserApplicationStatusText", EmitDefaultValue=true)]
        public string? CurrentUserApplicationStatusText { get; set; }

        /// <summary>
        /// 当前查看用户是否已经是该社团成员；干部和负责人也按成员处理。
        /// </summary>
        /// <value>当前查看用户是否已经是该社团成员；干部和负责人也按成员处理。</value>
        /* <example>false</example> */
        [Required]
        [DataMember(Name="currentUserIsMember", EmitDefaultValue=true)]
        public bool CurrentUserIsMember { get; set; }

        /// <summary>
        /// 当前查看用户是否应将该纳新归入本社团提出的纳新；同社团干部、负责人共享该视角。
        /// </summary>
        /// <value>当前查看用户是否应将该纳新归入本社团提出的纳新；同社团干部、负责人共享该视角。</value>
        /* <example>true</example> */
        [Required]
        [DataMember(Name="isOwnProposal", EmitDefaultValue=true)]
        public bool IsOwnProposal { get; set; }

        /// <summary>
        /// 当前查看用户是否可以管理该纳新和其报名。
        /// </summary>
        /// <value>当前查看用户是否可以管理该纳新和其报名。</value>
        /* <example>true</example> */
        [Required]
        [DataMember(Name="canManage", EmitDefaultValue=true)]
        public bool CanManage { get; set; }

        /// <summary>
        /// 当前查看用户是否可以编辑该纳新草稿。
        /// </summary>
        /// <value>当前查看用户是否可以编辑该纳新草稿。</value>
        /* <example>false</example> */
        [Required]
        [DataMember(Name="canEdit", EmitDefaultValue=true)]
        public bool CanEdit { get; set; }

        /// <summary>
        /// 当前查看用户是否可以删除该纳新草稿。
        /// </summary>
        /// <value>当前查看用户是否可以删除该纳新草稿。</value>
        /* <example>false</example> */
        [Required]
        [DataMember(Name="canDelete", EmitDefaultValue=true)]
        public bool CanDelete { get; set; }

        /// <summary>
        /// 当前查看用户是否可以审核该纳新。
        /// </summary>
        /// <value>当前查看用户是否可以审核该纳新。</value>
        /* <example>false</example> */
        [Required]
        [DataMember(Name="canReview", EmitDefaultValue=true)]
        public bool CanReview { get; set; }

    }
}
