/*
 * ClubHub API
 *
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 鐢ㄦ埛娉ㄥ唽璇锋眰銆傚鐢熷宸ュ彿涓?7 浣嶆暟瀛楋紝鏁欏笀宸ュ彿涓?5 浣嶆暟瀛椼€?    /// </summary>
    [DataContract]
    public partial class RegisterRequest 
    {
        /// <summary>
        /// 鐧诲綍鐢ㄦ埛鍚嶏紝娉ㄥ唽鍚庡繀椤诲敮涓€銆?        /// </summary>
        /// <value>鐧诲綍鐢ㄦ埛鍚嶏紝娉ㄥ唽鍚庡繀椤诲敮涓€銆?/value>
        /* <example>stu_public</example> */
        [Required]
        [StringLength(50, MinimumLength=3)]
        [DataMember(Name="username", EmitDefaultValue=false)]
        public string Username { get; set; }

        /// <summary>
        /// 鐧诲綍瀵嗙爜锛屾湇鍔＄浠呬繚瀛樺瘑鐮佹憳瑕併€?        /// </summary>
        /// <value>鐧诲綍瀵嗙爜锛屾湇鍔＄浠呬繚瀛樺瘑鐮佹憳瑕併€?/value>
        /* <example>ClubHub123</example> */
        [Required]
        [StringLength(128, MinimumLength=6)]
        [DataMember(Name="password", EmitDefaultValue=false)]
        public string Password { get; set; }

        /// <summary>
        /// 鐢ㄦ埛鐪熷疄濮撳悕銆?        /// </summary>
        /// <value>鐢ㄦ埛鐪熷疄濮撳悕銆?/value>
        /* <example>寮犱笁</example> */
        [Required]
        [StringLength(50, MinimumLength=1)]
        [DataMember(Name="realName", EmitDefaultValue=false)]
        public string RealName { get; set; }

        /// <summary>
        /// 瀛﹀伐鍙凤紱瀛︾敓 7 浣嶏紝鏁欏笀 5 浣嶃€?        /// </summary>
        /// <value>瀛﹀伐鍙凤紱瀛︾敓 7 浣嶏紝鏁欏笀 5 浣嶃€?/value>
        /* <example>2450001</example> */
        [Required]
        [RegularExpression("^([0-9]{7}|[0-9]{5})$")]
        [StringLength(7, MinimumLength=5)]
        [DataMember(Name="studentNo", EmitDefaultValue=false)]
        public string StudentNo { get; set; }

        /// <summary>
        /// 鎬у埆锛屽彲涓虹┖锛涘綋鍓嶆敮鎸佺敺銆佸コ銆?        /// </summary>
        /// <value>鎬у埆锛屽彲涓虹┖锛涘綋鍓嶆敮鎸佺敺銆佸コ銆?/value>
        /* <example>鐢?/example> */
        [RegularExpression("^(鐢穦濂?$")]
        [MaxLength(10)]
        [DataMember(Name="gender", EmitDefaultValue=true)]
        public string? Gender { get; set; }

        /// <summary>
        /// 鑱旂郴鐢佃瘽锛屽彲涓虹┖銆?        /// </summary>
        /// <value>鑱旂郴鐢佃瘽锛屽彲涓虹┖銆?/value>
        /* <example>13800138000</example> */
        [RegularExpression("^[0-9+\\-\\s()]{0,20}$")]
        [MaxLength(20)]
        [DataMember(Name="phone", EmitDefaultValue=true)]
        public string? Phone { get; set; }

        /// <summary>
        /// 閭鍦板潃锛屽彲涓虹┖銆?        /// </summary>
        /// <value>閭鍦板潃锛屽彲涓虹┖銆?/value>
        /* <example>zhangsan@example.com</example> */
        [MaxLength(100)]
        [DataMember(Name="email", EmitDefaultValue=true)]
        public string? Email { get; set; }

        /// <summary>
        /// 鎵€灞炲闄紝鍙负绌恒€?        /// </summary>
        /// <value>鎵€灞炲闄紝鍙负绌恒€?/value>
        /* <example>杞欢瀛﹂櫌</example> */
        [MaxLength(100)]
        [DataMember(Name="college", EmitDefaultValue=true)]
        public string? College { get; set; }

        /// <summary>
        /// 鎵€灞炰笓涓氾紝鍙负绌恒€?        /// </summary>
        /// <value>鎵€灞炰笓涓氾紝鍙负绌恒€?/value>
        /* <example>杞欢宸ョ▼</example> */
        [MaxLength(100)]
        [DataMember(Name="major", EmitDefaultValue=true)]
        public string? Major { get; set; }

        /// <summary>
        /// 骞寸骇锛屽彲涓虹┖銆?        /// </summary>
        /// <value>骞寸骇锛屽彲涓虹┖銆?/value>
        /* <example>2024</example> */
        [MaxLength(20)]
        [DataMember(Name="grade", EmitDefaultValue=true)]
        public string? Grade { get; set; }

    }
}

