/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 用户注册请求。学生学工号为 7 位数字，教师工号为 5 位数字。
    /// </summary>
    [DataContract]
    public partial class RegisterRequest 
    {
        /// <summary>
        /// 登录用户名，注册后必须唯一。
        /// </summary>
        /// <value>登录用户名，注册后必须唯一。</value>
        /* <example>stu_public</example> */
        [Required]
        [StringLength(50, MinimumLength=3)]
        [DataMember(Name="username", EmitDefaultValue=false)]
        public string Username { get; set; }

        /// <summary>
        /// 登录密码，服务端仅保存密码摘要。
        /// </summary>
        /// <value>登录密码，服务端仅保存密码摘要。</value>
        /* <example>ClubHub123</example> */
        [Required]
        [StringLength(128, MinimumLength=6)]
        [DataMember(Name="password", EmitDefaultValue=false)]
        public string Password { get; set; }

        /// <summary>
        /// 用户真实姓名。
        /// </summary>
        /// <value>用户真实姓名。</value>
        /* <example>张三</example> */
        [Required]
        [StringLength(50, MinimumLength=1)]
        [DataMember(Name="realName", EmitDefaultValue=false)]
        public string RealName { get; set; }

        /// <summary>
        /// 学工号；学生 7 位，教师 5 位。
        /// </summary>
        /// <value>学工号；学生 7 位，教师 5 位。</value>
        /* <example>2450001</example> */
        [Required]
        [RegularExpression("^([0-9]{7}|[0-9]{5})$")]
        [StringLength(7, MinimumLength=5)]
        [DataMember(Name="studentNo", EmitDefaultValue=false)]
        public string StudentNo { get; set; }

        /// <summary>
        /// 性别，可为空；当前支持男、女。
        /// </summary>
        /// <value>性别，可为空；当前支持男、女。</value>
        /* <example>男</example> */
        [RegularExpression("^(男|女)$")]
        [MaxLength(10)]
        [DataMember(Name="gender", EmitDefaultValue=true)]
        public string? Gender { get; set; }

        /// <summary>
        /// 联系电话，可为空。
        /// </summary>
        /// <value>联系电话，可为空。</value>
        /* <example>13800138000</example> */
        [RegularExpression("^[0-9+\\-\\s()]{0,20}$")]
        [MaxLength(20)]
        [DataMember(Name="phone", EmitDefaultValue=true)]
        public string? Phone { get; set; }

        /// <summary>
        /// 邮箱地址，可为空。
        /// </summary>
        /// <value>邮箱地址，可为空。</value>
        /* <example>zhangsan@example.com</example> */
        [MaxLength(100)]
        [DataMember(Name="email", EmitDefaultValue=true)]
        public string? Email { get; set; }

        /// <summary>
        /// 所属学院，可为空。
        /// </summary>
        /// <value>所属学院，可为空。</value>
        /* <example>软件学院</example> */
        [MaxLength(100)]
        [DataMember(Name="college", EmitDefaultValue=true)]
        public string? College { get; set; }

        /// <summary>
        /// 所属专业，可为空。
        /// </summary>
        /// <value>所属专业，可为空。</value>
        /* <example>软件工程</example> */
        [MaxLength(100)]
        [DataMember(Name="major", EmitDefaultValue=true)]
        public string? Major { get; set; }

        /// <summary>
        /// 年级，可为空。
        /// </summary>
        /// <value>年级，可为空。</value>
        /* <example>2024</example> */
        [MaxLength(20)]
        [DataMember(Name="grade", EmitDefaultValue=true)]
        public string? Grade { get; set; }

    }
}

