/*
 * ClubHub API
 *
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Request body for reviewing a project initiation application.
    /// </summary>
    [DataContract]
    public partial class ReviewProjectRequest 
    {
        /// <summary>
        /// 褰撳墠瀹℃牳鎿嶄綔鐢ㄦ埛 ID锛涗粎鏈ぞ鍥㈡寚瀵艰€佸笀鍙鏍搞€?        /// </summary>
        /// <value>褰撳墠瀹℃牳鎿嶄綔鐢ㄦ埛 ID锛涗粎鏈ぞ鍥㈡寚瀵艰€佸笀鍙鏍搞€?/value>
        /* <example>3</example> */
        [Required]
        [DataMember(Name="currentUserId", EmitDefaultValue=true)]
        public int CurrentUserId { get; set; }


        /// <summary>
        /// Review result. running means approved; closed means rejected or closed.
        /// </summary>
        /// <value>Review result. running means approved; closed means rejected or closed.</value>
        
        public enum ProjectStatusEnum
        {
            
            /// <summary>
            /// Enum RunningEnum for running
            /// </summary>
            [EnumMember(Value = "running")]
            RunningEnum = 1,
            
            /// <summary>
            /// Enum ClosedEnum for closed
            /// </summary>
            [EnumMember(Value = "closed")]
            ClosedEnum = 2
        }

        /// <summary>
        /// Review result. running means approved; closed means rejected or closed.
        /// </summary>
        /// <value>Review result. running means approved; closed means rejected or closed.</value>
        /* <example>running</example> */
        [Required]
        [DataMember(Name="projectStatus", EmitDefaultValue=true)]
        public ProjectStatusEnum ProjectStatus { get; set; }

        /// <summary>
        /// Optional review comment.
        /// </summary>
        /// <value>Optional review comment.</value>
        /* <example>绔嬮」鏉愭枡瀹屾暣锛屽悓鎰忔墽琛屻€?/example> */
        [DataMember(Name="reviewComment", EmitDefaultValue=true)]
        public string? ReviewComment { get; set; }

    }
}
