/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 社团管理员或系统管理员审核课程、资源的请求。
    /// </summary>
    [DataContract]
    public partial class ReviewLearningItemRequest 
    {

        /// <summary>
        /// approved 表示审核通过并发布，rejected 表示驳回。
        /// </summary>
        /// <value>approved 表示审核通过并发布，rejected 表示驳回。</value>
        
        public enum ResultEnum
        {
            
            /// <summary>
            /// Enum ApprovedEnum for approved
            /// </summary>
            [EnumMember(Value = "approved")]
            ApprovedEnum = 1,
            
            /// <summary>
            /// Enum RejectedEnum for rejected
            /// </summary>
            [EnumMember(Value = "rejected")]
            RejectedEnum = 2
        }

        /// <summary>
        /// approved 表示审核通过并发布，rejected 表示驳回。
        /// </summary>
        /// <value>approved 表示审核通过并发布，rejected 表示驳回。</value>
        [Required]
        [DataMember(Name="result", EmitDefaultValue=true)]
        public ResultEnum Result { get; set; }

    }
}
