/*
 * ClubHub API
 *
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 绯荤粺棰勭疆瑙掕壊瀹氫箟銆?    /// </summary>
    [DataContract]
    public partial class RoleDefinition 
    {
        /// <summary>
        /// 瑙掕壊缂栫爜銆?        /// </summary>
        /// <value>瑙掕壊缂栫爜銆?/value>
        /* <example>STUDENT</example> */
        [Required]
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// 瑙掕壊鍚嶇О銆?        /// </summary>
        /// <value>瑙掕壊鍚嶇О銆?/value>
        /* <example>鏅€氬鐢?/example> */
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }


        /// <summary>
        /// 瑙掕壊浣滅敤鍩熴€?        /// </summary>
        /// <value>瑙掕壊浣滅敤鍩熴€?/value>
        
        public enum ScopeEnum
        {
            
            /// <summary>
            /// Enum SystemEnum for system
            /// </summary>
            [EnumMember(Value = "system")]
            SystemEnum = 1,
            
            /// <summary>
            /// Enum ClubEnum for club
            /// </summary>
            [EnumMember(Value = "club")]
            ClubEnum = 2
        }

        /// <summary>
        /// 瑙掕壊浣滅敤鍩熴€?        /// </summary>
        /// <value>瑙掕壊浣滅敤鍩熴€?/value>
        /* <example>system</example> */
        [Required]
        [DataMember(Name="scope", EmitDefaultValue=true)]
        public ScopeEnum Scope { get; set; }

        /// <summary>
        /// 瑙掕壊涓氬姟璇存槑銆?        /// </summary>
        /// <value>瑙掕壊涓氬姟璇存槑銆?/value>
        /* <example>娉ㄥ唽鍚庨粯璁よ鑹诧紝鍙淮鎶や釜浜轰俊鎭苟娴忚鍏紑鍐呭銆?/example> */
        [Required]
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// 瑙掕壊鎷ユ湁鐨勬潈闄愮紪鐮佸垪琛ㄣ€?        /// </summary>
        /// <value>瑙掕壊鎷ユ湁鐨勬潈闄愮紪鐮佸垪琛ㄣ€?/value>
        /* <example>[&quot;profile:view&quot;,&quot;public:view&quot;]</example> */
        [Required]
        [DataMember(Name="permissions", EmitDefaultValue=false)]
        public List<string> Permissions { get; set; }

    }
}

