/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 角色分配结果。
    /// </summary>
    [DataContract]
    public partial class RoleAssignmentResult 
    {
        /// <summary>
        /// 被分配角色的用户 ID。
        /// </summary>
        /// <value>被分配角色的用户 ID。</value>
        /* <example>2</example> */
        [Required]
        [DataMember(Name="targetUserId", EmitDefaultValue=true)]
        public int TargetUserId { get; set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [Required]
        [DataMember(Name="role", EmitDefaultValue=false)]
        public AuthRole Role { get; set; }

        /// <summary>
        /// 该角色分配是否原本已存在。
        /// </summary>
        /// <value>该角色分配是否原本已存在。</value>
        /* <example>false</example> */
        [Required]
        [DataMember(Name="alreadyExists", EmitDefaultValue=true)]
        public bool AlreadyExists { get; set; }

        /// <summary>
        /// 角色分配结果说明。
        /// </summary>
        /// <value>角色分配结果说明。</value>
        /* <example>角色分配成功。</example> */
        [Required]
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

    }
}
