/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdateVenueRequest 
    {
        /// <summary>
        /// 执行维护操作的用户 ID，用于校验 venue:update 权限。
        /// </summary>
        /// <value>执行维护操作的用户 ID，用于校验 venue:update 权限。</value>
        [Required]
        [DataMember(Name="operatorUserId", EmitDefaultValue=true)]
        public int OperatorUserId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [MaxLength(255)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Building
        /// </summary>
        [MaxLength(255)]
        [DataMember(Name="building", EmitDefaultValue=true)]
        public string? Building { get; set; }

        /// <summary>
        /// Gets or Sets RoomNo
        /// </summary>
        [MaxLength(255)]
        [DataMember(Name="roomNo", EmitDefaultValue=true)]
        public string? RoomNo { get; set; }

        /// <summary>
        /// Gets or Sets Capacity
        /// </summary>
        [Required]
        [DataMember(Name="capacity", EmitDefaultValue=true)]
        public int Capacity { get; set; }

        /// <summary>
        /// Gets or Sets ManagerUserId
        /// </summary>
        [DataMember(Name="managerUserId", EmitDefaultValue=true)]
        public int? ManagerUserId { get; set; }

    }
}
