/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 更新成员部门和小组归属的请求体。
    /// </summary>
    [DataContract]
    public partial class UpdateClubMemberGroupingRequest 
    {
        /// <summary>
        /// 成员调整后的部门名称；传空或 null 表示不归属任何部门。
        /// </summary>
        /// <value>成员调整后的部门名称；传空或 null 表示不归属任何部门。</value>
        /* <example>技术部</example> */
        [DataMember(Name="departmentName", EmitDefaultValue=true)]
        public string? DepartmentName { get; set; }

        /// <summary>
        /// 成员调整后的小组名称；传空或 null 表示不归属任何小组。
        /// </summary>
        /// <value>成员调整后的小组名称；传空或 null 表示不归属任何小组。</value>
        /* <example>后端组</example> */
        [DataMember(Name="groupName", EmitDefaultValue=true)]
        public string? GroupName { get; set; }

    }
}
