/*
 * ClubHub API
 *
 * ClubHub 楂樻牎绀惧洟杩愯惀涓庡崗鍚岀鐞嗗钩鍙?API銆? **API-first 寮€鍙戞祦绋?*锛氫慨鏀规湰鏂囦欢 鈫?push 鈫?CI 鑷姩鐢熸垚鍓嶅悗绔唬鐮?鈫?git pull 鎷夊彇鐢熸垚浠ｇ爜 鈫?鍦?Controller / Services / Vue 缁勪欢涓墜鍐欎笟鍔￠€昏緫銆?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UserSummary 
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name="username", EmitDefaultValue=true)]
        public string? Username { get; set; }

        /// <summary>
        /// Gets or Sets RealName
        /// </summary>
        [DataMember(Name="realName", EmitDefaultValue=true)]
        public string? RealName { get; set; }

        /// <summary>
        /// Gets or Sets StudentNo
        /// </summary>
        [DataMember(Name="studentNo", EmitDefaultValue=true)]
        public string? StudentNo { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [Required]
        [DataMember(Name="displayName", EmitDefaultValue=false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets AccountStatus
        /// </summary>
        [DataMember(Name="accountStatus", EmitDefaultValue=true)]
        public string? AccountStatus { get; set; }

        /// <summary>
        /// Gets or Sets Roles
        /// </summary>
        [Required]
        [DataMember(Name="roles", EmitDefaultValue=false)]
        public List<UserRoleSummary> Roles { get; set; }

        /// <summary>
        /// Gets or Sets Memberships
        /// </summary>
        [Required]
        [DataMember(Name="memberships", EmitDefaultValue=false)]
        public List<UserMembershipSummary> Memberships { get; set; }

        /// <summary>
        /// Gets or Sets CanSubmitClubApplication
        /// </summary>
        [Required]
        [DataMember(Name="canSubmitClubApplication", EmitDefaultValue=true)]
        public bool CanSubmitClubApplication { get; set; }

        /// <summary>
        /// Gets or Sets CanReviewClubApplication
        /// </summary>
        [Required]
        [DataMember(Name="canReviewClubApplication", EmitDefaultValue=true)]
        public bool CanReviewClubApplication { get; set; }

    }
}

