/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VenueReservation 
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets VenueId
        /// </summary>
        [Required]
        [DataMember(Name="venueId", EmitDefaultValue=true)]
        public int VenueId { get; set; }

        /// <summary>
        /// Gets or Sets VenueName
        /// </summary>
        [Required]
        [DataMember(Name="venueName", EmitDefaultValue=false)]
        public string VenueName { get; set; }

        /// <summary>
        /// Gets or Sets ClubId
        /// </summary>
        [Required]
        [DataMember(Name="clubId", EmitDefaultValue=true)]
        public int ClubId { get; set; }

        /// <summary>
        /// Gets or Sets ClubName
        /// </summary>
        [Required]
        [DataMember(Name="clubName", EmitDefaultValue=false)]
        public string ClubName { get; set; }

        /// <summary>
        /// Gets or Sets ActivityId
        /// </summary>
        [DataMember(Name="activityId", EmitDefaultValue=true)]
        public int? ActivityId { get; set; }

        /// <summary>
        /// Gets or Sets ActivityTitle
        /// </summary>
        [DataMember(Name="activityTitle", EmitDefaultValue=true)]
        public string? ActivityTitle { get; set; }

        /// <summary>
        /// Gets or Sets ApplicantUserId
        /// </summary>
        [Required]
        [DataMember(Name="applicantUserId", EmitDefaultValue=true)]
        public int ApplicantUserId { get; set; }

        /// <summary>
        /// Gets or Sets ApplicantName
        /// </summary>
        [DataMember(Name="applicantName", EmitDefaultValue=true)]
        public string? ApplicantName { get; set; }

        /// <summary>
        /// 预约开始时间。响应统一返回 UTC 时间戳，前端按北京时间展示。
        /// </summary>
        /// <value>预约开始时间。响应统一返回 UTC 时间戳，前端按北京时间展示。</value>
        [Required]
        [DataMember(Name="startTime", EmitDefaultValue=true)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 预约结束时间。响应统一返回 UTC 时间戳，前端按北京时间展示。
        /// </summary>
        /// <value>预约结束时间。响应统一返回 UTC 时间戳，前端按北京时间展示。</value>
        [Required]
        [DataMember(Name="endTime", EmitDefaultValue=true)]
        public DateTime EndTime { get; set; }

        /// <summary>
        /// Gets or Sets Purpose
        /// </summary>
        [Required]
        [DataMember(Name="purpose", EmitDefaultValue=false)]
        public string Purpose { get; set; }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum PendingEnum for pending
            /// </summary>
            [EnumMember(Value = "pending")]
            PendingEnum = 1,
            
            /// <summary>
            /// Enum ApprovedEnum for approved
            /// </summary>
            [EnumMember(Value = "approved")]
            ApprovedEnum = 2,
            
            /// <summary>
            /// Enum RejectedEnum for rejected
            /// </summary>
            [EnumMember(Value = "rejected")]
            RejectedEnum = 3,
            
            /// <summary>
            /// Enum CancelledEnum for cancelled
            /// </summary>
            [EnumMember(Value = "cancelled")]
            CancelledEnum = 4
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets ReviewerUserId
        /// </summary>
        [DataMember(Name="reviewerUserId", EmitDefaultValue=true)]
        public int? ReviewerUserId { get; set; }

        /// <summary>
        /// Gets or Sets ReviewerName
        /// </summary>
        [DataMember(Name="reviewerName", EmitDefaultValue=true)]
        public string? ReviewerName { get; set; }

        /// <summary>
        /// Gets or Sets ReviewComment
        /// </summary>
        [MaxLength(255)]
        [DataMember(Name="reviewComment", EmitDefaultValue=true)]
        public string? ReviewComment { get; set; }

        /// <summary>
        /// 创建时间。响应统一返回 UTC 时间戳，前端按北京时间展示。
        /// </summary>
        /// <value>创建时间。响应统一返回 UTC 时间戳，前端按北京时间展示。</value>
        [Required]
        [DataMember(Name="createdAt", EmitDefaultValue=true)]
        public DateTime CreatedAt { get; set; }

    }
}
