/*
 * ClubHub API
 *
 * ClubHub 高校社团运营与协同管理平台 API。  **API-first 开发流程**：修改本文件 → push → CI 自动生成前后端代码 → git pull 拉取生成代码 → 在 Controller / Services / Vue 组件中手写业务逻辑。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 已通过预约的脱敏占用时段，仅用于场地状态展示和前端冲突提示。
    /// </summary>
    [DataContract]
    public partial class VenueOccupiedSlot 
    {
        /// <summary>
        /// 预约记录 ID。
        /// </summary>
        /// <value>预约记录 ID。</value>
        /* <example>301</example> */
        [Required]
        [DataMember(Name="reservationId", EmitDefaultValue=true)]
        public int ReservationId { get; set; }

        /// <summary>
        /// 场地 ID。
        /// </summary>
        /// <value>场地 ID。</value>
        /* <example>5</example> */
        [Required]
        [DataMember(Name="venueId", EmitDefaultValue=true)]
        public int VenueId { get; set; }

        /// <summary>
        /// 场地名称。
        /// </summary>
        /// <value>场地名称。</value>
        /* <example>大学生活动中心 201</example> */
        [Required]
        [DataMember(Name="venueName", EmitDefaultValue=false)]
        public string VenueName { get; set; }

        /// <summary>
        /// 占用开始时间。响应统一返回 UTC 时间戳，前端按北京时间展示。
        /// </summary>
        /// <value>占用开始时间。响应统一返回 UTC 时间戳，前端按北京时间展示。</value>
        /* <example>2026-07-10T10:00Z</example> */
        [Required]
        [DataMember(Name="startTime", EmitDefaultValue=true)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 占用结束时间。响应统一返回 UTC 时间戳，前端按北京时间展示。
        /// </summary>
        /// <value>占用结束时间。响应统一返回 UTC 时间戳，前端按北京时间展示。</value>
        /* <example>2026-07-10T12:00Z</example> */
        [Required]
        [DataMember(Name="endTime", EmitDefaultValue=true)]
        public DateTime EndTime { get; set; }

    }
}
